// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/transfer/v1/denomtrace.proto

package types

import (
	fmt "fmt"
	math "math"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DenomTrace contains the base denomination for ICS20 fungible tokens and the
// source tracing information path.
//
// Deprecated: Do not use.
type DenomTrace struct {
	// path defines the chain of port/channel identifiers used for tracing the
	// source of the fungible token.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// base denomination of the relayed fungible token.
	BaseDenom string `protobuf:"bytes,2,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
}

func (m *DenomTrace) Reset()                    { _ = "STUB: not implemented"; return }
func (m *DenomTrace) String() string            { _ = "STUB: not implemented"; return "" }
func (*DenomTrace) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*DenomTrace) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *DenomTrace) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *DenomTrace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *DenomTrace) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *DenomTrace) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *DenomTrace) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_DenomTrace proto.InternalMessageInfo

func (m *DenomTrace) GetPath() string { _ = "STUB: not implemented"; return "" }

func (m *DenomTrace) GetBaseDenom() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*DenomTrace)(nil), "ibc.applications.transfer.v1.DenomTrace")
}

func init() {
	proto.RegisterFile("ibc/applications/transfer/v1/denomtrace.proto", fileDescriptor_c400148599bf8bc8)
}

var fileDescriptor_c400148599bf8bc8 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0x4c, 0x4a, 0xd6,
	0x4f, 0x2c, 0x28, 0xc8, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2f, 0x29, 0x4a,
	0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0xd2, 0x2f, 0x33, 0xd4, 0x4f, 0x49, 0xcd, 0xcb, 0xcf, 0x2d, 0x29,
	0x4a, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xc9, 0x4c, 0x4a, 0xd6, 0x43,
	0x56, 0xae, 0x07, 0x53, 0xae, 0x57, 0x66, 0xa8, 0xe4, 0xcc, 0xc5, 0xe5, 0x02, 0xd2, 0x11, 0x02,
	0xd2, 0x21, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x58, 0x92, 0x21, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0x66, 0x0b, 0xc9, 0x72, 0x71, 0x25, 0x25, 0x16, 0xa7, 0xc6, 0x83, 0x0d, 0x96, 0x60, 0x02,
	0xcb, 0x70, 0x82, 0x44, 0xc0, 0xfa, 0xac, 0x98, 0x24, 0x18, 0x9d, 0x82, 0x4e, 0x3c, 0x92, 0x63,
	0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96,
	0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x22, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39,
	0x3f, 0x57, 0x3f, 0x39, 0xbf, 0x38, 0x37, 0xbf, 0x58, 0x3f, 0x33, 0x29, 0x59, 0x37, 0x3d, 0x5f,
	0xbf, 0xcc, 0xd0, 0x50, 0x3f, 0x37, 0x3f, 0xa5, 0x34, 0x27, 0xb5, 0x18, 0xe4, 0x19, 0x24, 0x4f,
	0x94, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x5d, 0x6f, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xc3, 0x73, 0x07, 0x4c, 0xee, 0x00, 0x00, 0x00,
}

func (m *DenomTrace) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *DenomTrace) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *DenomTrace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintDenomtrace(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *DenomTrace) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovDenomtrace(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozDenomtrace(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *DenomTrace) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipDenomtrace(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthDenomtrace        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDenomtrace          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDenomtrace = fmt.Errorf("proto: unexpected end of group")
)
