// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/connection/v1/connection.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/core/23-commitment/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State defines if a connection is in one of the following states:
// INIT, TRYOPEN, OPEN or UNINITIALIZED.
type State int32

const (
	// Default State
	UNINITIALIZED State = 0
	// A connection end has just started the opening handshake.
	INIT State = 1
	// A connection end has acknowledged the handshake step on the counterparty
	// chain.
	TRYOPEN State = 2
	// A connection end has completed the handshake.
	OPEN State = 3
)

var State_name = map[int32]string{
	0: "STATE_UNINITIALIZED_UNSPECIFIED",
	1: "STATE_INIT",
	2: "STATE_TRYOPEN",
	3: "STATE_OPEN",
}

var State_value = map[string]int32{
	"STATE_UNINITIALIZED_UNSPECIFIED": 0,
	"STATE_INIT":                      1,
	"STATE_TRYOPEN":                   2,
	"STATE_OPEN":                      3,
}

func (x State) String() string { _ = "STUB: not implemented"; return "" }

func (State) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// ConnectionEnd defines a stateful object on a chain connected to another
// separate one.
// NOTE: there must only be 2 defined ConnectionEnds to establish
// a connection between two chains.
type ConnectionEnd struct {
	// client associated with this connection.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// IBC version which can be utilised to determine encodings or protocols for
	// channels or packets utilising this connection.
	Versions []*Version `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	// current state of the connection end.
	State State `protobuf:"varint,3,opt,name=state,proto3,enum=ibc.core.connection.v1.State" json:"state,omitempty"`
	// counterparty chain associated with this connection.
	Counterparty Counterparty `protobuf:"bytes,4,opt,name=counterparty,proto3" json:"counterparty"`
	// delay period that must pass before a consensus state can be used for
	// packet-verification NOTE: delay period logic is only implemented by some
	// clients.
	DelayPeriod uint64 `protobuf:"varint,5,opt,name=delay_period,json=delayPeriod,proto3" json:"delay_period,omitempty"`
}

func (m *ConnectionEnd) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConnectionEnd) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConnectionEnd) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConnectionEnd) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConnectionEnd) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConnectionEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConnectionEnd) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConnectionEnd) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConnectionEnd) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConnectionEnd proto.InternalMessageInfo

// IdentifiedConnection defines a connection with additional connection
// identifier field.
type IdentifiedConnection struct {
	// connection identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// client associated with this connection.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// IBC version which can be utilised to determine encodings or protocols for
	// channels or packets utilising this connection
	Versions []*Version `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	// current state of the connection end.
	State State `protobuf:"varint,4,opt,name=state,proto3,enum=ibc.core.connection.v1.State" json:"state,omitempty"`
	// counterparty chain associated with this connection.
	Counterparty Counterparty `protobuf:"bytes,5,opt,name=counterparty,proto3" json:"counterparty"`
	// delay period associated with this connection.
	DelayPeriod uint64 `protobuf:"varint,6,opt,name=delay_period,json=delayPeriod,proto3" json:"delay_period,omitempty"`
}

func (m *IdentifiedConnection) Reset()         { _ = "STUB: not implemented"; return }
func (m *IdentifiedConnection) String() string { _ = "STUB: not implemented"; return "" }
func (*IdentifiedConnection) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*IdentifiedConnection) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IdentifiedConnection) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IdentifiedConnection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IdentifiedConnection) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *IdentifiedConnection) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *IdentifiedConnection) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_IdentifiedConnection proto.InternalMessageInfo

// Counterparty defines the counterparty chain associated with a connection end.
type Counterparty struct {
	// identifies the client on the counterparty chain associated with a given
	// connection.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// identifies the connection end on the counterparty chain associated with a
	// given connection.
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// commitment merkle prefix of the counterparty chain.
	Prefix types.MerklePrefix `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix"`
}

func (m *Counterparty) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Counterparty) String() string            { _ = "STUB: not implemented"; return "" }
func (*Counterparty) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Counterparty) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Counterparty) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Counterparty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Counterparty) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Counterparty) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Counterparty) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Counterparty proto.InternalMessageInfo

// ClientPaths define all the connection paths for a client state.
type ClientPaths struct {
	// list of connection paths
	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (m *ClientPaths) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientPaths) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientPaths) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientPaths) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientPaths) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientPaths) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientPaths) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientPaths) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientPaths proto.InternalMessageInfo

func (m *ClientPaths) GetPaths() []string { _ = "STUB: not implemented"; return nil }

// ConnectionPaths define all the connection paths for a given client state.
type ConnectionPaths struct {
	// client state unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// list of connection paths
	Paths []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (m *ConnectionPaths) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConnectionPaths) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConnectionPaths) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConnectionPaths) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConnectionPaths) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConnectionPaths) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConnectionPaths) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConnectionPaths) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConnectionPaths) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConnectionPaths proto.InternalMessageInfo

func (m *ConnectionPaths) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *ConnectionPaths) GetPaths() []string { _ = "STUB: not implemented"; return nil }

// Version defines the versioning scheme used to negotiate the IBC version in
// the connection handshake.
type Version struct {
	// unique version identifier
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// list of features compatible with the specified identifier
	Features []string `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
}

func (m *Version) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Version) String() string            { _ = "STUB: not implemented"; return "" }
func (*Version) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Version) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Version) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Version) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Version) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Version) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Version proto.InternalMessageInfo

// Params defines the set of Connection parameters.
type Params struct {
	// maximum expected time per block (in nanoseconds), used to enforce block delay. This parameter should reflect the
	// largest amount of time that the chain might reasonably take to produce the next block under normal operating
	// conditions. A safe choice is 3-5x the expected time per block.
	MaxExpectedTimePerBlock uint64 `protobuf:"varint,1,opt,name=max_expected_time_per_block,json=maxExpectedTimePerBlock,proto3" json:"max_expected_time_per_block,omitempty"`
}

func (m *Params) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Params) String() string            { _ = "STUB: not implemented"; return "" }
func (*Params) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Params) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Params) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Params) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Params) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxExpectedTimePerBlock() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterEnum("ibc.core.connection.v1.State", State_name, State_value)
	proto.RegisterType((*ConnectionEnd)(nil), "ibc.core.connection.v1.ConnectionEnd")
	proto.RegisterType((*IdentifiedConnection)(nil), "ibc.core.connection.v1.IdentifiedConnection")
	proto.RegisterType((*Counterparty)(nil), "ibc.core.connection.v1.Counterparty")
	proto.RegisterType((*ClientPaths)(nil), "ibc.core.connection.v1.ClientPaths")
	proto.RegisterType((*ConnectionPaths)(nil), "ibc.core.connection.v1.ConnectionPaths")
	proto.RegisterType((*Version)(nil), "ibc.core.connection.v1.Version")
	proto.RegisterType((*Params)(nil), "ibc.core.connection.v1.Params")
}

func init() {
	proto.RegisterFile("ibc/core/connection/v1/connection.proto", fileDescriptor_90572467c054e43a)
}

var fileDescriptor_90572467c054e43a = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6a, 0xdb, 0x4c,
	0x14, 0x95, 0x64, 0xd9, 0x71, 0xc6, 0x76, 0xbe, 0x7c, 0x43, 0x68, 0x85, 0x42, 0x65, 0x35, 0x29,
	0xd4, 0x14, 0x62, 0xd5, 0x09, 0x74, 0xd1, 0x9f, 0x45, 0xec, 0x28, 0x20, 0xda, 0xba, 0x42, 0x71,
	0x5a, 0x9a, 0x8d, 0x90, 0xa5, 0x89, 0x33, 0xc4, 0xd2, 0x08, 0x69, 0x6c, 0x9c, 0x37, 0x08, 0x59,
	0x75, 0x57, 0x5a, 0x08, 0x14, 0xba, 0xef, 0x73, 0x64, 0x99, 0x65, 0x57, 0xa5, 0x24, 0x2f, 0x52,
	0xf4, 0x13, 0x4b, 0x09, 0x8d, 0x17, 0x6d, 0x77, 0xf7, 0xe7, 0x9c, 0xa3, 0xab, 0x73, 0x2f, 0x03,
	0x1e, 0xe2, 0xbe, 0xad, 0xd8, 0x24, 0x40, 0x8a, 0x4d, 0x3c, 0x0f, 0xd9, 0x14, 0x13, 0x4f, 0x19,
	0xb7, 0x72, 0x59, 0xd3, 0x0f, 0x08, 0x25, 0xf0, 0x0e, 0xee, 0xdb, 0xcd, 0x08, 0xd8, 0xcc, 0xb5,
	0xc6, 0x2d, 0x71, 0x69, 0x40, 0x06, 0x24, 0x86, 0x28, 0x51, 0x94, 0xa0, 0xc5, 0xbc, 0xac, 0xeb,
	0x62, 0xea, 0x22, 0x8f, 0x26, 0xb2, 0x57, 0x59, 0x02, 0x5c, 0xf9, 0xc8, 0x81, 0x5a, 0x67, 0x2a,
	0xa8, 0x7a, 0x0e, 0x5c, 0x06, 0xf3, 0xf6, 0x10, 0x23, 0x8f, 0x9a, 0xd8, 0x11, 0x58, 0x99, 0x6d,
	0xcc, 0x1b, 0xe5, 0xa4, 0xa0, 0x39, 0xf0, 0x19, 0x28, 0x8f, 0x51, 0x10, 0x62, 0xe2, 0x85, 0x02,
	0x27, 0x17, 0x1a, 0x95, 0xf5, 0x7a, 0xf3, 0xf7, 0x83, 0x35, 0xdf, 0x26, 0x38, 0x63, 0x4a, 0x80,
	0x1b, 0xa0, 0x18, 0x52, 0x8b, 0x22, 0xa1, 0x20, 0xb3, 0x8d, 0x85, 0xf5, 0x7b, 0xb7, 0x31, 0x77,
	0x22, 0x90, 0x91, 0x60, 0x61, 0x17, 0x54, 0x6d, 0x32, 0xf2, 0x28, 0x0a, 0x7c, 0x2b, 0xa0, 0x47,
	0x02, 0x2f, 0xb3, 0x8d, 0xca, 0xfa, 0x83, 0xdb, 0xb8, 0x9d, 0x1c, 0xb6, 0xcd, 0x9f, 0xfd, 0xa8,
	0x33, 0xc6, 0x35, 0x3e, 0xbc, 0x0f, 0xaa, 0x0e, 0x1a, 0x5a, 0x47, 0xa6, 0x8f, 0x02, 0x4c, 0x1c,
	0xa1, 0x28, 0xb3, 0x0d, 0xde, 0xa8, 0xc4, 0x35, 0x3d, 0x2e, 0x3d, 0xe5, 0x8f, 0xbf, 0xd4, 0x99,
	0x95, 0x6f, 0x1c, 0x58, 0xd2, 0x1c, 0xe4, 0x51, 0xbc, 0x8f, 0x91, 0x93, 0x79, 0x04, 0x17, 0x00,
	0x37, 0x75, 0x86, 0xc3, 0x37, 0x0c, 0xe3, 0x66, 0x18, 0x56, 0xf8, 0x63, 0xc3, 0xf8, 0xbf, 0x30,
	0xac, 0xf8, 0x8f, 0x0d, 0x2b, 0xdd, 0x66, 0xd8, 0x67, 0x16, 0x54, 0xf3, 0x6a, 0xb3, 0x2f, 0x69,
	0x15, 0xd4, 0xb2, 0x41, 0x32, 0xe7, 0xaa, 0x59, 0x51, 0x73, 0x60, 0x1b, 0x94, 0xfc, 0x00, 0xed,
	0xe3, 0x49, 0x7c, 0x32, 0x37, 0xfe, 0x62, 0x7a, 0xc9, 0xe3, 0x56, 0xf3, 0x35, 0x0a, 0x0e, 0x87,
	0x48, 0x8f, 0xb1, 0xe9, 0x5f, 0xa4, 0xcc, 0x74, 0xb8, 0x55, 0x50, 0xe9, 0xc4, 0x9f, 0xd6, 0x2d,
	0x7a, 0x10, 0xc2, 0x25, 0x50, 0xf4, 0xa3, 0x40, 0x60, 0xe5, 0x42, 0x63, 0xde, 0x48, 0x92, 0x95,
	0x2d, 0xf0, 0x5f, 0xb6, 0xe7, 0x04, 0x38, 0xf3, 0x1f, 0xa6, 0x2a, 0x5c, 0x5e, 0xe5, 0x25, 0x98,
	0x4b, 0x57, 0x09, 0x25, 0x00, 0xf0, 0xd5, 0x09, 0x05, 0x29, 0x3d, 0x57, 0x81, 0x22, 0x28, 0xef,
	0x23, 0x8b, 0x8e, 0x02, 0x74, 0xa5, 0x31, 0xcd, 0xd3, 0xb9, 0xb7, 0x41, 0x49, 0xb7, 0x02, 0xcb,
	0x0d, 0xe1, 0x73, 0xb0, 0xec, 0x5a, 0x13, 0x13, 0x4d, 0x7c, 0x64, 0x53, 0xe4, 0x98, 0x14, 0xbb,
	0x28, 0xda, 0x89, 0xd9, 0x1f, 0x12, 0xfb, 0x30, 0x16, 0xe7, 0x8d, 0xbb, 0xae, 0x35, 0x51, 0x53,
	0x44, 0x0f, 0xbb, 0x48, 0x47, 0x41, 0x3b, 0x6a, 0x3f, 0xfa, 0xc4, 0x82, 0x62, 0x7c, 0x26, 0xf0,
	0x09, 0xa8, 0xef, 0xf4, 0x36, 0x7b, 0xaa, 0xb9, 0xdb, 0xd5, 0xba, 0x5a, 0x4f, 0xdb, 0x7c, 0xa5,
	0xed, 0xa9, 0x5b, 0xe6, 0x6e, 0x77, 0x47, 0x57, 0x3b, 0xda, 0xb6, 0xa6, 0x6e, 0x2d, 0x32, 0xe2,
	0xff, 0x27, 0xa7, 0x72, 0xed, 0x1a, 0x00, 0x0a, 0x00, 0x24, 0xbc, 0xa8, 0xb8, 0xc8, 0x8a, 0xe5,
	0x93, 0x53, 0x99, 0x8f, 0x62, 0x28, 0x81, 0x5a, 0xd2, 0xe9, 0x19, 0xef, 0xdf, 0xe8, 0x6a, 0x77,
	0x91, 0x13, 0x2b, 0x27, 0xa7, 0xf2, 0x5c, 0x9a, 0x66, 0xcc, 0xb8, 0x59, 0x48, 0x98, 0x51, 0x2c,
	0xf2, 0xc7, 0x5f, 0x25, 0xa6, 0xfd, 0xee, 0xec, 0x42, 0x62, 0xcf, 0x2f, 0x24, 0xf6, 0xe7, 0x85,
	0xc4, 0x7e, 0xb8, 0x94, 0x98, 0xf3, 0x4b, 0x89, 0xf9, 0x7e, 0x29, 0x31, 0x7b, 0x2f, 0x06, 0x98,
	0x1e, 0x8c, 0xfa, 0xd1, 0xb2, 0x15, 0x9b, 0x84, 0x2e, 0x09, 0x15, 0xdc, 0xb7, 0xd7, 0x06, 0x44,
	0x19, 0xb7, 0x5a, 0x8a, 0x4b, 0x9c, 0xd1, 0x10, 0x85, 0xc9, 0x3b, 0xf7, 0x78, 0x63, 0x2d, 0xf7,
	0x82, 0xd2, 0x23, 0x1f, 0x85, 0xfd, 0x52, 0xfc, 0xc6, 0x6d, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x33, 0x2f, 0xb7, 0x1f, 0x65, 0x05, 0x00, 0x00,
}

func (m *ConnectionEnd) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConnectionEnd) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConnectionEnd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IdentifiedConnection) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IdentifiedConnection) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IdentifiedConnection) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Counterparty) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Counterparty) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Counterparty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ClientPaths) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientPaths) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ClientPaths) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConnectionPaths) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConnectionPaths) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConnectionPaths) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Version) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Version) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Version) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintConnection(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *ConnectionEnd) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IdentifiedConnection) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Counterparty) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientPaths) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConnectionPaths) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Version) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Params) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovConnection(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozConnection(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConnectionEnd) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IdentifiedConnection) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Counterparty) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientPaths) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConnectionPaths) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Version) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Params) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipConnection(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthConnection        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConnection          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConnection = fmt.Errorf("proto: unexpected end of group")
)
