// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/connection/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgConnectionOpenInit defines the msg sent by an account on Chain A to
// initialize a connection with Chain B.
type MsgConnectionOpenInit struct {
	ClientId     string       `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Counterparty Counterparty `protobuf:"bytes,2,opt,name=counterparty,proto3" json:"counterparty"`
	Version      *Version     `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DelayPeriod  uint64       `protobuf:"varint,4,opt,name=delay_period,json=delayPeriod,proto3" json:"delay_period,omitempty"`
	Signer       string       `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgConnectionOpenInit) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenInit) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenInit) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenInit) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInit) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenInit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInit) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgConnectionOpenInit) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenInit) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenInit proto.InternalMessageInfo

// MsgConnectionOpenInitResponse defines the Msg/ConnectionOpenInit response
// type.
type MsgConnectionOpenInitResponse struct {
}

func (m *MsgConnectionOpenInitResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenInitResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenInitResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenInitResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInitResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInitResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgConnectionOpenInitResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenInitResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenInitResponse proto.InternalMessageInfo

// MsgConnectionOpenTry defines a msg sent by a Relayer to try to open a
// connection on Chain B.
type MsgConnectionOpenTry struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Deprecated: this field is unused. Crossing hellos are no longer supported in core IBC.
	PreviousConnectionId string `protobuf:"bytes,2,opt,name=previous_connection_id,json=previousConnectionId,proto3" json:"previous_connection_id,omitempty"` // Deprecated: Do not use.
	// Deprecated: this field is unused.
	ClientState          *types.Any    `protobuf:"bytes,3,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"` // Deprecated: Do not use.
	Counterparty         Counterparty  `protobuf:"bytes,4,opt,name=counterparty,proto3" json:"counterparty"`
	DelayPeriod          uint64        `protobuf:"varint,5,opt,name=delay_period,json=delayPeriod,proto3" json:"delay_period,omitempty"`
	CounterpartyVersions []*Version    `protobuf:"bytes,6,rep,name=counterparty_versions,json=counterpartyVersions,proto3" json:"counterparty_versions,omitempty"`
	ProofHeight          types1.Height `protobuf:"bytes,7,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
	// proof of the initialization the connection on Chain A: `UNINITIALIZED ->
	// INIT`
	ProofInit []byte `protobuf:"bytes,8,opt,name=proof_init,json=proofInit,proto3" json:"proof_init,omitempty"`
	// Deprecated: this field is unused.
	ProofClient []byte `protobuf:"bytes,9,opt,name=proof_client,json=proofClient,proto3" json:"proof_client,omitempty"` // Deprecated: Do not use.
	// Deprecated: this field is unused.
	ProofConsensus []byte `protobuf:"bytes,10,opt,name=proof_consensus,json=proofConsensus,proto3" json:"proof_consensus,omitempty"` // Deprecated: Do not use.
	// Deprecated: this field is unused.
	ConsensusHeight types1.Height `protobuf:"bytes,11,opt,name=consensus_height,json=consensusHeight,proto3" json:"consensus_height"` // Deprecated: Do not use.
	Signer          string        `protobuf:"bytes,12,opt,name=signer,proto3" json:"signer,omitempty"`
	// Deprecated: this field is unused.
	HostConsensusStateProof []byte `protobuf:"bytes,13,opt,name=host_consensus_state_proof,json=hostConsensusStateProof,proto3" json:"host_consensus_state_proof,omitempty"` // Deprecated: Do not use.
}

func (m *MsgConnectionOpenTry) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenTry) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenTry) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenTry) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTry) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgConnectionOpenTry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTry) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgConnectionOpenTry) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenTry) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenTry proto.InternalMessageInfo

// MsgConnectionOpenTryResponse defines the Msg/ConnectionOpenTry response type.
type MsgConnectionOpenTryResponse struct {
}

func (m *MsgConnectionOpenTryResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenTryResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenTryResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenTryResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTryResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenTryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTryResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgConnectionOpenTryResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenTryResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenTryResponse proto.InternalMessageInfo

// MsgConnectionOpenAck defines a msg sent by a Relayer to Chain A to
// acknowledge the change of connection state to TRYOPEN on Chain B.
type MsgConnectionOpenAck struct {
	ConnectionId             string   `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	CounterpartyConnectionId string   `protobuf:"bytes,2,opt,name=counterparty_connection_id,json=counterpartyConnectionId,proto3" json:"counterparty_connection_id,omitempty"`
	Version                  *Version `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Deprecated: this field is unused.
	ClientState *types.Any    `protobuf:"bytes,4,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"` // Deprecated: Do not use.
	ProofHeight types1.Height `protobuf:"bytes,5,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
	// proof of the initialization the connection on Chain B: `UNINITIALIZED ->
	// TRYOPEN`
	ProofTry []byte `protobuf:"bytes,6,opt,name=proof_try,json=proofTry,proto3" json:"proof_try,omitempty"`
	// Deprecated: this field is unused.
	ProofClient []byte `protobuf:"bytes,7,opt,name=proof_client,json=proofClient,proto3" json:"proof_client,omitempty"` // Deprecated: Do not use.
	// Deprecated: this field is unused.
	ProofConsensus []byte `protobuf:"bytes,8,opt,name=proof_consensus,json=proofConsensus,proto3" json:"proof_consensus,omitempty"` // Deprecated: Do not use.
	// Deprecated: this field is unused.
	ConsensusHeight types1.Height `protobuf:"bytes,9,opt,name=consensus_height,json=consensusHeight,proto3" json:"consensus_height"` // Deprecated: Do not use.
	Signer          string        `protobuf:"bytes,10,opt,name=signer,proto3" json:"signer,omitempty"`
	// Deprecated: this field is unused.
	HostConsensusStateProof []byte `protobuf:"bytes,11,opt,name=host_consensus_state_proof,json=hostConsensusStateProof,proto3" json:"host_consensus_state_proof,omitempty"` // Deprecated: Do not use.
}

func (m *MsgConnectionOpenAck) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenAck) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenAck) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenAck) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAck) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgConnectionOpenAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAck) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgConnectionOpenAck) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenAck) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenAck proto.InternalMessageInfo

// MsgConnectionOpenAckResponse defines the Msg/ConnectionOpenAck response type.
type MsgConnectionOpenAckResponse struct {
}

func (m *MsgConnectionOpenAckResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenAckResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenAckResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenAckResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAckResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenAckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAckResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgConnectionOpenAckResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenAckResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenAckResponse proto.InternalMessageInfo

// MsgConnectionOpenConfirm defines a msg sent by a Relayer to Chain B to
// acknowledge the change of connection state to OPEN on Chain A.
type MsgConnectionOpenConfirm struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// proof for the change of the connection state on Chain A: `INIT -> OPEN`
	ProofAck    []byte        `protobuf:"bytes,2,opt,name=proof_ack,json=proofAck,proto3" json:"proof_ack,omitempty"`
	ProofHeight types1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
	Signer      string        `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgConnectionOpenConfirm) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenConfirm) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenConfirm) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenConfirm) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirm) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenConfirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirm) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgConnectionOpenConfirm) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenConfirm) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenConfirm proto.InternalMessageInfo

// MsgConnectionOpenConfirmResponse defines the Msg/ConnectionOpenConfirm
// response type.
type MsgConnectionOpenConfirmResponse struct {
}

func (m *MsgConnectionOpenConfirmResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgConnectionOpenConfirmResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgConnectionOpenConfirmResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgConnectionOpenConfirmResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirmResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenConfirmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirmResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgConnectionOpenConfirmResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenConfirmResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgConnectionOpenConfirmResponse proto.InternalMessageInfo

// MsgUpdateParams defines the sdk.Msg type to update the connection parameters.
type MsgUpdateParams struct {
	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// params defines the connection parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpdateParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

// MsgUpdateParamsResponse defines the MsgUpdateParams response type.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgConnectionOpenInit)(nil), "ibc.core.connection.v1.MsgConnectionOpenInit")
	proto.RegisterType((*MsgConnectionOpenInitResponse)(nil), "ibc.core.connection.v1.MsgConnectionOpenInitResponse")
	proto.RegisterType((*MsgConnectionOpenTry)(nil), "ibc.core.connection.v1.MsgConnectionOpenTry")
	proto.RegisterType((*MsgConnectionOpenTryResponse)(nil), "ibc.core.connection.v1.MsgConnectionOpenTryResponse")
	proto.RegisterType((*MsgConnectionOpenAck)(nil), "ibc.core.connection.v1.MsgConnectionOpenAck")
	proto.RegisterType((*MsgConnectionOpenAckResponse)(nil), "ibc.core.connection.v1.MsgConnectionOpenAckResponse")
	proto.RegisterType((*MsgConnectionOpenConfirm)(nil), "ibc.core.connection.v1.MsgConnectionOpenConfirm")
	proto.RegisterType((*MsgConnectionOpenConfirmResponse)(nil), "ibc.core.connection.v1.MsgConnectionOpenConfirmResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "ibc.core.connection.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ibc.core.connection.v1.MsgUpdateParamsResponse")
}

func init() { proto.RegisterFile("ibc/core/connection/v1/tx.proto", fileDescriptor_5d00fde5fc97399e) }

var fileDescriptor_5d00fde5fc97399e = []byte{
	// 939 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xc7, 0xbd, 0x89, 0xed, 0xc4, 0xc7, 0x2e, 0x81, 0x91, 0x93, 0x4c, 0xb7, 0xd4, 0x36, 0x01,
	0xd4, 0xa8, 0x90, 0xdd, 0xba, 0x05, 0xa9, 0x40, 0x11, 0x4a, 0x7c, 0x43, 0x2e, 0x02, 0xd5, 0x12,
	0x40, 0xe2, 0xc6, 0xb2, 0xd7, 0x93, 0xcd, 0x28, 0xf1, 0xce, 0x6a, 0x67, 0x6d, 0x6a, 0xae, 0x10,
	0xdc, 0x20, 0x71, 0xc3, 0x23, 0xf0, 0x08, 0x7d, 0x8c, 0x8a, 0xab, 0x5e, 0x72, 0x85, 0xaa, 0x04,
	0xa9, 0x2f, 0xc0, 0x03, 0xa0, 0xf9, 0xd8, 0xf5, 0xda, 0x5e, 0xa7, 0x76, 0xdb, 0xbb, 0xdd, 0xb3,
	0xff, 0x73, 0xe6, 0xcc, 0x39, 0xbf, 0xb3, 0x33, 0x50, 0xa7, 0x5d, 0xd7, 0x76, 0x59, 0x48, 0x6c,
	0x97, 0xf9, 0x3e, 0x71, 0x23, 0xca, 0x7c, 0x7b, 0xd8, 0xb4, 0xa3, 0x47, 0x56, 0x10, 0xb2, 0x88,
	0xa1, 0x2d, 0xda, 0x75, 0x2d, 0x21, 0xb0, 0xc6, 0x02, 0x6b, 0xd8, 0x34, 0xab, 0x1e, 0xf3, 0x98,
	0x94, 0xd8, 0xe2, 0x49, 0xa9, 0xcd, 0x6d, 0x97, 0xf1, 0x3e, 0xe3, 0x76, 0x9f, 0x7b, 0x22, 0x4a,
	0x9f, 0x7b, 0xfa, 0xc3, 0x75, 0x8f, 0x31, 0xef, 0x9c, 0xd8, 0xf2, 0xad, 0x3b, 0x38, 0xb1, 0x3b,
	0xfe, 0x48, 0x7f, 0x4a, 0xa5, 0x70, 0x4e, 0x89, 0x1f, 0x09, 0x47, 0xf5, 0xa4, 0x05, 0xb7, 0xe6,
	0xe4, 0x98, 0x4a, 0x48, 0x0a, 0x77, 0x7e, 0x5f, 0x81, 0xcd, 0x23, 0xee, 0xb5, 0x12, 0xfb, 0xd7,
	0x01, 0xf1, 0x0f, 0x7d, 0x1a, 0xa1, 0x1b, 0x50, 0x52, 0x21, 0xdb, 0xb4, 0x87, 0x8d, 0x86, 0xb1,
	0x5b, 0x72, 0xd6, 0x95, 0xe1, 0xb0, 0x87, 0xbe, 0x82, 0x8a, 0xcb, 0x06, 0x7e, 0x44, 0xc2, 0xa0,
	0x13, 0x46, 0x23, 0xbc, 0xd2, 0x30, 0x76, 0xcb, 0x77, 0xdf, 0xb3, 0xb2, 0x77, 0x6e, 0xb5, 0x52,
	0xda, 0x83, 0xfc, 0x93, 0x7f, 0xea, 0x39, 0x67, 0xc2, 0x1f, 0x7d, 0x02, 0x6b, 0x43, 0x12, 0x72,
	0xca, 0x7c, 0xbc, 0x2a, 0x43, 0xd5, 0xe7, 0x85, 0xfa, 0x4e, 0xc9, 0x9c, 0x58, 0x8f, 0xde, 0x81,
	0x4a, 0x8f, 0x9c, 0x77, 0x46, 0xed, 0x80, 0x84, 0x94, 0xf5, 0x70, 0xbe, 0x61, 0xec, 0xe6, 0x9d,
	0xb2, 0xb4, 0x3d, 0x94, 0x26, 0xb4, 0x05, 0x45, 0x4e, 0x3d, 0x9f, 0x84, 0xb8, 0x20, 0xf7, 0xa1,
	0xdf, 0x3e, 0xdd, 0xf8, 0xed, 0xcf, 0x7a, 0xee, 0x97, 0xe7, 0x8f, 0x6f, 0x6b, 0xc3, 0x4e, 0x1d,
	0x6e, 0x66, 0x16, 0xc3, 0x21, 0x3c, 0x60, 0x3e, 0x27, 0x3b, 0xff, 0x16, 0xa0, 0x3a, 0xa3, 0x38,
	0x0e, 0x47, 0x57, 0x57, 0xeb, 0x3e, 0x6c, 0x05, 0x21, 0x19, 0x52, 0x36, 0xe0, 0xed, 0xf1, 0x6e,
	0x84, 0x52, 0xd4, 0xad, 0x74, 0xb0, 0x82, 0x0d, 0xa7, 0x1a, 0x2b, 0xc6, 0xb1, 0x0f, 0x7b, 0xe8,
	0x33, 0xa8, 0xe8, 0xb0, 0x3c, 0xea, 0x44, 0x44, 0x17, 0xa7, 0x6a, 0x29, 0x34, 0xac, 0x18, 0x0d,
	0x6b, 0xdf, 0x1f, 0xc9, 0x28, 0x65, 0xa5, 0xfe, 0x46, 0x88, 0x67, 0x9a, 0x94, 0x7f, 0xc5, 0x26,
	0x4d, 0x57, 0xba, 0x30, 0x5b, 0xe9, 0x63, 0xd8, 0x4c, 0xbb, 0xb4, 0x75, 0x93, 0x38, 0x2e, 0x36,
	0x56, 0x17, 0xe9, 0x6a, 0x35, 0xed, 0xad, 0x8d, 0x1c, 0xb5, 0xa0, 0x12, 0x84, 0x8c, 0x9d, 0xb4,
	0x4f, 0x09, 0xf5, 0x4e, 0x23, 0xbc, 0x26, 0x37, 0x62, 0xa6, 0x82, 0x29, 0xf6, 0x87, 0x4d, 0xeb,
	0x4b, 0xa9, 0xd0, 0xe9, 0x97, 0xa5, 0x97, 0x32, 0xa1, 0x9b, 0x00, 0x2a, 0x08, 0xf5, 0x69, 0x84,
	0xd7, 0x1b, 0xc6, 0x6e, 0xc5, 0x29, 0x49, 0x8b, 0xc4, 0xfd, 0xfd, 0x78, 0x0d, 0x15, 0x0b, 0x97,
	0x84, 0x40, 0xd5, 0x54, 0xda, 0x5b, 0xd2, 0x8c, 0x3e, 0x80, 0x0d, 0x2d, 0x13, 0x3c, 0xf8, 0x7c,
	0xc0, 0x31, 0x24, 0xca, 0x37, 0x94, 0x32, 0xfe, 0x82, 0x8e, 0xe0, 0xcd, 0x44, 0x16, 0xe7, 0x5e,
	0x7e, 0x61, 0xee, 0x45, 0x91, 0x3b, 0x36, 0x9c, 0x8d, 0xc4, 0x57, 0xef, 0x60, 0x8c, 0x71, 0x25,
	0x8d, 0x31, 0xfa, 0x02, 0xcc, 0x53, 0xc6, 0xa3, 0x71, 0x4a, 0x0a, 0x96, 0xb6, 0xcc, 0x06, 0x5f,
	0x4b, 0xd2, 0xdb, 0x16, 0xaa, 0x24, 0x3b, 0xc9, 0xc8, 0x43, 0x21, 0x99, 0x9d, 0x83, 0x1a, 0xbc,
	0x9d, 0x45, 0x79, 0x32, 0x06, 0xcf, 0xf2, 0x19, 0x63, 0xb0, 0xef, 0x9e, 0xa1, 0x77, 0xe1, 0xda,
	0x24, 0xe0, 0x6a, 0x14, 0x2a, 0x6e, 0x1a, 0xea, 0x07, 0x60, 0x4e, 0x40, 0x92, 0x31, 0x12, 0x0e,
	0x4e, 0x2b, 0x26, 0x46, 0xe2, 0x15, 0x7e, 0x15, 0xd3, 0xd3, 0x94, 0x5f, 0x66, 0x9a, 0xa6, 0x21,
	0x2c, 0xbc, 0x0c, 0x84, 0x37, 0x40, 0x21, 0xd7, 0x8e, 0xc2, 0x11, 0x2e, 0x4a, 0x06, 0xd7, 0xa5,
	0x41, 0xfc, 0x43, 0xa6, 0x11, 0x5c, 0x5b, 0x18, 0xc1, 0xf5, 0xa5, 0x10, 0x2c, 0xbd, 0x0e, 0x04,
	0x61, 0x09, 0x04, 0xcb, 0xaf, 0x09, 0xc1, 0x7d, 0xf7, 0x2c, 0x41, 0xf0, 0x2f, 0x03, 0xf0, 0x8c,
	0xa0, 0xc5, 0xfc, 0x13, 0x1a, 0xf6, 0x17, 0xc3, 0x30, 0xe9, 0x45, 0xc7, 0x3d, 0x93, 0xd4, 0xc5,
	0xbd, 0x10, 0x20, 0x4f, 0x77, 0x7b, 0xf5, 0x65, 0xba, 0x3d, 0xae, 0x56, 0xfe, 0xea, 0x73, 0x67,
	0x07, 0x1a, 0xf3, 0xf6, 0x92, 0x6c, 0xf8, 0x11, 0x6c, 0x1c, 0x71, 0xef, 0xdb, 0xa0, 0x27, 0x6a,
	0xd6, 0x09, 0x3b, 0x7d, 0x9e, 0x8a, 0x6f, 0x4c, 0x74, 0xe3, 0x01, 0x14, 0x03, 0xa9, 0xd0, 0xe7,
	0x72, 0x6d, 0xde, 0x84, 0xa8, 0x38, 0x3a, 0x75, 0xed, 0x33, 0x9b, 0xdd, 0x75, 0xd8, 0x9e, 0x5a,
	0x39, 0x4e, 0xea, 0xee, 0x7f, 0x79, 0x58, 0x3d, 0xe2, 0x1e, 0xfa, 0x09, 0x50, 0xc6, 0x15, 0x62,
	0x6f, 0xde, 0xba, 0x99, 0x87, 0xac, 0xf9, 0xf1, 0x52, 0xf2, 0x38, 0x07, 0xf4, 0x23, 0xbc, 0x35,
	0x7b, 0x1e, 0x7f, 0xb8, 0x70, 0xac, 0xe3, 0x70, 0x64, 0x7e, 0xb4, 0x8c, 0x7a, 0xfe, 0xc2, 0x02,
	0x9c, 0xc5, 0x17, 0xde, 0x77, 0xcf, 0x96, 0x58, 0x38, 0xc5, 0x3e, 0xfa, 0xd5, 0x80, 0xcd, 0x6c,
	0xf0, 0xef, 0x2c, 0x1c, 0x4f, 0x7b, 0x98, 0xf7, 0x97, 0xf5, 0x48, 0xb2, 0x08, 0x61, 0x4b, 0x31,
	0x31, 0x96, 0x69, 0x2e, 0x6f, 0x5d, 0x11, 0x33, 0x8d, 0x91, 0x69, 0x2f, 0x28, 0x8c, 0xd7, 0x34,
	0x0b, 0x3f, 0x3f, 0x7f, 0x7c, 0xdb, 0x38, 0xf8, 0xfe, 0xc9, 0x45, 0xcd, 0x78, 0x7a, 0x51, 0x33,
	0x9e, 0x5d, 0xd4, 0x8c, 0x3f, 0x2e, 0x6b, 0xb9, 0xa7, 0x97, 0xb5, 0xdc, 0xdf, 0x97, 0xb5, 0xdc,
	0x0f, 0x9f, 0x7b, 0x34, 0x3a, 0x1d, 0x74, 0x2d, 0x97, 0xf5, 0x6d, 0x7d, 0xb1, 0xa6, 0x5d, 0x77,
	0xcf, 0x63, 0xf6, 0xb0, 0xd9, 0xb4, 0xfb, 0xac, 0x37, 0x38, 0x27, 0x5c, 0xdd, 0x8c, 0xef, 0xdc,
	0xdb, 0x4b, 0x5d, 0x8e, 0xa3, 0x51, 0x40, 0x78, 0xb7, 0x28, 0xcf, 0x80, 0x7b, 0xff, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x0f, 0xfd, 0x0f, 0xfc, 0xe4, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ConnectionOpenInit defines a rpc handler method for MsgConnectionOpenInit.
	ConnectionOpenInit(ctx context.Context, in *MsgConnectionOpenInit, opts ...grpc.CallOption) (*MsgConnectionOpenInitResponse, error)
	// ConnectionOpenTry defines a rpc handler method for MsgConnectionOpenTry.
	ConnectionOpenTry(ctx context.Context, in *MsgConnectionOpenTry, opts ...grpc.CallOption) (*MsgConnectionOpenTryResponse, error)
	// ConnectionOpenAck defines a rpc handler method for MsgConnectionOpenAck.
	ConnectionOpenAck(ctx context.Context, in *MsgConnectionOpenAck, opts ...grpc.CallOption) (*MsgConnectionOpenAckResponse, error)
	// ConnectionOpenConfirm defines a rpc handler method for
	// MsgConnectionOpenConfirm.
	ConnectionOpenConfirm(ctx context.Context, in *MsgConnectionOpenConfirm, opts ...grpc.CallOption) (*MsgConnectionOpenConfirmResponse, error)
	// UpdateConnectionParams defines a rpc handler method for
	// MsgUpdateParams.
	UpdateConnectionParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient { _ = "STUB: not implemented"; return *new(MsgClient) }

func (c *msgClient) ConnectionOpenInit(ctx context.Context, in *MsgConnectionOpenInit, opts ...grpc.CallOption) (*MsgConnectionOpenInitResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) ConnectionOpenTry(ctx context.Context, in *MsgConnectionOpenTry, opts ...grpc.CallOption) (*MsgConnectionOpenTryResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) ConnectionOpenAck(ctx context.Context, in *MsgConnectionOpenAck, opts ...grpc.CallOption) (*MsgConnectionOpenAckResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) ConnectionOpenConfirm(ctx context.Context, in *MsgConnectionOpenConfirm, opts ...grpc.CallOption) (*MsgConnectionOpenConfirmResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) UpdateConnectionParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ConnectionOpenInit defines a rpc handler method for MsgConnectionOpenInit.
	ConnectionOpenInit(context.Context, *MsgConnectionOpenInit) (*MsgConnectionOpenInitResponse, error)
	// ConnectionOpenTry defines a rpc handler method for MsgConnectionOpenTry.
	ConnectionOpenTry(context.Context, *MsgConnectionOpenTry) (*MsgConnectionOpenTryResponse, error)
	// ConnectionOpenAck defines a rpc handler method for MsgConnectionOpenAck.
	ConnectionOpenAck(context.Context, *MsgConnectionOpenAck) (*MsgConnectionOpenAckResponse, error)
	// ConnectionOpenConfirm defines a rpc handler method for
	// MsgConnectionOpenConfirm.
	ConnectionOpenConfirm(context.Context, *MsgConnectionOpenConfirm) (*MsgConnectionOpenConfirmResponse, error)
	// UpdateConnectionParams defines a rpc handler method for
	// MsgUpdateParams.
	UpdateConnectionParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConnectionOpenInit(ctx context.Context, req *MsgConnectionOpenInit) (*MsgConnectionOpenInitResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) ConnectionOpenTry(ctx context.Context, req *MsgConnectionOpenTry) (*MsgConnectionOpenTryResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) ConnectionOpenAck(ctx context.Context, req *MsgConnectionOpenAck) (*MsgConnectionOpenAckResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) ConnectionOpenConfirm(ctx context.Context, req *MsgConnectionOpenConfirm) (*MsgConnectionOpenConfirmResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) UpdateConnectionParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) { _ = "STUB: not implemented"; return }

func _Msg_ConnectionOpenInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_ConnectionOpenTry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_ConnectionOpenAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_ConnectionOpenConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_UpdateConnectionParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.core.connection.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectionOpenInit",
			Handler:    _Msg_ConnectionOpenInit_Handler,
		},
		{
			MethodName: "ConnectionOpenTry",
			Handler:    _Msg_ConnectionOpenTry_Handler,
		},
		{
			MethodName: "ConnectionOpenAck",
			Handler:    _Msg_ConnectionOpenAck_Handler,
		},
		{
			MethodName: "ConnectionOpenConfirm",
			Handler:    _Msg_ConnectionOpenConfirm_Handler,
		},
		{
			MethodName: "UpdateConnectionParams",
			Handler:    _Msg_UpdateConnectionParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/core/connection/v1/tx.proto",
}

func (m *MsgConnectionOpenInit) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInit) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenInit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenInitResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenInitResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenInitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenTry) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTry) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenTry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenTryResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenTryResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenTryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenAck) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAck) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenAckResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenAckResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenAckResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenConfirm) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirm) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenConfirm) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenConfirmResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgConnectionOpenConfirmResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgConnectionOpenConfirmResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenInit) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenInitResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenTry) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenTryResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenAck) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenAckResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenConfirm) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenConfirmResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgConnectionOpenInit) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgConnectionOpenInitResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenTry) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgConnectionOpenTryResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenAck) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgConnectionOpenAckResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenConfirm) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgConnectionOpenConfirmResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipTx(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
