// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_accounts/controller/v1/controller.proto

package types

import (
	fmt "fmt"
	math "math"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of on-chain interchain accounts parameters.
// The following parameters may be used to disable the controller submodule.
type Params struct {
	// controller_enabled enables or disables the controller submodule.
	ControllerEnabled bool `protobuf:"varint,1,opt,name=controller_enabled,json=controllerEnabled,proto3" json:"controller_enabled,omitempty"`
}

func (m *Params) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Params) String() string            { _ = "STUB: not implemented"; return "" }
func (*Params) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Params) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Params) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Params) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Params) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetControllerEnabled() bool { _ = "STUB: not implemented"; return false }

func init() {
	proto.RegisterType((*Params)(nil), "ibc.applications.interchain_accounts.controller.v1.Params")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_accounts/controller/v1/controller.proto", fileDescriptor_177fd0fec5eb3400)
}

var fileDescriptor_177fd0fec5eb3400 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe3, 0xa5, 0x42, 0xd9, 0xc8, 0xc4, 0x64, 0x21, 0x26, 0x96, 0xf8, 0x94, 0x32, 0x74,
	0x07, 0xb1, 0x03, 0x23, 0x4b, 0x65, 0x5f, 0xad, 0xf6, 0x84, 0xe3, 0x8b, 0x7c, 0x4e, 0x24, 0xde,
	0x82, 0xc7, 0x62, 0xec, 0xc8, 0x88, 0x92, 0x17, 0x41, 0xc0, 0x90, 0x0c, 0x19, 0x4f, 0x9f, 0xee,
	0xd3, 0xff, 0x95, 0x0f, 0xe4, 0x10, 0x6c, 0xd7, 0x05, 0x42, 0x9b, 0x89, 0xa3, 0x00, 0xc5, 0xec,
	0x13, 0x9e, 0x2c, 0xc5, 0xbd, 0x45, 0xe4, 0x3e, 0x66, 0x01, 0xe4, 0x98, 0x13, 0x87, 0xe0, 0x13,
	0x0c, 0xcd, 0xe2, 0x32, 0x5d, 0xe2, 0xcc, 0xd5, 0x96, 0x1c, 0x9a, 0xa5, 0xc4, 0xac, 0x48, 0xcc,
	0xe2, 0x6d, 0x68, 0x6e, 0x76, 0xe5, 0xe6, 0xc9, 0x26, 0xdb, 0x4a, 0x55, 0x97, 0xd5, 0x8c, 0xf6,
	0x3e, 0x5a, 0x17, 0xfc, 0xe1, 0x4a, 0x5d, 0xab, 0xdb, 0x8b, 0x97, 0xcb, 0x99, 0x3c, 0xfe, 0x83,
	0xfb, 0xb7, 0xcf, 0x51, 0xab, 0xf3, 0xa8, 0xd5, 0xf7, 0xa8, 0xd5, 0xc7, 0xa4, 0x8b, 0xf3, 0xa4,
	0x8b, 0xaf, 0x49, 0x17, 0xaf, 0xcf, 0x47, 0xca, 0xa7, 0xde, 0x19, 0xe4, 0x16, 0x90, 0xa5, 0x65,
	0x01, 0x72, 0x58, 0x1f, 0x19, 0x86, 0xa6, 0x81, 0x96, 0x0f, 0x7d, 0xf0, 0xf2, 0x1b, 0x2b, 0xb0,
	0xdd, 0xd5, 0xf3, 0xc4, 0x7a, 0xad, 0x33, 0xbf, 0x77, 0x5e, 0xdc, 0xe6, 0x2f, 0xf0, 0xee, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x18, 0xdd, 0xe1, 0x90, 0x27, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Params) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintController(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Params) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovController(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozController(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Params) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipController(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthController        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowController          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupController = fmt.Errorf("proto: unexpected end of group")
)
