// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_accounts/controller/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types1 "github.com/cosmos/ibc-go/v11/modules/apps/27-interchain-accounts/types"
	types "github.com/cosmos/ibc-go/v11/modules/core/04-channel/types"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRegisterInterchainAccount defines the payload for Msg/RegisterAccount
type MsgRegisterInterchainAccount struct {
	Owner        string      `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ConnectionId string      `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Version      string      `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Ordering     types.Order `protobuf:"varint,4,opt,name=ordering,proto3,enum=ibc.core.channel.v1.Order" json:"ordering,omitempty"`
}

func (m *MsgRegisterInterchainAccount) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgRegisterInterchainAccount) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgRegisterInterchainAccount) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgRegisterInterchainAccount) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccount) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgRegisterInterchainAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccount) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgRegisterInterchainAccount) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgRegisterInterchainAccount) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgRegisterInterchainAccount proto.InternalMessageInfo

// MsgRegisterInterchainAccountResponse defines the response for Msg/RegisterAccount
type MsgRegisterInterchainAccountResponse struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PortId    string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
}

func (m *MsgRegisterInterchainAccountResponse) Reset() { _ = "STUB: not implemented"; return }
func (m *MsgRegisterInterchainAccountResponse) String() string {
	_ = "STUB: not implemented"
	return ""
}
func (*MsgRegisterInterchainAccountResponse) ProtoMessage() { _ = "STUB: not implemented"; return }
func (*MsgRegisterInterchainAccountResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccountResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgRegisterInterchainAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccountResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgRegisterInterchainAccountResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgRegisterInterchainAccountResponse) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_MsgRegisterInterchainAccountResponse proto.InternalMessageInfo

// MsgSendTx defines the payload for Msg/SendTx
type MsgSendTx struct {
	Owner        string                             `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	ConnectionId string                             `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	PacketData   types1.InterchainAccountPacketData `protobuf:"bytes,3,opt,name=packet_data,json=packetData,proto3" json:"packet_data"`
	// Relative timeout timestamp provided will be added to the current block time during transaction execution.
	// The timeout timestamp must be non-zero.
	RelativeTimeout uint64 `protobuf:"varint,4,opt,name=relative_timeout,json=relativeTimeout,proto3" json:"relative_timeout,omitempty"`
}

func (m *MsgSendTx) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgSendTx) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgSendTx) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgSendTx) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgSendTx) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgSendTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgSendTx) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgSendTx) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgSendTx) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgSendTx proto.InternalMessageInfo

// MsgSendTxResponse defines the response for MsgSendTx
type MsgSendTxResponse struct {
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *MsgSendTxResponse) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgSendTxResponse) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgSendTxResponse) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgSendTxResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgSendTxResponse) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgSendTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgSendTxResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgSendTxResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgSendTxResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgSendTxResponse proto.InternalMessageInfo

// MsgUpdateParams defines the payload for Msg/UpdateParams
type MsgUpdateParams struct {
	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// params defines the 27-interchain-accounts/controller parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpdateParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

// MsgUpdateParamsResponse defines the response for Msg/UpdateParams
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterInterchainAccount)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccount")
	proto.RegisterType((*MsgRegisterInterchainAccountResponse)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgRegisterInterchainAccountResponse")
	proto.RegisterType((*MsgSendTx)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgSendTx")
	proto.RegisterType((*MsgSendTxResponse)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgSendTxResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ibc.applications.interchain_accounts.controller.v1.MsgUpdateParamsResponse")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_accounts/controller/v1/tx.proto", fileDescriptor_7def041328c84a30)
}

var fileDescriptor_7def041328c84a30 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x4e, 0x14, 0x4b,
	0x18, 0x9d, 0xbe, 0x0c, 0x03, 0x14, 0x5c, 0xb8, 0xb7, 0x43, 0x2e, 0x43, 0xe7, 0x3a, 0xe0, 0xe8,
	0x02, 0x49, 0xa8, 0x4a, 0x8f, 0x7f, 0xc9, 0x18, 0x17, 0x02, 0x2e, 0x26, 0x66, 0x22, 0xb6, 0x98,
	0x10, 0x37, 0x93, 0x9a, 0xea, 0x4a, 0x51, 0x61, 0xba, 0xaa, 0xad, 0xaa, 0x69, 0x71, 0x67, 0x5c,
	0x19, 0x17, 0xc6, 0x85, 0x0f, 0xc0, 0x23, 0xb0, 0xf7, 0x01, 0x64, 0xc9, 0xd2, 0x95, 0x31, 0xb0,
	0x60, 0xe7, 0x33, 0x98, 0xfe, 0x99, 0x1e, 0x14, 0x24, 0x38, 0xb0, 0xeb, 0xef, 0xab, 0x3a, 0xe7,
	0x3b, 0xe7, 0x54, 0x75, 0x81, 0x7b, 0xbc, 0x4d, 0x10, 0x0e, 0xc3, 0x0e, 0x27, 0xd8, 0x70, 0x29,
	0x34, 0xe2, 0xc2, 0x50, 0x45, 0x36, 0x31, 0x17, 0x2d, 0x4c, 0x88, 0xec, 0x0a, 0xa3, 0x11, 0x91,
	0xc2, 0x28, 0xd9, 0xe9, 0x50, 0x85, 0x22, 0x17, 0x99, 0x6d, 0x18, 0x2a, 0x69, 0xa4, 0x5d, 0xe3,
	0x6d, 0x02, 0x8f, 0x83, 0xe1, 0x29, 0x60, 0xd8, 0x07, 0xc3, 0xc8, 0x75, 0xa6, 0x99, 0x64, 0x32,
	0x81, 0xa3, 0xf8, 0x2b, 0x65, 0x72, 0x6e, 0x9d, 0x4b, 0x46, 0xe4, 0xa2, 0x10, 0x93, 0x2d, 0x6a,
	0x32, 0xd4, 0xca, 0x00, 0xe2, 0x8f, 0xa9, 0x49, 0x49, 0x66, 0x88, 0xd4, 0x81, 0xd4, 0x28, 0xd0,
	0x2c, 0x5e, 0x0f, 0x34, 0xcb, 0x16, 0xae, 0xc6, 0xec, 0x44, 0x2a, 0x8a, 0xc8, 0x26, 0x16, 0x82,
	0x76, 0x12, 0x78, 0xfa, 0x99, 0x6e, 0xa9, 0x7e, 0xb2, 0xc0, 0xff, 0x4d, 0xcd, 0x3c, 0xca, 0xb8,
	0x36, 0x54, 0x35, 0xf2, 0xe9, 0x0f, 0xd2, 0xe1, 0xf6, 0x34, 0x18, 0x96, 0x2f, 0x05, 0x55, 0x65,
	0x6b, 0xde, 0x5a, 0x18, 0xf3, 0xd2, 0xc2, 0xbe, 0x06, 0xfe, 0x26, 0x52, 0x08, 0x4a, 0x62, 0xd1,
	0x2d, 0xee, 0x97, 0xff, 0x4a, 0x56, 0x27, 0xfa, 0xcd, 0x86, 0x6f, 0x97, 0xc1, 0x48, 0x44, 0x95,
	0xe6, 0x52, 0x94, 0x87, 0x92, 0xe5, 0x5e, 0x69, 0xdf, 0x01, 0xa3, 0x52, 0xf9, 0x54, 0x71, 0xc1,
	0xca, 0xc5, 0x79, 0x6b, 0x61, 0xb2, 0xe6, 0xc0, 0xf8, 0x24, 0x62, 0xad, 0xb0, 0x27, 0x30, 0x72,
	0xe1, 0xe3, 0x78, 0x93, 0x97, 0xef, 0xad, 0x4f, 0xbe, 0xdd, 0x99, 0x2b, 0xbc, 0x39, 0xda, 0x5d,
	0x4c, 0x65, 0x54, 0x7d, 0x70, 0xfd, 0x2c, 0xf1, 0x1e, 0xd5, 0xa1, 0x14, 0x9a, 0xda, 0x57, 0x00,
	0xc8, 0x58, 0x63, 0xad, 0xa9, 0x93, 0xb1, 0xac, 0xd3, 0xf0, 0xed, 0x19, 0x30, 0x12, 0x4a, 0x65,
	0xfa, 0x3e, 0x4a, 0x71, 0xd9, 0xf0, 0xeb, 0xc5, 0x78, 0x5e, 0xf5, 0xbb, 0x05, 0xc6, 0x9a, 0x9a,
	0x3d, 0xa5, 0xc2, 0x5f, 0xdf, 0xbe, 0x48, 0x20, 0x5b, 0x60, 0x3c, 0x3d, 0xfd, 0x96, 0x8f, 0x0d,
	0x4e, 0x42, 0x19, 0xaf, 0xad, 0xc2, 0x73, 0xdd, 0xc1, 0xc8, 0x85, 0x27, 0xfc, 0xad, 0x25, 0x64,
	0xab, 0xd8, 0xe0, 0xe5, 0xe2, 0xde, 0xd7, 0xb9, 0x82, 0x07, 0xc2, 0xbc, 0x63, 0xdf, 0x00, 0xff,
	0x28, 0xda, 0xc1, 0x86, 0x47, 0xb4, 0x65, 0x78, 0x40, 0x65, 0xd7, 0x24, 0x59, 0x17, 0xbd, 0xa9,
	0x5e, 0x7f, 0x3d, 0x6d, 0x9f, 0x88, 0xf5, 0x36, 0xf8, 0x37, 0xf7, 0x9b, 0x67, 0xe8, 0x80, 0x51,
	0x4d, 0x5f, 0x74, 0xa9, 0x20, 0x34, 0xb1, 0x5e, 0xf4, 0xf2, 0x3a, 0xcb, 0xe9, 0xa3, 0x05, 0xa6,
	0x9a, 0x9a, 0x3d, 0x0b, 0x7d, 0x6c, 0xe8, 0x1a, 0x56, 0x38, 0xd0, 0xf6, 0x7f, 0xa0, 0xa4, 0x39,
	0xeb, 0xc7, 0x95, 0x55, 0xf6, 0x06, 0x28, 0x85, 0xc9, 0x8e, 0x24, 0xa8, 0xf1, 0x5a, 0x1d, 0xfe,
	0xf9, 0x9f, 0x08, 0xd3, 0x19, 0x99, 0xf7, 0x8c, 0xaf, 0x3e, 0xd5, 0x33, 0x93, 0x8d, 0xaa, 0xce,
	0x82, 0x99, 0x5f, 0x54, 0xf5, 0x3c, 0xd5, 0xde, 0x15, 0xc1, 0x50, 0x53, 0x33, 0xfb, 0xb3, 0x05,
	0x66, 0x7f, 0xff, 0x0b, 0xac, 0x0d, 0xa2, 0xed, 0xac, 0x7b, 0xe9, 0x6c, 0x5c, 0x36, 0x63, 0x7e,
	0x4a, 0xef, 0x2d, 0x50, 0xca, 0x2e, 0xea, 0xfd, 0x01, 0x87, 0xa4, 0x70, 0xe7, 0xe1, 0x85, 0xe0,
	0xb9, 0xa0, 0x1d, 0x0b, 0x4c, 0xfc, 0x74, 0x23, 0x56, 0x06, 0xe4, 0x3d, 0x4e, 0xe2, 0x3c, 0xba,
	0x04, 0x92, 0x9e, 0x44, 0x67, 0xf8, 0xf5, 0xd1, 0xee, 0xa2, 0xb5, 0xbc, 0xb5, 0x77, 0x50, 0xb1,
	0xf6, 0x0f, 0x2a, 0xd6, 0xb7, 0x83, 0x8a, 0xf5, 0xe1, 0xb0, 0x52, 0xd8, 0x3f, 0xac, 0x14, 0xbe,
	0x1c, 0x56, 0x0a, 0xcf, 0x9f, 0x30, 0x6e, 0x36, 0xbb, 0x6d, 0x48, 0x64, 0x80, 0xb2, 0xb7, 0x96,
	0xb7, 0xc9, 0x12, 0x93, 0x28, 0x72, 0x5d, 0x14, 0x48, 0xbf, 0xdb, 0xa1, 0x3a, 0x7e, 0xc6, 0x35,
	0xaa, 0xdd, 0x5d, 0xea, 0x0b, 0x59, 0x3a, 0xed, 0x05, 0x37, 0xaf, 0x42, 0xaa, 0xdb, 0xa5, 0xe4,
	0xf9, 0xbd, 0xf9, 0x23, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xe7, 0x58, 0xf9, 0xbe, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterInterchainAccount defines a rpc handler for MsgRegisterInterchainAccount.
	RegisterInterchainAccount(ctx context.Context, in *MsgRegisterInterchainAccount, opts ...grpc.CallOption) (*MsgRegisterInterchainAccountResponse, error)
	// SendTx defines a rpc handler for MsgSendTx.
	SendTx(ctx context.Context, in *MsgSendTx, opts ...grpc.CallOption) (*MsgSendTxResponse, error)
	// UpdateParams defines a rpc handler for MsgUpdateParams.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient { _ = "STUB: not implemented"; return *new(MsgClient) }

func (c *msgClient) RegisterInterchainAccount(ctx context.Context, in *MsgRegisterInterchainAccount, opts ...grpc.CallOption) (*MsgRegisterInterchainAccountResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) SendTx(ctx context.Context, in *MsgSendTx, opts ...grpc.CallOption) (*MsgSendTxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterInterchainAccount defines a rpc handler for MsgRegisterInterchainAccount.
	RegisterInterchainAccount(context.Context, *MsgRegisterInterchainAccount) (*MsgRegisterInterchainAccountResponse, error)
	// SendTx defines a rpc handler for MsgSendTx.
	SendTx(context.Context, *MsgSendTx) (*MsgSendTxResponse, error)
	// UpdateParams defines a rpc handler for MsgUpdateParams.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterInterchainAccount(ctx context.Context, req *MsgRegisterInterchainAccount) (*MsgRegisterInterchainAccountResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) SendTx(ctx context.Context, req *MsgSendTx) (*MsgSendTxResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) { _ = "STUB: not implemented"; return }

func _Msg_RegisterInterchainAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_SendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.applications.interchain_accounts.controller.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterInterchainAccount",
			Handler:    _Msg_RegisterInterchainAccount_Handler,
		},
		{
			MethodName: "SendTx",
			Handler:    _Msg_SendTx_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/applications/interchain_accounts/controller/v1/tx.proto",
}

func (m *MsgRegisterInterchainAccount) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccount) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRegisterInterchainAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRegisterInterchainAccountResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRegisterInterchainAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRegisterInterchainAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgSendTx) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgSendTx) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *MsgSendTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgSendTxResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgSendTxResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgSendTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *MsgRegisterInterchainAccount) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgRegisterInterchainAccountResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgSendTx) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgSendTxResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgRegisterInterchainAccount) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgRegisterInterchainAccountResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgSendTx) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgSendTxResponse) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipTx(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
