// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/transfer/v1/authz.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Allocation defines the spend limit for a particular port and channel
type Allocation struct {
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,2,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	// spend limitation on the channel
	SpendLimit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=spend_limit,json=spendLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"spend_limit"`
	// allow list of receivers, an empty allow list permits any receiver address
	AllowList []string `protobuf:"bytes,4,rep,name=allow_list,json=allowList,proto3" json:"allow_list,omitempty"`
	// allow list of memo strings, an empty list prohibits all memo strings;
	// a list only with "*" permits any memo string
	AllowedPacketData []string `protobuf:"bytes,5,rep,name=allowed_packet_data,json=allowedPacketData,proto3" json:"allowed_packet_data,omitempty"`
}

func (m *Allocation) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Allocation) String() string            { _ = "STUB: not implemented"; return "" }
func (*Allocation) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Allocation) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Allocation) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Allocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Allocation) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Allocation) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Allocation) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Allocation proto.InternalMessageInfo

func (m *Allocation) GetSourcePort() string { _ = "STUB: not implemented"; return "" }

func (m *Allocation) GetSourceChannel() string { _ = "STUB: not implemented"; return "" }

func (m *Allocation) GetSpendLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	_ = "STUB: not implemented"
	return *new(github_com_cosmos_cosmos_sdk_types.Coins)
}

func (m *Allocation) GetAllowList() []string { _ = "STUB: not implemented"; return nil }

func (m *Allocation) GetAllowedPacketData() []string { _ = "STUB: not implemented"; return nil }

// TransferAuthorization allows the grantee to spend up to spend_limit coins from
// the granter's account for ibc transfer on a specific channel
type TransferAuthorization struct {
	// port and channel amounts
	Allocations []Allocation `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations"`
}

func (m *TransferAuthorization) Reset()         { _ = "STUB: not implemented"; return }
func (m *TransferAuthorization) String() string { _ = "STUB: not implemented"; return "" }
func (*TransferAuthorization) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*TransferAuthorization) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferAuthorization) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *TransferAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferAuthorization) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TransferAuthorization) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TransferAuthorization) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TransferAuthorization proto.InternalMessageInfo

func (m *TransferAuthorization) GetAllocations() []Allocation {
	_ = "STUB: not implemented"
	return nil
}

func init() {
	proto.RegisterType((*Allocation)(nil), "ibc.applications.transfer.v1.Allocation")
	proto.RegisterType((*TransferAuthorization)(nil), "ibc.applications.transfer.v1.TransferAuthorization")
}

func init() {
	proto.RegisterFile("ibc/applications/transfer/v1/authz.proto", fileDescriptor_b1a28b55d17325aa)
}

var fileDescriptor_b1a28b55d17325aa = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0x75, 0x20, 0xd5, 0x15, 0x48, 0x04, 0x90, 0xb2, 0x09, 0xd2, 0xaa, 0x12, 0x28,
	0x97, 0xda, 0x04, 0x2e, 0x88, 0xdb, 0x3a, 0x8e, 0x3b, 0x54, 0x11, 0x27, 0x2e, 0x91, 0xe3, 0x98,
	0xd6, 0x9a, 0x9b, 0x37, 0x8a, 0xdf, 0x04, 0xb1, 0x4f, 0xc1, 0xbe, 0x06, 0x67, 0x3e, 0xc4, 0xc4,
	0x69, 0x47, 0x4e, 0x80, 0xda, 0x2f, 0x82, 0x62, 0x7b, 0x50, 0x84, 0xb4, 0x53, 0xe2, 0xe7, 0x7d,
	0xfc, 0xfe, 0xf9, 0xf9, 0x25, 0x89, 0x2a, 0x04, 0xe3, 0x75, 0xad, 0x95, 0xe0, 0xa8, 0xa0, 0x32,
	0x0c, 0x1b, 0x5e, 0x99, 0x0f, 0xb2, 0x61, 0x5d, 0xca, 0x78, 0x8b, 0xeb, 0x0b, 0x5a, 0x37, 0x80,
	0x10, 0x3e, 0x51, 0x85, 0xa0, 0xfb, 0x4e, 0x7a, 0xe3, 0xa4, 0x5d, 0x7a, 0x7c, 0x24, 0xc0, 0x6c,
	0xc0, 0xe4, 0xd6, 0xcb, 0xdc, 0xc1, 0x5d, 0x3c, 0x7e, 0xb4, 0x82, 0x15, 0x38, 0xbd, 0xff, 0xf3,
	0x6a, 0xec, 0x3c, 0xac, 0xe0, 0x46, 0xb2, 0x2e, 0x2d, 0x24, 0xf2, 0x94, 0x09, 0x50, 0x95, 0x8b,
	0xcf, 0x2e, 0x0f, 0x08, 0x39, 0xd1, 0x1a, 0x5c, 0xb1, 0x70, 0x42, 0xc6, 0x06, 0xda, 0x46, 0xc8,
	0xbc, 0x86, 0x06, 0xa3, 0x60, 0x1a, 0x24, 0xa3, 0x8c, 0x38, 0x69, 0x09, 0x0d, 0x86, 0xcf, 0xc8,
	0x7d, 0x6f, 0x10, 0x6b, 0x5e, 0x55, 0x52, 0x47, 0x07, 0xd6, 0x73, 0xcf, 0xa9, 0xa7, 0x4e, 0x0c,
	0x35, 0x19, 0x9b, 0x5a, 0x56, 0x65, 0xae, 0xd5, 0x46, 0x61, 0x34, 0x9c, 0x0e, 0x93, 0xf1, 0xcb,
	0x23, 0xea, 0x1b, 0xee, 0x9b, 0xa1, 0xbe, 0x19, 0x7a, 0x0a, 0xaa, 0x5a, 0xbc, 0xb8, 0xfa, 0x31,
	0x19, 0x7c, 0xf9, 0x39, 0x49, 0x56, 0x0a, 0xd7, 0x6d, 0x41, 0x05, 0x6c, 0xfc, 0x74, 0xfe, 0x33,
	0x37, 0xe5, 0x39, 0xc3, 0x4f, 0xb5, 0x34, 0xf6, 0x82, 0xc9, 0x88, 0xcd, 0x7f, 0xd6, 0xa7, 0x0f,
	0x9f, 0x12, 0xc2, 0xb5, 0x86, 0x8f, 0xb9, 0x56, 0x06, 0xa3, 0xc3, 0xe9, 0x30, 0x19, 0x65, 0x23,
	0xab, 0x9c, 0x29, 0x83, 0x21, 0x25, 0x0f, 0xed, 0x41, 0x96, 0x79, 0xcd, 0xc5, 0xb9, 0xc4, 0xbc,
	0xe4, 0xc8, 0xa3, 0x3b, 0xd6, 0xf7, 0xc0, 0x87, 0x96, 0x36, 0xf2, 0x96, 0x23, 0x9f, 0x5d, 0x06,
	0xe4, 0xf1, 0x3b, 0x0f, 0xfd, 0xa4, 0xc5, 0x35, 0x34, 0xea, 0xc2, 0xe1, 0x59, 0x92, 0x31, 0xff,
	0x03, 0xcb, 0x44, 0x81, 0x1d, 0x2b, 0xa1, 0xb7, 0x3d, 0x19, 0xfd, 0x4b, 0x77, 0x71, 0xd8, 0x4f,
	0x99, 0xed, 0xa7, 0x78, 0xf3, 0xfc, 0xdb, 0xd7, 0xf9, 0xcc, 0x63, 0x71, 0x6b, 0x70, 0xc3, 0xe5,
	0x9f, 0xca, 0x8b, 0xec, 0x6a, 0x1b, 0x07, 0xd7, 0xdb, 0x38, 0xf8, 0xb5, 0x8d, 0x83, 0xcf, 0xbb,
	0x78, 0x70, 0xbd, 0x8b, 0x07, 0xdf, 0x77, 0xf1, 0xe0, 0xfd, 0xeb, 0xff, 0x91, 0xa9, 0x42, 0xcc,
	0x57, 0xc0, 0xba, 0x34, 0x65, 0x1b, 0x28, 0x5b, 0x2d, 0x4d, 0xbf, 0x7b, 0x7b, 0x3b, 0x67, 0x41,
	0x16, 0x77, 0xed, 0x0a, 0xbc, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x60, 0xff, 0xa8, 0x9d,
	0x02, 0x00, 0x00,
}

func (m *Allocation) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Allocation) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Allocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferAuthorization) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TransferAuthorization) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TransferAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintAuthz(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Allocation) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TransferAuthorization) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovAuthz(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozAuthz(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Allocation) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TransferAuthorization) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipAuthz(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthAuthz        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthz          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthz = fmt.Errorf("proto: unexpected end of group")
)
