// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/attestations/v1/attestations.proto

package attestations

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientState defines an attestor-based light client that tracks the current
// consensus state and if the client is frozen.
type ClientState struct {
	// trusted attestor set (EOA addresses)
	AttestorAddresses []string `protobuf:"bytes,1,rep,name=attestor_addresses,json=attestorAddresses,proto3" json:"attestor_addresses,omitempty"`
	// quorum threshold (minimum number of unique attestor signatures required)
	MinRequiredSigs uint32 `protobuf:"varint,2,opt,name=min_required_sigs,json=minRequiredSigs,proto3" json:"min_required_sigs,omitempty"`
	// highest height that has been trusted
	LatestHeight uint64 `protobuf:"varint,3,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	// when true, all verification and updates MUST fail
	IsFrozen bool `protobuf:"varint,4,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
}

func (m *ClientState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// ConsensusState defines an attestor consensus state. The timestamp of a
// consensus state is stored per height.
type ConsensusState struct {
	// trusted UNIX timestamp (nanoseconds) for the height
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *ConsensusState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConsensusState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConsensusState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConsensusState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConsensusState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// AttestationProof is used for client updates and membership verification.
// All attestor signatures cover sha256(attestationData).
type AttestationProof struct {
	// the attestation data that was signed (ABI-encoded StateAttestation or PacketAttestation)
	AttestationData []byte `protobuf:"bytes,1,opt,name=attestation_data,json=attestationData,proto3" json:"attestation_data,omitempty"`
	// array of 65-byte ECDSA signatures (r||s||v)
	Signatures [][]byte `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
}

func (m *AttestationProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AttestationProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*AttestationProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AttestationProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AttestationProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AttestationProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AttestationProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AttestationProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AttestationProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AttestationProof proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.attestations.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.attestations.v1.ConsensusState")
	proto.RegisterType((*AttestationProof)(nil), "ibc.lightclients.attestations.v1.AttestationProof")
}

func init() {
	proto.RegisterFile("ibc/lightclients/attestations/v1/attestations.proto", fileDescriptor_4c60154e5a577f40)
}

var fileDescriptor_4c60154e5a577f40 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0x86, 0xbd, 0x24, 0x42, 0x97, 0x25, 0xc7, 0xdd, 0xad, 0x28, 0x2c, 0x40, 0xc6, 0x3a, 0x1a,
	0x83, 0x14, 0xaf, 0xac, 0xa3, 0x82, 0xea, 0x38, 0x84, 0x28, 0x28, 0x90, 0xd3, 0xd1, 0x58, 0x6b,
	0x7b, 0xb3, 0x19, 0xc9, 0xde, 0x0d, 0x3b, 0xeb, 0x14, 0x3c, 0x01, 0x25, 0x8f, 0xc0, 0x23, 0xf0,
	0x18, 0x94, 0x29, 0x29, 0x51, 0xf2, 0x22, 0xc8, 0x76, 0xa2, 0x38, 0xd2, 0x75, 0x3b, 0xff, 0xcc,
	0x37, 0x3b, 0x33, 0x3f, 0xbd, 0x81, 0xbc, 0xe0, 0x15, 0xa8, 0xa5, 0x2b, 0x2a, 0x90, 0xda, 0x21,
	0x17, 0xce, 0x49, 0x74, 0xc2, 0x81, 0xd1, 0xc8, 0xd7, 0xc9, 0x49, 0x1c, 0xaf, 0xac, 0x71, 0x86,
	0x85, 0x90, 0x17, 0xf1, 0x10, 0x8a, 0x4f, 0x8a, 0xd6, 0xc9, 0xd3, 0x27, 0xca, 0x28, 0xd3, 0x15,
	0xf3, 0xf6, 0xd5, 0x73, 0xd7, 0xbf, 0x09, 0x7d, 0x74, 0xd7, 0x11, 0x73, 0x27, 0x9c, 0x64, 0x33,
	0xca, 0x7a, 0xd0, 0xd8, 0x4c, 0x94, 0xa5, 0x95, 0x88, 0x12, 0x7d, 0x12, 0x8e, 0xa2, 0x49, 0x7a,
	0x75, 0xc8, 0xdc, 0x1e, 0x12, 0xec, 0x35, 0xbd, 0xaa, 0x41, 0x67, 0x56, 0x7e, 0x6b, 0xc0, 0xca,
	0x32, 0x43, 0x50, 0xe8, 0x3f, 0x08, 0x49, 0x74, 0x9e, 0x5e, 0xd4, 0xa0, 0xd3, 0xbd, 0x3e, 0x07,
	0x85, 0xec, 0x25, 0x3d, 0xaf, 0x44, 0xdb, 0x20, 0x5b, 0xca, 0x76, 0x50, 0x7f, 0x14, 0x92, 0x68,
	0x9c, 0x4e, 0x7b, 0xf1, 0x53, 0xa7, 0xb1, 0x67, 0x74, 0x02, 0x98, 0x2d, 0xac, 0xf9, 0x2e, 0xb5,
	0x3f, 0x0e, 0x49, 0x74, 0x96, 0x9e, 0x01, 0x7e, 0xec, 0xe2, 0xb7, 0xe3, 0x1f, 0xbf, 0x5e, 0x78,
	0xd7, 0x6f, 0xe8, 0xe3, 0x3b, 0xa3, 0x51, 0x6a, 0x6c, 0xb0, 0x1f, 0xfa, 0x39, 0x9d, 0x38, 0xa8,
	0xdb, 0x6d, 0xeb, 0x95, 0x4f, 0xba, 0xae, 0x47, 0x61, 0x4f, 0x15, 0xf4, 0xf2, 0xf6, 0x78, 0x91,
	0x2f, 0xd6, 0x98, 0x05, 0x7b, 0x45, 0x2f, 0x07, 0x57, 0xca, 0x4a, 0xe1, 0x44, 0x87, 0x4f, 0xd3,
	0x8b, 0x81, 0xfe, 0x41, 0x38, 0xc1, 0x02, 0x4a, 0x11, 0x94, 0x16, 0xae, 0xb1, 0xb2, 0xdd, 0x70,
	0x14, 0x4d, 0xd3, 0x81, 0xd2, 0x7f, 0xf2, 0x7e, 0xf1, 0x67, 0x1b, 0x90, 0xcd, 0x36, 0x20, 0xff,
	0xb6, 0x01, 0xf9, 0xb9, 0x0b, 0xbc, 0xcd, 0x2e, 0xf0, 0xfe, 0xee, 0x02, 0xef, 0xeb, 0x67, 0x05,
	0x6e, 0xd9, 0xe4, 0x71, 0x61, 0x6a, 0x5e, 0x18, 0xac, 0x0d, 0x72, 0xc8, 0x8b, 0x99, 0x32, 0x7c,
	0x9d, 0x24, 0xbc, 0x36, 0x65, 0x53, 0x49, 0xec, 0x5d, 0x9f, 0xdd, 0x67, 0xfb, 0xbb, 0x61, 0x90,
	0x3f, 0xec, 0xcc, 0xbb, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xef, 0xaa, 0x6d, 0xb2, 0x2b, 0x02,
	0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AttestationProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AttestationProof) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AttestationProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintAttestations(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *ClientState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AttestationProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovAttestations(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozAttestations(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AttestationProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipAttestations(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthAttestations        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttestations          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttestations = fmt.Errorf("proto: unexpected end of group")
)
