// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_accounts/genesis/v1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/apps/27-interchain-accounts/controller/types"
	types1 "github.com/cosmos/ibc-go/v11/modules/apps/27-interchain-accounts/host/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the interchain accounts genesis state
type GenesisState struct {
	ControllerGenesisState ControllerGenesisState `protobuf:"bytes,1,opt,name=controller_genesis_state,json=controllerGenesisState,proto3" json:"controller_genesis_state"`
	HostGenesisState       HostGenesisState       `protobuf:"bytes,2,opt,name=host_genesis_state,json=hostGenesisState,proto3" json:"host_genesis_state"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetControllerGenesisState() ControllerGenesisState {
	_ = "STUB: not implemented"
	return *new(ControllerGenesisState)
}

func (m *GenesisState) GetHostGenesisState() HostGenesisState {
	_ = "STUB: not implemented"
	return *new(HostGenesisState)
}

// ControllerGenesisState defines the interchain accounts controller genesis state
type ControllerGenesisState struct {
	ActiveChannels     []ActiveChannel               `protobuf:"bytes,1,rep,name=active_channels,json=activeChannels,proto3" json:"active_channels"`
	InterchainAccounts []RegisteredInterchainAccount `protobuf:"bytes,2,rep,name=interchain_accounts,json=interchainAccounts,proto3" json:"interchain_accounts"`
	Ports              []string                      `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
	Params             types.Params                  `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
}

func (m *ControllerGenesisState) Reset()         { _ = "STUB: not implemented"; return }
func (m *ControllerGenesisState) String() string { _ = "STUB: not implemented"; return "" }
func (*ControllerGenesisState) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ControllerGenesisState) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ControllerGenesisState) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *ControllerGenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ControllerGenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ControllerGenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ControllerGenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ControllerGenesisState proto.InternalMessageInfo

func (m *ControllerGenesisState) GetActiveChannels() []ActiveChannel {
	_ = "STUB: not implemented"
	return nil
}

func (m *ControllerGenesisState) GetInterchainAccounts() []RegisteredInterchainAccount {
	_ = "STUB: not implemented"
	return nil
}

func (m *ControllerGenesisState) GetPorts() []string { _ = "STUB: not implemented"; return nil }

func (m *ControllerGenesisState) GetParams() types.Params {
	_ = "STUB: not implemented"
	return *new(types.Params)
}

// HostGenesisState defines the interchain accounts host genesis state
type HostGenesisState struct {
	ActiveChannels     []ActiveChannel               `protobuf:"bytes,1,rep,name=active_channels,json=activeChannels,proto3" json:"active_channels"`
	InterchainAccounts []RegisteredInterchainAccount `protobuf:"bytes,2,rep,name=interchain_accounts,json=interchainAccounts,proto3" json:"interchain_accounts"`
	Port               string                        `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Params             types1.Params                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
}

func (m *HostGenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HostGenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*HostGenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HostGenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HostGenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HostGenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HostGenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HostGenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HostGenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HostGenesisState proto.InternalMessageInfo

func (m *HostGenesisState) GetActiveChannels() []ActiveChannel {
	_ = "STUB: not implemented"
	return nil
}

func (m *HostGenesisState) GetInterchainAccounts() []RegisteredInterchainAccount {
	_ = "STUB: not implemented"
	return nil
}

func (m *HostGenesisState) GetPort() string { _ = "STUB: not implemented"; return "" }

func (m *HostGenesisState) GetParams() types1.Params {
	_ = "STUB: not implemented"
	return *new(types1.Params)
}

// ActiveChannel contains a connection ID, port ID and associated active channel ID, as well as a boolean flag to
// indicate if the channel is middleware enabled
type ActiveChannel struct {
	ConnectionId        string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	PortId              string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	ChannelId           string `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	IsMiddlewareEnabled bool   `protobuf:"varint,4,opt,name=is_middleware_enabled,json=isMiddlewareEnabled,proto3" json:"is_middleware_enabled,omitempty"`
}

func (m *ActiveChannel) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ActiveChannel) String() string            { _ = "STUB: not implemented"; return "" }
func (*ActiveChannel) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ActiveChannel) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ActiveChannel) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ActiveChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ActiveChannel) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ActiveChannel) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ActiveChannel) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ActiveChannel proto.InternalMessageInfo

func (m *ActiveChannel) GetConnectionId() string { _ = "STUB: not implemented"; return "" }

func (m *ActiveChannel) GetPortId() string { _ = "STUB: not implemented"; return "" }

func (m *ActiveChannel) GetChannelId() string { _ = "STUB: not implemented"; return "" }

func (m *ActiveChannel) GetIsMiddlewareEnabled() bool { _ = "STUB: not implemented"; return false }

// RegisteredInterchainAccount contains a connection ID, port ID and associated interchain account address
type RegisteredInterchainAccount struct {
	ConnectionId   string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	PortId         string `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	AccountAddress string `protobuf:"bytes,3,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
}

func (m *RegisteredInterchainAccount) Reset()         { _ = "STUB: not implemented"; return }
func (m *RegisteredInterchainAccount) String() string { _ = "STUB: not implemented"; return "" }
func (*RegisteredInterchainAccount) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*RegisteredInterchainAccount) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredInterchainAccount) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RegisteredInterchainAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredInterchainAccount) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *RegisteredInterchainAccount) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RegisteredInterchainAccount) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RegisteredInterchainAccount proto.InternalMessageInfo

func (m *RegisteredInterchainAccount) GetConnectionId() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *RegisteredInterchainAccount) GetPortId() string { _ = "STUB: not implemented"; return "" }

func (m *RegisteredInterchainAccount) GetAccountAddress() string {
	_ = "STUB: not implemented"
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "ibc.applications.interchain_accounts.genesis.v1.GenesisState")
	proto.RegisterType((*ControllerGenesisState)(nil), "ibc.applications.interchain_accounts.genesis.v1.ControllerGenesisState")
	proto.RegisterType((*HostGenesisState)(nil), "ibc.applications.interchain_accounts.genesis.v1.HostGenesisState")
	proto.RegisterType((*ActiveChannel)(nil), "ibc.applications.interchain_accounts.genesis.v1.ActiveChannel")
	proto.RegisterType((*RegisteredInterchainAccount)(nil), "ibc.applications.interchain_accounts.genesis.v1.RegisteredInterchainAccount")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_accounts/genesis/v1/genesis.proto", fileDescriptor_d4aa48c8e29a1947)
}

var fileDescriptor_d4aa48c8e29a1947 = []byte{
	// 592 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x95, 0x4f, 0x8b, 0xd3, 0x4e,
	0x18, 0xc7, 0x9b, 0x74, 0x7f, 0xfd, 0xd9, 0xd9, 0x3f, 0x2e, 0xb3, 0xeb, 0x1a, 0x56, 0x8c, 0xa5,
	0x1e, 0xec, 0xa5, 0x09, 0xad, 0xc2, 0x82, 0xa0, 0xd0, 0x2d, 0xb2, 0x16, 0x54, 0x24, 0x5e, 0xc4,
	0x4b, 0x98, 0x4e, 0x86, 0x64, 0x20, 0xc9, 0x84, 0x3c, 0xd3, 0x8a, 0x67, 0x05, 0x8f, 0xfa, 0x12,
	0x7c, 0x39, 0x7b, 0xdc, 0xa3, 0x27, 0x91, 0xf6, 0x05, 0xf8, 0x0a, 0x04, 0x99, 0x49, 0xb6, 0xad,
	0xb5, 0x4a, 0x8b, 0x47, 0x4f, 0x99, 0x79, 0xbe, 0x79, 0xbe, 0xcf, 0x27, 0xcf, 0x93, 0x64, 0xd0,
	0x03, 0x3e, 0xa4, 0x2e, 0xc9, 0xb2, 0x98, 0x53, 0x22, 0xb9, 0x48, 0xc1, 0xe5, 0xa9, 0x64, 0x39,
	0x8d, 0x08, 0x4f, 0x7d, 0x42, 0xa9, 0x18, 0xa5, 0x12, 0xdc, 0x90, 0xa5, 0x0c, 0x38, 0xb8, 0xe3,
	0xce, 0xe5, 0xd2, 0xc9, 0x72, 0x21, 0x05, 0x76, 0xf9, 0x90, 0x3a, 0x8b, 0xe9, 0xce, 0x8a, 0x74,
	0xe7, 0x32, 0x67, 0xdc, 0x39, 0x3e, 0x0c, 0x45, 0x28, 0x74, 0xae, 0xab, 0x56, 0x85, 0xcd, 0x71,
	0x7f, 0x2d, 0x0a, 0x2a, 0x52, 0x99, 0x8b, 0x38, 0x66, 0xb9, 0x02, 0x99, 0xef, 0x4a, 0x93, 0x93,
	0xb5, 0x4c, 0x22, 0x01, 0x52, 0xa5, 0xab, 0x6b, 0x91, 0xd8, 0xfc, 0x60, 0xa2, 0x9d, 0xb3, 0x02,
	0xf1, 0x85, 0x24, 0x92, 0xe1, 0xf7, 0x06, 0xb2, 0xe6, 0xf6, 0x7e, 0x89, 0xef, 0x83, 0x12, 0x2d,
	0xa3, 0x61, 0xb4, 0xb6, 0xbb, 0x67, 0xce, 0x86, 0x4f, 0xee, 0xf4, 0x67, 0x86, 0x8b, 0xb5, 0x4e,
	0xb7, 0xce, 0xbf, 0xdc, 0xaa, 0x78, 0x47, 0x74, 0xa5, 0x8a, 0x47, 0x08, 0x2b, 0xd0, 0x25, 0x04,
	0x53, 0x23, 0xf4, 0x36, 0x46, 0x78, 0x2c, 0x40, 0xae, 0x28, 0xbe, 0x1f, 0x2d, 0xc5, 0x9b, 0xdf,
	0x4d, 0x74, 0xb4, 0x9a, 0x17, 0x27, 0xe8, 0x2a, 0xa1, 0x92, 0x8f, 0x99, 0x4f, 0x23, 0x92, 0xa6,
	0x2c, 0x06, 0xcb, 0x68, 0x54, 0x5b, 0xdb, 0xdd, 0x87, 0x1b, 0xe3, 0xf4, 0xb4, 0x4f, 0xbf, 0xb0,
	0x29, 0x59, 0xf6, 0xc8, 0x62, 0x10, 0xf0, 0x5b, 0x03, 0x1d, 0xac, 0xb0, 0xb1, 0x4c, 0x5d, 0xf3,
	0xc9, 0xc6, 0x35, 0x3d, 0x16, 0x72, 0x90, 0x2c, 0x67, 0xc1, 0x60, 0x76, 0x63, 0xaf, 0xb8, 0xaf,
	0x24, 0xc0, 0x7c, 0x59, 0x00, 0x7c, 0x88, 0xfe, 0xcb, 0x44, 0x2e, 0xc1, 0xaa, 0x36, 0xaa, 0xad,
	0xba, 0x57, 0x6c, 0xf0, 0x4b, 0x54, 0xcb, 0x48, 0x4e, 0x12, 0xb0, 0xb6, 0xf4, 0x40, 0xee, 0xaf,
	0x47, 0xb3, 0xf0, 0xe2, 0x8e, 0x3b, 0xce, 0x73, 0xed, 0x50, 0xd6, 0x2e, 0xfd, 0x9a, 0xdf, 0x4c,
	0xb4, 0xbf, 0x3c, 0xac, 0x7f, 0xb3, 0xf3, 0x18, 0x6d, 0xa9, 0x66, 0x5b, 0xd5, 0x86, 0xd1, 0xaa,
	0x7b, 0x7a, 0x8d, 0xbd, 0xa5, 0xbe, 0xdf, 0x5b, 0x8f, 0x45, 0x7f, 0xf1, 0xbf, 0xeb, 0xf8, 0x27,
	0x03, 0xed, 0xfe, 0xd4, 0x15, 0x7c, 0x1b, 0xed, 0x52, 0x91, 0xa6, 0x8c, 0x2a, 0x47, 0x9f, 0x07,
	0xfa, 0xc3, 0xaf, 0x7b, 0x3b, 0xf3, 0xe0, 0x20, 0xc0, 0xd7, 0xd1, 0xff, 0x0a, 0x49, 0xc9, 0xa6,
	0x96, 0x6b, 0x6a, 0x3b, 0x08, 0xf0, 0x4d, 0x84, 0xca, 0x29, 0x29, 0xad, 0xa0, 0xaf, 0x97, 0x91,
	0x41, 0x80, 0xbb, 0xe8, 0x1a, 0x07, 0x3f, 0xe1, 0x41, 0x10, 0xb3, 0xd7, 0x24, 0x67, 0x3e, 0x4b,
	0xc9, 0x30, 0x66, 0x81, 0x7e, 0xa2, 0x2b, 0xde, 0x01, 0x87, 0xa7, 0x33, 0xed, 0x51, 0x21, 0x35,
	0xdf, 0x19, 0xe8, 0xc6, 0x1f, 0x9a, 0xf8, 0x97, 0xc0, 0x77, 0xd4, 0xdb, 0xa5, 0x8d, 0x7c, 0x12,
	0x04, 0x39, 0x03, 0x28, 0xa9, 0xf7, 0xca, 0x70, 0xaf, 0x88, 0x9e, 0x46, 0xe7, 0x13, 0xdb, 0xb8,
	0x98, 0xd8, 0xc6, 0xd7, 0x89, 0x6d, 0x7c, 0x9c, 0xda, 0x95, 0x8b, 0xa9, 0x5d, 0xf9, 0x3c, 0xb5,
	0x2b, 0xaf, 0x9e, 0x85, 0x5c, 0x46, 0xa3, 0xa1, 0x43, 0x45, 0xe2, 0x52, 0x01, 0x89, 0x00, 0x75,
	0x3c, 0xb4, 0x43, 0xe1, 0x8e, 0x3b, 0x1d, 0x37, 0x11, 0xc1, 0x28, 0x66, 0xa0, 0xfe, 0xd0, 0xe0,
	0x76, 0x4f, 0xda, 0xf3, 0x11, 0xb5, 0x7f, 0x39, 0x67, 0xe4, 0x9b, 0x8c, 0xc1, 0xb0, 0xa6, 0x7f,
	0xcf, 0x77, 0x7f, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x72, 0x3b, 0x4e, 0xa4, 0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ControllerGenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ControllerGenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ControllerGenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HostGenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HostGenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HostGenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ActiveChannel) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ActiveChannel) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ActiveChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RegisteredInterchainAccount) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredInterchainAccount) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RegisteredInterchainAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ControllerGenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HostGenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ActiveChannel) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RegisteredInterchainAccount) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ControllerGenesisState) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *HostGenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ActiveChannel) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RegisteredInterchainAccount) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
