package ibctesting

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/cosmos/cosmos-sdk/client"
	"github.com/cosmos/cosmos-sdk/codec"
	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"
	sdk "github.com/cosmos/cosmos-sdk/types"

	abci "github.com/cometbft/cometbft/abci/types"
	cmtproto "github.com/cometbft/cometbft/proto/tendermint/types"
	cmttypes "github.com/cometbft/cometbft/types"

	clienttypes "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
	channeltypes "github.com/cosmos/ibc-go/v11/modules/core/04-channel/types"
	commitmenttypes "github.com/cosmos/ibc-go/v11/modules/core/23-commitment/types"
	"github.com/cosmos/ibc-go/v11/modules/core/exported"
	ibctm "github.com/cosmos/ibc-go/v11/modules/light-clients/07-tendermint"
	"github.com/cosmos/ibc-go/v11/testing/simapp"
)

var MaxAccounts = 10

type SenderAccount struct {
	SenderPrivKey cryptotypes.PrivKey
	SenderAccount sdk.AccountI
}

const (
	DefaultGenesisAccBalance = "10000000000000000000"
)

// TestChain is a testing struct that wraps a simapp with the last TM Header, the current ABCI
// header and the validators of the TestChain. It also contains a field called ChainID. This
// is the clientID that *other* chains use to refer to this TestChain. The SenderAccount
// is used for delivering transactions through the application state.
// NOTE: the actual application uses an empty chain-id for ease of testing.
type TestChain struct {
	testing.TB

	Coordinator           *Coordinator
	App                   TestingApp
	ChainID               string
	LatestCommittedHeader *ibctm.Header   // header for last block height committed
	ProposedHeader        cmtproto.Header // proposed (uncommitted) header for current block height
	TxConfig              client.TxConfig
	Codec                 codec.Codec

	Vals     *cmttypes.ValidatorSet
	NextVals *cmttypes.ValidatorSet

	// Signers is a map from validator address to the PrivValidator
	// The map is converted into an array that is the same order as the validators right before signing commit
	// This ensures that signers will always be in correct order even as validator powers change.
	// If a test adds a new validator after chain creation, then the signer map must be updated to include
	// the new PrivValidator entry.
	Signers map[string]cmttypes.PrivValidator

	// TrustedValidators is a mapping used to obtain the validator set from which we can prove a header update.
	// It maps from a header height to the next validator set associated with that header.
	TrustedValidators map[uint64]*cmttypes.ValidatorSet

	// autogenerated sender private key
	SenderPrivKey cryptotypes.PrivKey
	SenderAccount sdk.AccountI

	SenderAccounts []SenderAccount

	// Short-term solution to override the logic of the standard SendMsgs function.
	// See issue https://github.com/cosmos/ibc-go/issues/3123 for more information.
	SendMsgsOverride func(msgs ...sdk.Msg) (*abci.ExecTxResult, error)

	// Tracks whether the next block's finalize state has been initialized.
	// Direct keeper writes in tests should target this state and only become
	// committed once NextBlock/SendMsgs completes.
	nextBlockContextInitialized bool
}

// NewTestChainWithValSet initializes a new TestChain instance with the given validator set
// and signer array. It also initializes 10 Sender accounts with a balance of 10000000000000000000 coins of
// bond denom to use for tests.
//
// The first block height is committed to state in order to allow for client creations on
// counterparty chains. The TestChain will return with a block height starting at 2.
//
// Time management is handled by the Coordinator in order to ensure synchrony between chains.
// Each update of any chain increments the block header time for all chains by 5 seconds.
//
// NOTE: to use a custom sender privkey and account for testing purposes, replace and modify this
// constructor function.
//
// CONTRACT: Validator array must be provided in the order expected by Tendermint.
// i.e. sorted first by power and then lexicographically by address.
func NewTestChainWithValSet(tb testing.TB, coord *Coordinator, chainID string, valSet *cmttypes.ValidatorSet, signers map[string]cmttypes.PrivValidator) *TestChain {
	_ = "STUB: not implemented"
	return nil
}

func newTestChainWithValSet(tb testing.TB, coord *Coordinator, chainID string, valSet *cmttypes.ValidatorSet, signers map[string]cmttypes.PrivValidator, appCreator AppCreator) *TestChain {
	_ = "STUB: not implemented"
	return nil
}

// generate genesis accounts

// add sender account

// create current header and call begin block

// create an account to send transactions from

// commit genesis block

// AppCreator is a function which returns a TestingApp and a GenesisState
type AppCreator func() (TestingApp, map[string]json.RawMessage)

// NewCustomAppTestChain creates a TestChain instance with the provided AppCreator function.
func NewCustomAppTestChain(t *testing.T, coord *Coordinator, chainID string, appCreator AppCreator) *TestChain {
	_ = "STUB: not implemented"

	// generate validators private/public key
	return nil
}

// construct validator set;
// Note that the validators are sorted by voting power
// or, if equal, by address lexical order

// NewTestChain initializes a new test chain with a default of 4 validators
// Use this function if the tests do not need custom control over the validator set
func NewTestChain(t *testing.T, coord *Coordinator, chainID string) *TestChain {
	_ = "STUB: not implemented"
	return nil
}

// GetContext returns the current context for the application.
// If called between blocks (after Commit, before FinalizeBlock), it lazily
// initializes the finalize state via NewNextBlockContext so that direct keeper
// writes target the state that will be committed in the next block.
// If called during FinalizeBlock (e.g. inside a contract callback), it returns
// the already-active finalize state without replacing it.
func (c *TestChain) GetContext() sdk.Context { _ = "STUB: not implemented"; return *new(sdk.Context) }

// Try to get the existing finalize state first. If FinalizeBlock is
// in progress, the state already exists and we must not replace it
// with NewNextBlockContext.

// tryGetContextLegacy attempts to get a context from the finalize state.
// Returns false if the finalize state is not initialized (e.g. between blocks).
func (c *TestChain) tryGetContextLegacy() (sdk.Context, bool) {
	_ = "STUB: not implemented"
	return *new(sdk.Context), false
}

//nolint:errcheck // catch nil pointer panic

// GetSimApp returns the SimApp to allow usage ofnon-interface fields.
// CONTRACT: This function should not be called by third parties implementing
// their own SimApp.
func (c *TestChain) GetSimApp() *simapp.SimApp { _ = "STUB: not implemented"; return nil }

// QueryProof performs an abci query with the given key and returns the proto encoded merkle proof
// for the query and the height at which the proof will succeed on a tendermint verifier.
func (c *TestChain) QueryProof(key []byte) ([]byte, clienttypes.Height) {
	_ = "STUB: not implemented"
	return nil, *new(clienttypes.Height)
}

// QueryProofAtHeight performs an abci query with the given key and returns the proto encoded merkle proof
// for the query and the height at which the proof will succeed on a tendermint verifier. Only the IBC
// store is supported
func (c *TestChain) QueryProofAtHeight(key []byte, height int64) ([]byte, clienttypes.Height) {
	_ = "STUB: not implemented"
	return nil, *new(clienttypes.Height)
}

// QueryProofForStore performs an abci query with the given key and returns the proto encoded merkle proof
// for the query and the height at which the proof will succeed on a tendermint verifier.
func (c *TestChain) QueryProofForStore(storeKey string, key []byte, height int64) ([]byte, clienttypes.Height) {
	_ = "STUB: not implemented"
	return nil, *new(clienttypes.Height)
}

// proof height + 1 is returned as the proof created corresponds to the height the proof
// was created in the IAVL tree. Tendermint and subsequently the clients that rely on it
// have heights 1 above the IAVL tree. Thus we return proof height + 1

// QueryUpgradeProof performs an abci query with the given key and returns the proto encoded merkle proof
// for the query and the height at which the proof will succeed on a tendermint verifier.
func (c *TestChain) QueryUpgradeProof(key []byte, height uint64) ([]byte, clienttypes.Height) {
	_ = "STUB: not implemented"
	return nil, *new(clienttypes.Height)
}

// proof height + 1 is returned as the proof created corresponds to the height the proof
// was created in the IAVL tree. Tendermint and subsequently the clients that rely on it
// have heights 1 above the IAVL tree. Thus we return proof height + 1

// QueryConsensusStateProof performs an abci query for a consensus state
// stored on the given clientID. The proof and consensusHeight are returned.
func (c *TestChain) QueryConsensusStateProof(clientID string) ([]byte, clienttypes.Height) {
	_ = "STUB: not implemented"
	return nil, *new(clienttypes.Height)
}

// NextBlock sets the last header to the current header and increments the current header to be
// at the next block height. It does not update the time as that is handled by the Coordinator.
// It will call FinalizeBlock and Commit and apply the validator set changes to the next validators
// of the next block being created. This follows the Tendermint protocol of applying valset changes
// returned on block `n` to the validators of block `n+2`.
// It calls BeginBlock with the new block created before returning.
func (c *TestChain) NextBlock() { _ = "STUB: not implemented"; return }

func (c *TestChain) commitBlock(res *abci.ResponseFinalizeBlock) { _ = "STUB: not implemented"; return }

// set the last header to the current header
// use nil trusted fields

// set the trusted validator set to the next validator set
// The latest trusted validator set is the next validator set
// associated with the header being committed in storage. This will
// allow for header updates to be proved against these validators.

// val set changes returned from previous block get applied to the next validators
// of this block. See tendermint spec for details.

// increment the proposer priority of validators

// increment the current header

// NOTE: the time is increased by the coordinator to maintain time synchrony amongst
// chains.

// sendMsgs delivers a transaction through the application without returning the result.
func (c *TestChain) sendMsgs(msgs ...sdk.Msg) error { _ = "STUB: not implemented"; return nil }

// SendMsgs delivers a transaction through the application using a predefined sender.
// It updates the senders sequence number and updates the TestChain's headers.
// It returns the result and error if one occurred.
func (c *TestChain) SendMsgs(msgs ...sdk.Msg) (*abci.ExecTxResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SendMsgsWithSender delivers a transaction through the application using the provided sender.
func (c *TestChain) SendMsgsWithSender(sender SenderAccount, msgs ...sdk.Msg) (*abci.ExecTxResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ensure the chain has the latest time

// increment acc sequence regardless of success or failure tx execution

// GetClientState retrieves the client state for the provided clientID. The client is
// expected to exist otherwise testing will fail.
func (c *TestChain) GetClientState(clientID string) exported.ClientState {
	_ = "STUB: not implemented"
	return *new(exported.ClientState)
}

// GetConsensusState retrieves the consensus state for the provided clientID and height.
// It will return a success boolean depending on if consensus state exists or not.
func (c *TestChain) GetConsensusState(clientID string, height exported.Height) (exported.ConsensusState, bool) {
	_ = "STUB: not implemented"
	return *new(exported.ConsensusState), false
}

// GetAcknowledgement retrieves an acknowledgement for the provided packet. If the
// acknowledgement does not exist then testing will fail.
func (c *TestChain) GetAcknowledgement(packet channeltypes.Packet) []byte {
	_ = "STUB: not implemented"
	return nil
}

// GetPrefix returns the prefix for used by a chain in connection creation
func (c *TestChain) GetPrefix() commitmenttypes.MerklePrefix {
	_ = "STUB: not implemented"
	return *new(commitmenttypes.MerklePrefix)
}

// ExpireClient fast forwards the chain's block time by the provided amount of time which will
// expire any clients with a trusting period less than or equal to this amount of time.
func (c *TestChain) ExpireClient(amount time.Duration) { _ = "STUB: not implemented"; return }

// CurrentTMClientHeader creates a TM header using the current header parameters
// on the chain. The trusted fields in the header are set to nil.
func (c *TestChain) CurrentTMClientHeader() *ibctm.Header { _ = "STUB: not implemented"; return nil }

// CommitHeader takes in a proposed header and returns a signed cometbft header.
// The signers passed in must match the validator set provided. The signers will
// be used to sign over the proposed header.
func CommitHeader(proposedHeader cmttypes.Header, valSet *cmttypes.ValidatorSet, signers map[string]cmttypes.PrivValidator) (*cmtproto.SignedHeader, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MakeExtCommit expects a signer array in the same order as the validator array.
// Thus we iterate over the ordered validator set and construct a signer array
// from the signer map in the same order.

// CreateTMClientHeader creates a TM header to update the TM client. Args are passed in to allow
// caller flexibility to use params that differ from the chain.
func (c *TestChain) CreateTMClientHeader(chainID string, blockHeight int64, trustedHeight clienttypes.Height, timestamp time.Time, cmtValSet, nextVals, cmtTrustedVals *cmttypes.ValidatorSet, signers map[string]cmttypes.PrivValidator) *ibctm.Header {
	_ = "STUB: not implemented"
	return nil
}

//nolint:staticcheck // will not be nil

//nolint:staticcheck

// The trusted fields may be nil. They may be filled before relaying messages to a client.
// The relayer is responsible for querying client and injecting appropriate trusted fields.

// MakeBlockID copied unimported test functions from cmttypes to use them here
func MakeBlockID(hash []byte, partSetSize uint32, partSetHash []byte) cmttypes.BlockID {
	_ = "STUB: not implemented"
	return *new(cmttypes.BlockID)
}

// GetClientLatestHeight returns the latest height for the client state with the given client identifier.
// If an invalid client identifier is provided then a zero value height will be returned and testing will fail.
func (c *TestChain) GetClientLatestHeight(clientID string) exported.Height {
	_ = "STUB: not implemented"
	return *new(exported.Height)
}

// GetTimeoutHeight is a convenience function which returns a IBC packet timeout height
// to be used for testing. It returns the current IBC height + 100 blocks
func (c *TestChain) GetTimeoutHeight() clienttypes.Height {
	_ = "STUB: not implemented"
	return *new(clienttypes.Height)
}

// GetTimeoutTimestamp is a convenience function which returns a IBC packet timeout timestamp
// to be used for testing. It returns the current block timestamp + default timestamp delta (1 hour).
func (c *TestChain) GetTimeoutTimestamp() uint64 { _ = "STUB: not implemented"; return 0 }

// GetTimeoutTimestampSecs is a convenience function which returns a IBC packet timeout timestamp in seconds
// to be used for testing. It returns the current block timestamp + default timestamp delta (1 hour).
func (c *TestChain) GetTimeoutTimestampSecs() uint64 { _ = "STUB: not implemented"; return 0 }

// DeleteKey deletes the specified key from the ibc store.
func (c *TestChain) DeleteKey(key []byte) { _ = "STUB: not implemented"; return }

// IBCClientHeader will construct a 07-tendermint Header to update the light client
// on the counterparty chain. The trustedHeight must be passed in as a non-zero height.
func (c *TestChain) IBCClientHeader(header *ibctm.Header, trustedHeight clienttypes.Height) (*ibctm.Header, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSenderAccount returns the sender account associated with the provided private key.
func (c *TestChain) GetSenderAccount(privKey cryptotypes.PrivKey) SenderAccount {
	_ = "STUB: not implemented"
	return *new(SenderAccount)
}
