// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/channel/v2/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the ibc channel/v2 submodule's genesis state.
type GenesisState struct {
	Acknowledgements []PacketState    `protobuf:"bytes,2,rep,name=acknowledgements,proto3" json:"acknowledgements"`
	Commitments      []PacketState    `protobuf:"bytes,3,rep,name=commitments,proto3" json:"commitments"`
	Receipts         []PacketState    `protobuf:"bytes,4,rep,name=receipts,proto3" json:"receipts"`
	AsyncPackets     []PacketState    `protobuf:"bytes,5,rep,name=async_packets,json=asyncPackets,proto3" json:"async_packets"`
	SendSequences    []PacketSequence `protobuf:"bytes,6,rep,name=send_sequences,json=sendSequences,proto3" json:"send_sequences"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetAcknowledgements() []PacketState { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) GetCommitments() []PacketState { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) GetReceipts() []PacketState { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) GetAsyncPackets() []PacketState { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) GetSendSequences() []PacketSequence { _ = "STUB: not implemented"; return nil }

// PacketState defines the generic type necessary to retrieve and store
// packet commitments, acknowledgements, and receipts.
// Caller is responsible for knowing the context necessary to interpret this
// state as a commitment, acknowledgement, or a receipt.
type PacketState struct {
	// client unique identifier.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// packet sequence.
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// embedded data that represents packet state.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PacketState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketState) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketState proto.InternalMessageInfo

// PacketSequence defines the genesis type necessary to retrieve and store next send sequences.
type PacketSequence struct {
	// client unique identifier.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// packet sequence
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *PacketSequence) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketSequence) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketSequence) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketSequence) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketSequence) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketSequence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketSequence) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketSequence) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketSequence) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketSequence proto.InternalMessageInfo

func (m *PacketSequence) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *PacketSequence) GetSequence() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*GenesisState)(nil), "ibc.core.channel.v2.GenesisState")
	proto.RegisterType((*PacketState)(nil), "ibc.core.channel.v2.PacketState")
	proto.RegisterType((*PacketSequence)(nil), "ibc.core.channel.v2.PacketSequence")
}

func init() { proto.RegisterFile("ibc/core/channel/v2/genesis.proto", fileDescriptor_b5d374f126f051c3) }

var fileDescriptor_b5d374f126f051c3 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x3f, 0x6f, 0xda, 0x40,
	0x18, 0xc6, 0x6d, 0xec, 0x22, 0x38, 0xfe, 0xa8, 0xba, 0x76, 0xb0, 0xa8, 0x64, 0x5c, 0xba, 0x78,
	0xc1, 0x57, 0x68, 0xa7, 0x4a, 0x5d, 0x58, 0x5a, 0xd4, 0x05, 0xb9, 0x43, 0xa5, 0x2e, 0xd4, 0x3e,
	0xbf, 0x32, 0x27, 0xec, 0x3b, 0x97, 0x3b, 0x88, 0xf8, 0x06, 0xd9, 0x92, 0x8f, 0x90, 0x8f, 0xc3,
	0xc8, 0x98, 0x29, 0x8a, 0xe0, 0x8b, 0x44, 0xd8, 0x80, 0x88, 0x12, 0x45, 0x22, 0xdb, 0xeb, 0xd7,
	0xcf, 0xef, 0xf7, 0xde, 0xf0, 0xa0, 0x8f, 0x2c, 0xa4, 0x84, 0x8a, 0x19, 0x10, 0x3a, 0x09, 0x38,
	0x87, 0x84, 0x2c, 0xfa, 0x24, 0x06, 0x0e, 0x92, 0x49, 0x2f, 0x9b, 0x09, 0x25, 0xf0, 0x3b, 0x16,
	0x52, 0x6f, 0x17, 0xf1, 0xf6, 0x11, 0x6f, 0xd1, 0x6f, 0xbd, 0x8f, 0x45, 0x2c, 0xf2, 0xff, 0x64,
	0x37, 0x15, 0xd1, 0xce, 0x95, 0x81, 0xea, 0x3f, 0x0a, 0xf8, 0xb7, 0x0a, 0x14, 0x60, 0x1f, 0xbd,
	0x0d, 0xe8, 0x94, 0x8b, 0x8b, 0x04, 0xa2, 0x18, 0x52, 0xe0, 0x4a, 0x5a, 0x25, 0xc7, 0x70, 0x6b,
	0x7d, 0xc7, 0x7b, 0x46, 0xeb, 0x8d, 0x02, 0x3a, 0x05, 0x95, 0xb3, 0x03, 0x73, 0x75, 0xd7, 0xd6,
	0xfc, 0x27, 0x3c, 0xfe, 0x89, 0x6a, 0x54, 0xa4, 0x29, 0x53, 0x85, 0xce, 0x38, 0x4b, 0x77, 0x8a,
	0xe2, 0x01, 0xaa, 0xcc, 0x80, 0x02, 0xcb, 0x94, 0xb4, 0xcc, 0xb3, 0x34, 0x47, 0x0e, 0xff, 0x42,
	0x8d, 0x40, 0x2e, 0x39, 0x1d, 0x67, 0x79, 0x48, 0x5a, 0x6f, 0xce, 0x12, 0xd5, 0x73, 0xb8, 0xd8,
	0x4b, 0x3c, 0x42, 0x4d, 0x09, 0x3c, 0x1a, 0x4b, 0xf8, 0x3f, 0x07, 0x4e, 0x41, 0x5a, 0xe5, 0xdc,
	0xf6, 0xe9, 0x25, 0xdb, 0x3e, 0xbb, 0x17, 0x36, 0x76, 0x82, 0xc3, 0x4e, 0x76, 0xfe, 0xa1, 0xda,
	0xc9, 0x51, 0xfc, 0x01, 0x55, 0x69, 0xc2, 0x80, 0xab, 0x31, 0x8b, 0x2c, 0xdd, 0xd1, 0xdd, 0xaa,
	0x5f, 0x29, 0x16, 0xc3, 0x08, 0xb7, 0x50, 0xe5, 0x70, 0xd8, 0x2a, 0x39, 0xba, 0x6b, 0xfa, 0xc7,
	0x6f, 0x8c, 0x91, 0x19, 0x05, 0x2a, 0xb0, 0x0c, 0x47, 0x77, 0xeb, 0x7e, 0x3e, 0x7f, 0x33, 0x2f,
	0x6f, 0xda, 0x5a, 0x67, 0x88, 0x9a, 0x8f, 0x1f, 0xf2, 0xea, 0x23, 0x83, 0x3f, 0xab, 0x8d, 0xad,
	0xaf, 0x37, 0xb6, 0x7e, 0xbf, 0xb1, 0xf5, 0xeb, 0xad, 0xad, 0xad, 0xb7, 0xb6, 0x76, 0xbb, 0xb5,
	0xb5, 0xbf, 0xdf, 0x63, 0xa6, 0x26, 0xf3, 0xd0, 0xa3, 0x22, 0x25, 0x54, 0xc8, 0x54, 0x48, 0xc2,
	0x42, 0xda, 0x8d, 0x05, 0x59, 0xf4, 0x7a, 0x24, 0x15, 0xd1, 0x3c, 0x01, 0x59, 0xf4, 0xf8, 0xf3,
	0xd7, 0xee, 0x49, 0x95, 0xd5, 0x32, 0x03, 0x19, 0x96, 0xf3, 0x7a, 0x7e, 0x79, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x72, 0x8a, 0x0f, 0x0a, 0xee, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketSequence) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketSequence) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketSequence) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketSequence) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketSequence) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
