// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/channel/v2/packet.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PacketStatus specifies the status of a RecvPacketResult.
type PacketStatus int32

const (
	// PACKET_STATUS_UNSPECIFIED indicates an unknown packet status.
	PacketStatus_NONE PacketStatus = 0
	// PACKET_STATUS_SUCCESS indicates a successful packet receipt.
	PacketStatus_Success PacketStatus = 1
	// PACKET_STATUS_FAILURE indicates a failed packet receipt.
	PacketStatus_Failure PacketStatus = 2
	// PACKET_STATUS_ASYNC indicates an async packet receipt.
	PacketStatus_Async PacketStatus = 3
)

var PacketStatus_name = map[int32]string{
	0: "PACKET_STATUS_UNSPECIFIED",
	1: "PACKET_STATUS_SUCCESS",
	2: "PACKET_STATUS_FAILURE",
	3: "PACKET_STATUS_ASYNC",
}

var PacketStatus_value = map[string]int32{
	"PACKET_STATUS_UNSPECIFIED": 0,
	"PACKET_STATUS_SUCCESS":     1,
	"PACKET_STATUS_FAILURE":     2,
	"PACKET_STATUS_ASYNC":       3,
}

func (x PacketStatus) String() string { _ = "STUB: not implemented"; return "" }

func (PacketStatus) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Packet defines a type that carries data across different chains through IBC
type Packet struct {
	// number corresponds to the order of sends and receives, where a Packet
	// with an earlier sequence number must be sent and received before a Packet
	// with a later sequence number.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// identifies the sending client on the sending chain.
	SourceClient string `protobuf:"bytes,2,opt,name=source_client,json=sourceClient,proto3" json:"source_client,omitempty"`
	// identifies the receiving client on the receiving chain.
	DestinationClient string `protobuf:"bytes,3,opt,name=destination_client,json=destinationClient,proto3" json:"destination_client,omitempty"`
	// timeout timestamp in seconds after which the packet times out.
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	// a list of payloads, each one for a specific application.
	Payloads []Payload `protobuf:"bytes,5,rep,name=payloads,proto3" json:"payloads"`
}

func (m *Packet) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Packet) String() string            { _ = "STUB: not implemented"; return "" }
func (*Packet) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Packet) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Packet) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Packet) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Packet) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetSequence() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Packet) GetSourceClient() string { _ = "STUB: not implemented"; return "" }

func (m *Packet) GetDestinationClient() string { _ = "STUB: not implemented"; return "" }

func (m *Packet) GetTimeoutTimestamp() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Packet) GetPayloads() []Payload { _ = "STUB: not implemented"; return nil }

// Payload contains the source and destination ports and payload for the application (version, encoding, raw bytes)
type Payload struct {
	// specifies the source port of the packet.
	SourcePort string `protobuf:"bytes,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// specifies the destination port of the packet.
	DestinationPort string `protobuf:"bytes,2,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// version of the specified application.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// the encoding used for the provided value.
	Encoding string `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	// the raw bytes for the payload.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Payload) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Payload) String() string            { _ = "STUB: not implemented"; return "" }
func (*Payload) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Payload) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Payload) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Payload) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Payload) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Payload) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetSourcePort() string { _ = "STUB: not implemented"; return "" }

func (m *Payload) GetDestinationPort() string { _ = "STUB: not implemented"; return "" }

func (m *Payload) GetVersion() string { _ = "STUB: not implemented"; return "" }

func (m *Payload) GetEncoding() string { _ = "STUB: not implemented"; return "" }

func (m *Payload) GetValue() []byte { _ = "STUB: not implemented"; return nil }

// Acknowledgement contains a list of all ack results associated with a single packet.
// In the case of a successful receive, the acknowledgement will contain an app acknowledgement
// for each application that received a payload in the same order that the payloads were sent
// in the packet.
// If the receive is not successful, the acknowledgement will contain a single app acknowledgment
// which will be a constant error acknowledgment as defined by the IBC v2 protocol.
type Acknowledgement struct {
	AppAcknowledgements [][]byte `protobuf:"bytes,1,rep,name=app_acknowledgements,json=appAcknowledgements,proto3" json:"app_acknowledgements,omitempty"`
}

func (m *Acknowledgement) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Acknowledgement) String() string            { _ = "STUB: not implemented"; return "" }
func (*Acknowledgement) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Acknowledgement) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Acknowledgement) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Acknowledgement) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

func (m *Acknowledgement) GetAppAcknowledgements() [][]byte { _ = "STUB: not implemented"; return nil }

// RecvPacketResult speecifies the status of a packet as well as the acknowledgement bytes.
type RecvPacketResult struct {
	// status of the packet
	Status PacketStatus `protobuf:"varint,1,opt,name=status,proto3,enum=ibc.core.channel.v2.PacketStatus" json:"status,omitempty"`
	// acknowledgement of the packet
	Acknowledgement []byte `protobuf:"bytes,2,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
}

func (m *RecvPacketResult) Reset()                    { _ = "STUB: not implemented"; return }
func (m *RecvPacketResult) String() string            { _ = "STUB: not implemented"; return "" }
func (*RecvPacketResult) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*RecvPacketResult) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *RecvPacketResult) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RecvPacketResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RecvPacketResult) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RecvPacketResult) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RecvPacketResult) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RecvPacketResult proto.InternalMessageInfo

func (m *RecvPacketResult) GetStatus() PacketStatus {
	_ = "STUB: not implemented"
	return *new(PacketStatus)
}

func (m *RecvPacketResult) GetAcknowledgement() []byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterEnum("ibc.core.channel.v2.PacketStatus", PacketStatus_name, PacketStatus_value)
	proto.RegisterType((*Packet)(nil), "ibc.core.channel.v2.Packet")
	proto.RegisterType((*Payload)(nil), "ibc.core.channel.v2.Payload")
	proto.RegisterType((*Acknowledgement)(nil), "ibc.core.channel.v2.Acknowledgement")
	proto.RegisterType((*RecvPacketResult)(nil), "ibc.core.channel.v2.RecvPacketResult")
}

func init() { proto.RegisterFile("ibc/core/channel/v2/packet.proto", fileDescriptor_2f814aba9ca97169) }

var fileDescriptor_2f814aba9ca97169 = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0x4d, 0xd2, 0x36, 0xdb, 0x40, 0xdd, 0x6d, 0x91, 0x4c, 0x84, 0x52, 0x13, 0x24,
	0x08, 0xa0, 0xda, 0x34, 0x70, 0xe1, 0x00, 0x52, 0xea, 0xba, 0x52, 0x05, 0x0a, 0xd1, 0x3a, 0x11,
	0x82, 0x4b, 0xb4, 0xd9, 0xac, 0x5c, 0xab, 0xb6, 0xd7, 0x78, 0xd7, 0xae, 0xfa, 0x0a, 0x3d, 0xf1,
	0x02, 0x3d, 0x70, 0xe6, 0x45, 0x7a, 0xec, 0x91, 0x13, 0x42, 0xad, 0x78, 0x0f, 0xe4, 0xb5, 0x5b,
	0xa5, 0x05, 0x4e, 0xf6, 0xfc, 0xf3, 0xfd, 0x1e, 0xfd, 0x63, 0x0d, 0x34, 0xfc, 0x29, 0xb5, 0x28,
	0x4f, 0x98, 0x45, 0x0f, 0x48, 0x14, 0xb1, 0xc0, 0xca, 0x7a, 0x56, 0x4c, 0xe8, 0x21, 0x93, 0x66,
	0x9c, 0x70, 0xc9, 0xd1, 0xba, 0x3f, 0xa5, 0x66, 0x4e, 0x98, 0x25, 0x61, 0x66, 0xbd, 0xd6, 0x86,
	0xc7, 0x3d, 0xae, 0xfa, 0x56, 0xfe, 0x56, 0xa0, 0x9d, 0xdf, 0x00, 0x2e, 0x0e, 0x95, 0x17, 0xb5,
	0xe0, 0xb2, 0x60, 0x5f, 0x52, 0x16, 0x51, 0xa6, 0x03, 0x03, 0x74, 0x6b, 0xf8, 0xba, 0x46, 0x8f,
	0xe0, 0x1d, 0xc1, 0xd3, 0x84, 0xb2, 0x09, 0x0d, 0x7c, 0x16, 0x49, 0x7d, 0xc1, 0x00, 0xdd, 0x06,
	0x6e, 0x16, 0xa2, 0xad, 0x34, 0xb4, 0x05, 0xd1, 0x8c, 0x09, 0xe9, 0x47, 0x44, 0xfa, 0x3c, 0xba,
	0x22, 0xab, 0x8a, 0x5c, 0x9b, 0xeb, 0x94, 0xf8, 0x73, 0xb8, 0x26, 0xfd, 0x90, 0xf1, 0x54, 0x4e,
	0xf2, 0xa7, 0x90, 0x24, 0x8c, 0xf5, 0x9a, 0x1a, 0xac, 0x95, 0x8d, 0xd1, 0x95, 0x8e, 0xde, 0xc2,
	0xe5, 0x98, 0x1c, 0x07, 0x9c, 0xcc, 0x84, 0x5e, 0x37, 0xaa, 0xdd, 0x95, 0xde, 0x03, 0xf3, 0x1f,
	0x29, 0xcd, 0x61, 0x01, 0xed, 0xd4, 0xce, 0x7e, 0x6e, 0x56, 0xf0, 0xb5, 0xa7, 0xf3, 0x0d, 0xc0,
	0xa5, 0xb2, 0x87, 0x36, 0xe1, 0x4a, 0x19, 0x26, 0xe6, 0x89, 0x54, 0x59, 0x1b, 0x18, 0x16, 0xd2,
	0x90, 0x27, 0x12, 0x3d, 0x85, 0xda, 0x7c, 0x10, 0x45, 0x15, 0x81, 0x57, 0xe7, 0x74, 0x85, 0xea,
	0x70, 0x29, 0x63, 0x89, 0xf0, 0x79, 0x54, 0x06, 0xbd, 0x2a, 0xf3, 0x75, 0xb2, 0x88, 0xf2, 0x99,
	0x1f, 0x79, 0x2a, 0x55, 0x03, 0x5f, 0xd7, 0x68, 0x03, 0xd6, 0x33, 0x12, 0xa4, 0x4c, 0xaf, 0x1b,
	0xa0, 0xdb, 0xc4, 0x45, 0xd1, 0xd9, 0x85, 0xab, 0x7d, 0x7a, 0x18, 0xf1, 0xa3, 0x80, 0xcd, 0x3c,
	0x16, 0xe6, 0x3b, 0xda, 0x86, 0x1b, 0x24, 0x8e, 0x27, 0xe4, 0xa6, 0x2c, 0x74, 0x60, 0x54, 0xbb,
	0x4d, 0xbc, 0x4e, 0xe2, 0xf8, 0x96, 0x43, 0x74, 0x8e, 0xa0, 0x86, 0x19, 0xcd, 0x8a, 0x9f, 0x8a,
	0x99, 0x48, 0x03, 0x89, 0x5e, 0xc3, 0x45, 0x21, 0x89, 0x4c, 0x85, 0x0a, 0x7b, 0xb7, 0xf7, 0xf0,
	0x3f, 0xbb, 0xcb, 0x2d, 0xae, 0x02, 0x71, 0x69, 0x40, 0x5d, 0xb8, 0x7a, 0x6b, 0xba, 0x5a, 0x45,
	0x13, 0xdf, 0x96, 0x9f, 0x7d, 0x07, 0xb0, 0x39, 0xff, 0x09, 0xf4, 0x04, 0xde, 0x1f, 0xf6, 0xed,
	0x77, 0xce, 0x68, 0xe2, 0x8e, 0xfa, 0xa3, 0xb1, 0x3b, 0x19, 0x0f, 0xdc, 0xa1, 0x63, 0xef, 0xef,
	0xed, 0x3b, 0xbb, 0x5a, 0xa5, 0xb5, 0x7c, 0x72, 0x6a, 0xd4, 0x06, 0x1f, 0x06, 0x0e, 0x7a, 0x0c,
	0xef, 0xdd, 0x04, 0xdd, 0xb1, 0x6d, 0x3b, 0xae, 0xab, 0x81, 0xd6, 0xca, 0xc9, 0xa9, 0xb1, 0xe4,
	0xa6, 0x94, 0x32, 0x21, 0xfe, 0xe6, 0xf6, 0xfa, 0xfb, 0xef, 0xc7, 0xd8, 0xd1, 0x16, 0x0a, 0x6e,
	0x8f, 0xf8, 0x41, 0x9a, 0x30, 0xd4, 0x81, 0xeb, 0x37, 0xb9, 0xbe, 0xfb, 0x69, 0x60, 0x6b, 0xd5,
	0x56, 0xe3, 0xe4, 0xd4, 0xa8, 0xf7, 0xc5, 0x71, 0x44, 0x77, 0x3e, 0x9e, 0x5d, 0xb4, 0xc1, 0xf9,
	0x45, 0x1b, 0xfc, 0xba, 0x68, 0x83, 0xaf, 0x97, 0xed, 0xca, 0xf9, 0x65, 0xbb, 0xf2, 0xe3, 0xb2,
	0x5d, 0xf9, 0xfc, 0xc6, 0xf3, 0xe5, 0x41, 0x3a, 0x35, 0x29, 0x0f, 0x2d, 0xca, 0x45, 0xc8, 0x85,
	0xe5, 0x4f, 0xe9, 0x96, 0xc7, 0xad, 0x6c, 0x7b, 0xdb, 0x0a, 0xf9, 0x2c, 0x0d, 0x98, 0x28, 0x0e,
	0xf0, 0xc5, 0xab, 0xad, 0xb9, 0x1b, 0x94, 0xc7, 0x31, 0x13, 0xd3, 0x45, 0x75, 0x58, 0x2f, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x2f, 0x3b, 0x07, 0xa7, 0x03, 0x00, 0x00,
}

func (m *Packet) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Packet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Payload) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Payload) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Payload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Acknowledgement) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RecvPacketResult) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RecvPacketResult) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RecvPacketResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Packet) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Payload) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RecvPacketResult) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovPacket(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozPacket(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Payload) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Acknowledgement) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RecvPacketResult) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipPacket(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
