// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/channel/v2/query.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryNextSequenceSendRequest is the request type for the Query/QueryNextSequenceSend RPC method
type QueryNextSequenceSendRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *QueryNextSequenceSendRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryNextSequenceSendRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryNextSequenceSendRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryNextSequenceSendRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryNextSequenceSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryNextSequenceSendRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryNextSequenceSendRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryNextSequenceSendRequest proto.InternalMessageInfo

func (m *QueryNextSequenceSendRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

// QueryNextSequenceSendResponse is the response type for the Query/QueryNextSequenceSend RPC method
type QueryNextSequenceSendResponse struct {
	// next sequence send number
	NextSequenceSend uint64 `protobuf:"varint,1,opt,name=next_sequence_send,json=nextSequenceSend,proto3" json:"next_sequence_send,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight types.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
}

func (m *QueryNextSequenceSendResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryNextSequenceSendResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryNextSequenceSendResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryNextSequenceSendResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryNextSequenceSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryNextSequenceSendResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryNextSequenceSendResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryNextSequenceSendResponse proto.InternalMessageInfo

func (m *QueryNextSequenceSendResponse) GetNextSequenceSend() uint64 {
	_ = "STUB: not implemented"
	return 0
}

func (m *QueryNextSequenceSendResponse) GetProof() []byte { _ = "STUB: not implemented"; return nil }

func (m *QueryNextSequenceSendResponse) GetProofHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryPacketCommitmentRequest is the request type for the Query/PacketCommitment RPC method.
type QueryPacketCommitmentRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// packet sequence
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *QueryPacketCommitmentRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketCommitmentRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketCommitmentRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketCommitmentRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketCommitmentRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketCommitmentRequest proto.InternalMessageInfo

func (m *QueryPacketCommitmentRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *QueryPacketCommitmentRequest) GetSequence() uint64 { _ = "STUB: not implemented"; return 0 }

// QueryPacketCommitmentResponse is the response type for the Query/PacketCommitment RPC method.
type QueryPacketCommitmentResponse struct {
	// packet associated with the request fields
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight types.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
}

func (m *QueryPacketCommitmentResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketCommitmentResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketCommitmentResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketCommitmentResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketCommitmentResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketCommitmentResponse proto.InternalMessageInfo

func (m *QueryPacketCommitmentResponse) GetCommitment() []byte {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentResponse) GetProof() []byte { _ = "STUB: not implemented"; return nil }

func (m *QueryPacketCommitmentResponse) GetProofHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryPacketCommitmentsRequest is the request type for the Query/PacketCommitments RPC method.
type QueryPacketCommitmentsRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// pagination request
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryPacketCommitmentsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketCommitmentsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketCommitmentsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketCommitmentsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketCommitmentsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketCommitmentsRequest proto.InternalMessageInfo

func (m *QueryPacketCommitmentsRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *QueryPacketCommitmentsRequest) GetPagination() *query.PageRequest {
	_ = "STUB: not implemented"
	return nil
}

// QueryPacketCommitmentResponse is the response type for the Query/PacketCommitment RPC method.
type QueryPacketCommitmentsResponse struct {
	// collection of packet commitments for the requested channel identifier.
	Commitments []*PacketState `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	// pagination response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height.
	Height types.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height"`
}

func (m *QueryPacketCommitmentsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketCommitmentsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketCommitmentsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketCommitmentsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketCommitmentsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketCommitmentsResponse proto.InternalMessageInfo

func (m *QueryPacketCommitmentsResponse) GetCommitments() []*PacketState {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsResponse) GetHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryPacketAcknowledgementRequest is the request type for the Query/PacketAcknowledgement RPC method.
type QueryPacketAcknowledgementRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// packet sequence
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *QueryPacketAcknowledgementRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketAcknowledgementRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketAcknowledgementRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketAcknowledgementRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketAcknowledgementRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketAcknowledgementRequest proto.InternalMessageInfo

func (m *QueryPacketAcknowledgementRequest) GetClientId() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *QueryPacketAcknowledgementRequest) GetSequence() uint64 {
	_ = "STUB: not implemented"
	return 0
}

// QueryPacketAcknowledgementResponse is the response type for the Query/PacketAcknowledgement RPC method.
type QueryPacketAcknowledgementResponse struct {
	// acknowledgement associated with the request fields
	Acknowledgement []byte `protobuf:"bytes,1,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight types.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
}

func (m *QueryPacketAcknowledgementResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketAcknowledgementResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketAcknowledgementResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketAcknowledgementResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketAcknowledgementResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementResponse) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryPacketAcknowledgementResponse proto.InternalMessageInfo

func (m *QueryPacketAcknowledgementResponse) GetAcknowledgement() []byte {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementResponse) GetProof() []byte {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementResponse) GetProofHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryPacketAcknowledgementsRequest is the request type for the
// Query/QueryPacketCommitments RPC method
type QueryPacketAcknowledgementsRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// pagination request
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// list of packet sequences
	PacketCommitmentSequences []uint64 `protobuf:"varint,3,rep,packed,name=packet_commitment_sequences,json=packetCommitmentSequences,proto3" json:"packet_commitment_sequences,omitempty"`
}

func (m *QueryPacketAcknowledgementsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketAcknowledgementsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketAcknowledgementsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketAcknowledgementsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketAcknowledgementsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementsRequest) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryPacketAcknowledgementsRequest proto.InternalMessageInfo

func (m *QueryPacketAcknowledgementsRequest) GetClientId() string {
	_ = "STUB: not implemented"
	return ""
}

func (m *QueryPacketAcknowledgementsRequest) GetPagination() *query.PageRequest {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsRequest) GetPacketCommitmentSequences() []uint64 {
	_ = "STUB: not implemented"
	return nil
}

// QueryPacketAcknowledgemetsResponse is the request type for the
// Query/QueryPacketAcknowledgements RPC method
type QueryPacketAcknowledgementsResponse struct {
	Acknowledgements []*PacketState `protobuf:"bytes,1,rep,name=acknowledgements,proto3" json:"acknowledgements,omitempty"`
	// pagination response
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height
	Height types.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height"`
}

func (m *QueryPacketAcknowledgementsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketAcknowledgementsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketAcknowledgementsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketAcknowledgementsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketAcknowledgementsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementsResponse) XXX_DiscardUnknown() {
	_ = "STUB: not implemented"
	return
}

var xxx_messageInfo_QueryPacketAcknowledgementsResponse proto.InternalMessageInfo

func (m *QueryPacketAcknowledgementsResponse) GetAcknowledgements() []*PacketState {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsResponse) GetPagination() *query.PageResponse {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsResponse) GetHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryPacketReceiptRequest is the request type for the Query/PacketReceipt RPC method.
type QueryPacketReceiptRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// packet sequence
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *QueryPacketReceiptRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketReceiptRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketReceiptRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketReceiptRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptRequest) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *QueryPacketReceiptRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketReceiptRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketReceiptRequest proto.InternalMessageInfo

func (m *QueryPacketReceiptRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *QueryPacketReceiptRequest) GetSequence() uint64 { _ = "STUB: not implemented"; return 0 }

// QueryPacketReceiptResponse is the response type for the Query/PacketReceipt RPC method.
type QueryPacketReceiptResponse struct {
	// success flag for if receipt exists
	Received bool `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	// merkle proof of existence or absence
	Proof []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight types.Height `protobuf:"bytes,4,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height"`
}

func (m *QueryPacketReceiptResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryPacketReceiptResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryPacketReceiptResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryPacketReceiptResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryPacketReceiptResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketReceiptResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryPacketReceiptResponse proto.InternalMessageInfo

func (m *QueryPacketReceiptResponse) GetReceived() bool { _ = "STUB: not implemented"; return false }

func (m *QueryPacketReceiptResponse) GetProof() []byte { _ = "STUB: not implemented"; return nil }

func (m *QueryPacketReceiptResponse) GetProofHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryUnreceivedPacketsRequest is the request type for the Query/UnreceivedPackets RPC method
type QueryUnreceivedPacketsRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// list of packet sequences
	Sequences []uint64 `protobuf:"varint,2,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
}

func (m *QueryUnreceivedPacketsRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnreceivedPacketsRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnreceivedPacketsRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnreceivedPacketsRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedPacketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnreceivedPacketsRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedPacketsRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnreceivedPacketsRequest proto.InternalMessageInfo

func (m *QueryUnreceivedPacketsRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *QueryUnreceivedPacketsRequest) GetSequences() []uint64 {
	_ = "STUB: not implemented"
	return nil
}

// QueryUnreceivedPacketsResponse is the response type for the Query/UnreceivedPacketCommitments RPC method
type QueryUnreceivedPacketsResponse struct {
	// list of unreceived packet sequences
	Sequences []uint64 `protobuf:"varint,1,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	// query block height
	Height types.Height `protobuf:"bytes,2,opt,name=height,proto3" json:"height"`
}

func (m *QueryUnreceivedPacketsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnreceivedPacketsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnreceivedPacketsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnreceivedPacketsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedPacketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnreceivedPacketsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedPacketsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnreceivedPacketsResponse proto.InternalMessageInfo

func (m *QueryUnreceivedPacketsResponse) GetSequences() []uint64 {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedPacketsResponse) GetHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

// QueryUnreceivedAcks is the request type for the
// Query/UnreceivedAcks RPC method
type QueryUnreceivedAcksRequest struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// list of acknowledgement sequences
	PacketAckSequences []uint64 `protobuf:"varint,2,rep,packed,name=packet_ack_sequences,json=packetAckSequences,proto3" json:"packet_ack_sequences,omitempty"`
}

func (m *QueryUnreceivedAcksRequest) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnreceivedAcksRequest) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnreceivedAcksRequest) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnreceivedAcksRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksRequest) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedAcksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksRequest) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnreceivedAcksRequest) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedAcksRequest) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnreceivedAcksRequest proto.InternalMessageInfo

func (m *QueryUnreceivedAcksRequest) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *QueryUnreceivedAcksRequest) GetPacketAckSequences() []uint64 {
	_ = "STUB: not implemented"
	return nil
}

// QueryUnreceivedAcksResponse is the response type for the
// Query/UnreceivedAcks RPC method
type QueryUnreceivedAcksResponse struct {
	// list of unreceived acknowledgement sequences
	Sequences []uint64 `protobuf:"varint,1,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	// query block height
	Height types.Height `protobuf:"bytes,2,opt,name=height,proto3" json:"height"`
}

func (m *QueryUnreceivedAcksResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *QueryUnreceivedAcksResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*QueryUnreceivedAcksResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*QueryUnreceivedAcksResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedAcksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *QueryUnreceivedAcksResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedAcksResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_QueryUnreceivedAcksResponse proto.InternalMessageInfo

func (m *QueryUnreceivedAcksResponse) GetSequences() []uint64 {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedAcksResponse) GetHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

func init() {
	proto.RegisterType((*QueryNextSequenceSendRequest)(nil), "ibc.core.channel.v2.QueryNextSequenceSendRequest")
	proto.RegisterType((*QueryNextSequenceSendResponse)(nil), "ibc.core.channel.v2.QueryNextSequenceSendResponse")
	proto.RegisterType((*QueryPacketCommitmentRequest)(nil), "ibc.core.channel.v2.QueryPacketCommitmentRequest")
	proto.RegisterType((*QueryPacketCommitmentResponse)(nil), "ibc.core.channel.v2.QueryPacketCommitmentResponse")
	proto.RegisterType((*QueryPacketCommitmentsRequest)(nil), "ibc.core.channel.v2.QueryPacketCommitmentsRequest")
	proto.RegisterType((*QueryPacketCommitmentsResponse)(nil), "ibc.core.channel.v2.QueryPacketCommitmentsResponse")
	proto.RegisterType((*QueryPacketAcknowledgementRequest)(nil), "ibc.core.channel.v2.QueryPacketAcknowledgementRequest")
	proto.RegisterType((*QueryPacketAcknowledgementResponse)(nil), "ibc.core.channel.v2.QueryPacketAcknowledgementResponse")
	proto.RegisterType((*QueryPacketAcknowledgementsRequest)(nil), "ibc.core.channel.v2.QueryPacketAcknowledgementsRequest")
	proto.RegisterType((*QueryPacketAcknowledgementsResponse)(nil), "ibc.core.channel.v2.QueryPacketAcknowledgementsResponse")
	proto.RegisterType((*QueryPacketReceiptRequest)(nil), "ibc.core.channel.v2.QueryPacketReceiptRequest")
	proto.RegisterType((*QueryPacketReceiptResponse)(nil), "ibc.core.channel.v2.QueryPacketReceiptResponse")
	proto.RegisterType((*QueryUnreceivedPacketsRequest)(nil), "ibc.core.channel.v2.QueryUnreceivedPacketsRequest")
	proto.RegisterType((*QueryUnreceivedPacketsResponse)(nil), "ibc.core.channel.v2.QueryUnreceivedPacketsResponse")
	proto.RegisterType((*QueryUnreceivedAcksRequest)(nil), "ibc.core.channel.v2.QueryUnreceivedAcksRequest")
	proto.RegisterType((*QueryUnreceivedAcksResponse)(nil), "ibc.core.channel.v2.QueryUnreceivedAcksResponse")
}

func init() { proto.RegisterFile("ibc/core/channel/v2/query.proto", fileDescriptor_a328cba4986edcab) }

var fileDescriptor_a328cba4986edcab = []byte{
	// 1033 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x6f, 0x1b, 0xc5,
	0x1b, 0xce, 0xc4, 0x6e, 0x95, 0xbc, 0x4e, 0x7f, 0xbf, 0x74, 0x08, 0xc8, 0xdd, 0x04, 0xd7, 0x5d,
	0x24, 0xb0, 0x10, 0xdd, 0x89, 0x5d, 0x04, 0x95, 0xaa, 0x02, 0x49, 0x44, 0x1b, 0x04, 0xaa, 0xca,
	0x06, 0x54, 0x29, 0xaa, 0x64, 0xad, 0xd7, 0xc3, 0x66, 0xb1, 0xbd, 0xb3, 0xf5, 0xac, 0x4d, 0xaa,
	0x2a, 0x17, 0xc4, 0x85, 0x1b, 0x52, 0x6f, 0x7c, 0x02, 0xf8, 0x10, 0x20, 0x71, 0x6b, 0x6f, 0x45,
	0x08, 0x89, 0x13, 0x54, 0x09, 0x12, 0xdf, 0x80, 0x33, 0xf2, 0xcc, 0xd8, 0xde, 0xb5, 0xd7, 0x9b,
	0xdd, 0xb4, 0x41, 0xdc, 0x66, 0xc7, 0xef, 0x9f, 0xe7, 0x79, 0xe7, 0x79, 0xe7, 0x9d, 0x04, 0x2e,
	0xba, 0x0d, 0x9b, 0xd8, 0xac, 0x4b, 0x89, 0xbd, 0x67, 0x79, 0x1e, 0x6d, 0x93, 0x7e, 0x8d, 0xdc,
	0xeb, 0xd1, 0xee, 0x7d, 0xc3, 0xef, 0xb2, 0x80, 0xe1, 0x17, 0xdc, 0x86, 0x6d, 0x0c, 0x0c, 0x0c,
	0x65, 0x60, 0xf4, 0x6b, 0xda, 0xeb, 0x36, 0xe3, 0x1d, 0xc6, 0x49, 0xc3, 0xe2, 0x54, 0x5a, 0x93,
	0x7e, 0xb5, 0x41, 0x03, 0xab, 0x4a, 0x7c, 0xcb, 0x71, 0x3d, 0x2b, 0x70, 0x99, 0x27, 0x03, 0x68,
	0x97, 0xe2, 0x32, 0x38, 0xd4, 0xa3, 0xdc, 0xe5, 0xca, 0x24, 0x04, 0xa2, 0xed, 0x52, 0x2f, 0x20,
	0xfd, 0xaa, 0x5a, 0x29, 0x83, 0x35, 0x87, 0x31, 0xa7, 0x4d, 0x89, 0xe5, 0xbb, 0xc4, 0xf2, 0x3c,
	0x16, 0x88, 0x04, 0x43, 0xf7, 0x15, 0x87, 0x39, 0x4c, 0x2c, 0xc9, 0x60, 0x25, 0x77, 0xf5, 0x6b,
	0xb0, 0xf6, 0xf1, 0x00, 0xd9, 0x2d, 0xba, 0x1f, 0xec, 0xd0, 0x7b, 0x3d, 0xea, 0xd9, 0x74, 0x87,
	0x7a, 0x4d, 0x73, 0xb0, 0xe6, 0x01, 0x5e, 0x85, 0x45, 0x99, 0xa3, 0xee, 0x36, 0x8b, 0xa8, 0x8c,
	0x2a, 0x8b, 0xe6, 0x82, 0xdc, 0xf8, 0xa0, 0xa9, 0x7f, 0x87, 0xe0, 0xe5, 0x19, 0xde, 0xdc, 0x67,
	0x1e, 0xa7, 0xf8, 0x0d, 0xc0, 0x1e, 0xdd, 0x0f, 0xea, 0x5c, 0xfd, 0x58, 0xe7, 0xd4, 0x93, 0x71,
	0xf2, 0xe6, 0xb2, 0x37, 0xe1, 0x85, 0x57, 0xe0, 0x8c, 0xdf, 0x65, 0xec, 0xb3, 0xe2, 0x7c, 0x19,
	0x55, 0x96, 0x4c, 0xf9, 0x81, 0xb7, 0x60, 0x49, 0x2c, 0xea, 0x7b, 0xd4, 0x75, 0xf6, 0x82, 0x62,
	0xae, 0x8c, 0x2a, 0x85, 0x9a, 0x66, 0x8c, 0x4b, 0x2e, 0x8b, 0xd0, 0xaf, 0x1a, 0xdb, 0xc2, 0x62,
	0x33, 0xff, 0xe8, 0xf7, 0x8b, 0x73, 0x66, 0x41, 0x78, 0xc9, 0x2d, 0xfd, 0x8e, 0xe2, 0x79, 0xdb,
	0xb2, 0x5b, 0x34, 0xd8, 0x62, 0x9d, 0x8e, 0x1b, 0x74, 0xa8, 0x17, 0xa4, 0xe1, 0x89, 0x35, 0x58,
	0x18, 0x12, 0x10, 0xd0, 0xf2, 0xe6, 0xe8, 0x5b, 0xff, 0x76, 0x58, 0x83, 0xe9, 0xc8, 0xaa, 0x06,
	0x25, 0x00, 0x7b, 0xb4, 0x2b, 0x62, 0x2f, 0x99, 0xa1, 0x9d, 0xd3, 0x64, 0xfd, 0xd5, 0x2c, 0x70,
	0x3c, 0x15, 0xef, 0x1b, 0x00, 0x63, 0xa1, 0x0a, 0x78, 0x85, 0xda, 0xab, 0x86, 0x54, 0xb5, 0x31,
	0x50, 0xb5, 0x21, 0x7b, 0x40, 0xa9, 0xda, 0xb8, 0x6d, 0x39, 0x54, 0x05, 0x36, 0x43, 0x9e, 0xfa,
	0x5f, 0x08, 0x4a, 0xb3, 0x60, 0xa8, 0x22, 0x6d, 0x42, 0x61, 0x5c, 0x12, 0x5e, 0x44, 0xe5, 0x5c,
	0xa5, 0x50, 0x2b, 0x1b, 0x31, 0x6d, 0x65, 0xc8, 0x20, 0x3b, 0x81, 0x15, 0x50, 0x33, 0xec, 0x84,
	0x6f, 0xc6, 0xc0, 0x7d, 0xed, 0x58, 0xb8, 0x12, 0x40, 0x18, 0x2f, 0xbe, 0x0a, 0x67, 0x33, 0x56,
	0x5d, 0xd9, 0xeb, 0x77, 0xe1, 0x52, 0x88, 0xe8, 0x86, 0xdd, 0xf2, 0xd8, 0x17, 0x6d, 0xda, 0x74,
	0xe8, 0x73, 0xd1, 0xda, 0xf7, 0x08, 0xf4, 0xa4, 0xf0, 0xaa, 0x96, 0x15, 0xf8, 0xbf, 0x15, 0xfd,
	0x49, 0xa9, 0x6e, 0x72, 0xfb, 0x34, 0xa5, 0xf7, 0x38, 0x11, 0xeb, 0xbf, 0xaa, 0x3f, 0xfc, 0x0e,
	0xac, 0xfa, 0x02, 0x45, 0x7d, 0x2c, 0x97, 0xd1, 0x95, 0xc4, 0x8b, 0xb9, 0x72, 0xae, 0x92, 0x37,
	0x2f, 0xf8, 0x13, 0xe2, 0x1c, 0x5e, 0x4d, 0x5c, 0xff, 0x1b, 0xc1, 0x2b, 0x89, 0x5c, 0x54, 0xe1,
	0x3f, 0x82, 0xe5, 0x89, 0x0a, 0xa7, 0x57, 0xf2, 0x94, 0xe7, 0x7f, 0x41, 0xce, 0x9f, 0xc0, 0x85,
	0x10, 0x6f, 0x93, 0xda, 0xd4, 0xf5, 0x9f, 0x5d, 0xc6, 0x0f, 0x11, 0x68, 0x71, 0x61, 0x55, 0x15,
	0x35, 0x58, 0xe8, 0x0e, 0xb6, 0xfa, 0xb4, 0x29, 0x5c, 0x17, 0xcc, 0xd1, 0xf7, 0x58, 0xb0, 0xb9,
	0x24, 0xc1, 0xe6, 0x4f, 0x22, 0xd8, 0x5d, 0x75, 0x55, 0x7e, 0xea, 0x0d, 0xb3, 0x49, 0x78, 0xe9,
	0xa4, 0xba, 0x06, 0x8b, 0x63, 0x41, 0xcd, 0x0b, 0x41, 0x8d, 0x37, 0xf4, 0x7d, 0x75, 0xff, 0xc5,
	0xc4, 0x56, 0xa4, 0x23, 0xfe, 0x68, 0xc2, 0x3f, 0x74, 0x82, 0xf3, 0x19, 0x4f, 0xb0, 0xa5, 0x4a,
	0x3d, 0xce, 0xbc, 0x61, 0xb7, 0xd2, 0x51, 0x5a, 0x87, 0x15, 0xd5, 0x35, 0x96, 0xdd, 0xaa, 0x4f,
	0xb2, 0xc3, 0xfe, 0xb0, 0x17, 0xc6, 0x7d, 0xd2, 0x83, 0xd5, 0xd8, 0x64, 0xa7, 0xcb, 0xb1, 0xf6,
	0xf5, 0x39, 0x38, 0x23, 0xf2, 0xe2, 0x1f, 0x11, 0x2c, 0x4f, 0xbe, 0x45, 0x70, 0x35, 0xb6, 0xf7,
	0x92, 0x5e, 0x3d, 0x5a, 0x2d, 0x8b, 0x8b, 0x64, 0xa7, 0x6f, 0x7d, 0xf9, 0xcb, 0x9f, 0x0f, 0xe7,
	0xaf, 0xe3, 0x6b, 0x24, 0xee, 0x29, 0x27, 0x29, 0x70, 0xf2, 0x60, 0x54, 0xef, 0x03, 0x32, 0xfd,
	0x32, 0xc2, 0x8f, 0x11, 0x2c, 0x4f, 0x0e, 0xc9, 0x24, 0x02, 0x33, 0x9e, 0x33, 0x49, 0x04, 0x66,
	0xbd, 0x53, 0xf4, 0x5b, 0x82, 0xc0, 0x36, 0xbe, 0x91, 0x9a, 0xc0, 0xd4, 0xa5, 0xca, 0xc9, 0x83,
	0x21, 0x9f, 0x03, 0xfc, 0x13, 0x82, 0xf3, 0x53, 0x03, 0x1f, 0x67, 0x40, 0x36, 0x94, 0xa9, 0x76,
	0x25, 0x93, 0xcf, 0x89, 0xcf, 0x63, 0x9a, 0x0e, 0xfe, 0x19, 0xc1, 0x8b, 0xb1, 0x97, 0x3e, 0x7e,
	0xeb, 0x38, 0x4c, 0xf1, 0xc3, 0x5f, 0x7b, 0x3b, 0xb3, 0x9f, 0xe2, 0x73, 0x53, 0xf0, 0xd9, 0xc0,
	0xef, 0x66, 0xe5, 0x63, 0xd9, 0xad, 0xc8, 0xb9, 0xfc, 0x8a, 0xe0, 0xa5, 0xf8, 0x41, 0x86, 0xb3,
	0x82, 0x1b, 0x9d, 0xd0, 0xd5, 0xec, 0x8e, 0x8a, 0xd6, 0xb6, 0xa0, 0xb5, 0x89, 0xdf, 0x3b, 0x01,
	0xad, 0x28, 0xf8, 0x1f, 0x10, 0x9c, 0x8b, 0x4c, 0x14, 0x6c, 0x1c, 0x87, 0x2a, 0x3a, 0xd1, 0x34,
	0x92, 0xda, 0x5e, 0x81, 0xff, 0x50, 0x80, 0x7f, 0x1f, 0x6f, 0x65, 0x05, 0xdf, 0x95, 0x81, 0x22,
	0xe7, 0xf2, 0x14, 0xc1, 0xf9, 0xa9, 0x01, 0x91, 0xd4, 0x2f, 0xb3, 0x26, 0x55, 0x52, 0xbf, 0xcc,
	0x9c, 0x40, 0x7a, 0x43, 0x70, 0xb9, 0x8b, 0x77, 0x9f, 0x4b, 0xfb, 0xf3, 0x03, 0xd2, 0x1b, 0xa5,
	0xaa, 0xfb, 0x8a, 0xcc, 0x1f, 0x08, 0xfe, 0x17, 0x1d, 0x0e, 0x98, 0xa4, 0xc1, 0x1a, 0x9a, 0x59,
	0xda, 0x7a, 0x7a, 0x07, 0xc5, 0xec, 0x73, 0xc1, 0xac, 0x89, 0x1b, 0xcf, 0xc4, 0x2c, 0x6e, 0x16,
	0x46, 0x48, 0x0e, 0xfa, 0x6c, 0xf3, 0xce, 0xa3, 0xc3, 0x12, 0x7a, 0x72, 0x58, 0x42, 0x4f, 0x0f,
	0x4b, 0xe8, 0x9b, 0xa3, 0xd2, 0xdc, 0x93, 0xa3, 0xd2, 0xdc, 0x6f, 0x47, 0xa5, 0xb9, 0xdd, 0xeb,
	0x8e, 0x1b, 0xec, 0xf5, 0x1a, 0x86, 0xcd, 0x3a, 0x44, 0xfd, 0x63, 0xc0, 0x6d, 0xd8, 0x97, 0x1d,
	0x46, 0xfa, 0xd5, 0x2a, 0xe9, 0xb0, 0x66, 0xaf, 0x4d, 0xb9, 0x44, 0xb7, 0xfe, 0xe6, 0xe5, 0x10,
	0xc0, 0xe0, 0xbe, 0x4f, 0x79, 0xe3, 0xac, 0xf8, 0x7b, 0xfd, 0xca, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc3, 0x6c, 0xe5, 0x6e, 0x8b, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// NextSequenceSend returns the next send sequence for a given channel.
	NextSequenceSend(ctx context.Context, in *QueryNextSequenceSendRequest, opts ...grpc.CallOption) (*QueryNextSequenceSendResponse, error)
	// PacketCommitment queries a stored packet commitment hash.
	PacketCommitment(ctx context.Context, in *QueryPacketCommitmentRequest, opts ...grpc.CallOption) (*QueryPacketCommitmentResponse, error)
	// PacketCommitments queries a stored packet commitment hash.
	PacketCommitments(ctx context.Context, in *QueryPacketCommitmentsRequest, opts ...grpc.CallOption) (*QueryPacketCommitmentsResponse, error)
	// PacketAcknowledgement queries a stored acknowledgement commitment hash.
	PacketAcknowledgement(ctx context.Context, in *QueryPacketAcknowledgementRequest, opts ...grpc.CallOption) (*QueryPacketAcknowledgementResponse, error)
	// PacketAcknowledgements returns all packet acknowledgements associated with a channel.
	PacketAcknowledgements(ctx context.Context, in *QueryPacketAcknowledgementsRequest, opts ...grpc.CallOption) (*QueryPacketAcknowledgementsResponse, error)
	// PacketReceipt queries a stored packet receipt.
	PacketReceipt(ctx context.Context, in *QueryPacketReceiptRequest, opts ...grpc.CallOption) (*QueryPacketReceiptResponse, error)
	// UnreceivedPackets returns all the unreceived IBC packets associated with a channel and sequences.
	UnreceivedPackets(ctx context.Context, in *QueryUnreceivedPacketsRequest, opts ...grpc.CallOption) (*QueryUnreceivedPacketsResponse, error)
	// UnreceivedAcks returns all the unreceived IBC acknowledgements associated with a channel and sequences.
	UnreceivedAcks(ctx context.Context, in *QueryUnreceivedAcksRequest, opts ...grpc.CallOption) (*QueryUnreceivedAcksResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	_ = "STUB: not implemented"
	return *new(QueryClient)
}

func (c *queryClient) NextSequenceSend(ctx context.Context, in *QueryNextSequenceSendRequest, opts ...grpc.CallOption) (*QueryNextSequenceSendResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PacketCommitment(ctx context.Context, in *QueryPacketCommitmentRequest, opts ...grpc.CallOption) (*QueryPacketCommitmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PacketCommitments(ctx context.Context, in *QueryPacketCommitmentsRequest, opts ...grpc.CallOption) (*QueryPacketCommitmentsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PacketAcknowledgement(ctx context.Context, in *QueryPacketAcknowledgementRequest, opts ...grpc.CallOption) (*QueryPacketAcknowledgementResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PacketAcknowledgements(ctx context.Context, in *QueryPacketAcknowledgementsRequest, opts ...grpc.CallOption) (*QueryPacketAcknowledgementsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) PacketReceipt(ctx context.Context, in *QueryPacketReceiptRequest, opts ...grpc.CallOption) (*QueryPacketReceiptResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) UnreceivedPackets(ctx context.Context, in *QueryUnreceivedPacketsRequest, opts ...grpc.CallOption) (*QueryUnreceivedPacketsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *queryClient) UnreceivedAcks(ctx context.Context, in *QueryUnreceivedAcksRequest, opts ...grpc.CallOption) (*QueryUnreceivedAcksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// NextSequenceSend returns the next send sequence for a given channel.
	NextSequenceSend(context.Context, *QueryNextSequenceSendRequest) (*QueryNextSequenceSendResponse, error)
	// PacketCommitment queries a stored packet commitment hash.
	PacketCommitment(context.Context, *QueryPacketCommitmentRequest) (*QueryPacketCommitmentResponse, error)
	// PacketCommitments queries a stored packet commitment hash.
	PacketCommitments(context.Context, *QueryPacketCommitmentsRequest) (*QueryPacketCommitmentsResponse, error)
	// PacketAcknowledgement queries a stored acknowledgement commitment hash.
	PacketAcknowledgement(context.Context, *QueryPacketAcknowledgementRequest) (*QueryPacketAcknowledgementResponse, error)
	// PacketAcknowledgements returns all packet acknowledgements associated with a channel.
	PacketAcknowledgements(context.Context, *QueryPacketAcknowledgementsRequest) (*QueryPacketAcknowledgementsResponse, error)
	// PacketReceipt queries a stored packet receipt.
	PacketReceipt(context.Context, *QueryPacketReceiptRequest) (*QueryPacketReceiptResponse, error)
	// UnreceivedPackets returns all the unreceived IBC packets associated with a channel and sequences.
	UnreceivedPackets(context.Context, *QueryUnreceivedPacketsRequest) (*QueryUnreceivedPacketsResponse, error)
	// UnreceivedAcks returns all the unreceived IBC acknowledgements associated with a channel and sequences.
	UnreceivedAcks(context.Context, *QueryUnreceivedAcksRequest) (*QueryUnreceivedAcksResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) NextSequenceSend(ctx context.Context, req *QueryNextSequenceSendRequest) (*QueryNextSequenceSendResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PacketCommitment(ctx context.Context, req *QueryPacketCommitmentRequest) (*QueryPacketCommitmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PacketCommitments(ctx context.Context, req *QueryPacketCommitmentsRequest) (*QueryPacketCommitmentsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PacketAcknowledgement(ctx context.Context, req *QueryPacketAcknowledgementRequest) (*QueryPacketAcknowledgementResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PacketAcknowledgements(ctx context.Context, req *QueryPacketAcknowledgementsRequest) (*QueryPacketAcknowledgementsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) PacketReceipt(ctx context.Context, req *QueryPacketReceiptRequest) (*QueryPacketReceiptResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) UnreceivedPackets(ctx context.Context, req *QueryUnreceivedPacketsRequest) (*QueryUnreceivedPacketsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedQueryServer) UnreceivedAcks(ctx context.Context, req *QueryUnreceivedAcksRequest) (*QueryUnreceivedAcksResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) { _ = "STUB: not implemented"; return }

func _Query_NextSequenceSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PacketCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PacketCommitments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PacketAcknowledgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PacketAcknowledgements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_PacketReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_UnreceivedPackets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Query_UnreceivedAcks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.core.channel.v2.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextSequenceSend",
			Handler:    _Query_NextSequenceSend_Handler,
		},
		{
			MethodName: "PacketCommitment",
			Handler:    _Query_PacketCommitment_Handler,
		},
		{
			MethodName: "PacketCommitments",
			Handler:    _Query_PacketCommitments_Handler,
		},
		{
			MethodName: "PacketAcknowledgement",
			Handler:    _Query_PacketAcknowledgement_Handler,
		},
		{
			MethodName: "PacketAcknowledgements",
			Handler:    _Query_PacketAcknowledgements_Handler,
		},
		{
			MethodName: "PacketReceipt",
			Handler:    _Query_PacketReceipt_Handler,
		},
		{
			MethodName: "UnreceivedPackets",
			Handler:    _Query_UnreceivedPackets_Handler,
		},
		{
			MethodName: "UnreceivedAcks",
			Handler:    _Query_UnreceivedAcks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/core/channel/v2/query.proto",
}

func (m *QueryNextSequenceSendRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryNextSequenceSendRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryNextSequenceSendResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryNextSequenceSendResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryNextSequenceSendResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketCommitmentsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketCommitmentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketAcknowledgementsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketAcknowledgementsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketReceiptRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketReceiptRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketReceiptResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryPacketReceiptResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryPacketReceiptResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedPacketsRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedPacketsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedPacketsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedPacketsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedPacketsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedAcksRequest) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksRequest) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedAcksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedAcksResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *QueryUnreceivedAcksResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *QueryUnreceivedAcksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *QueryNextSequenceSendRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryNextSequenceSendResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketCommitmentsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketAcknowledgementsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketReceiptRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryPacketReceiptResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedPacketsRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedPacketsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedAcksRequest) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryUnreceivedAcksResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozQuery(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *QueryNextSequenceSendRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryNextSequenceSendResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketCommitmentsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketAcknowledgementsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketReceiptRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryPacketReceiptResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedPacketsRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedPacketsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedAcksRequest) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *QueryUnreceivedAcksResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
