// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/commitment/v1/commitment.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_go "github.com/cosmos/ics23/go"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MerkleRoot defines a merkle root hash.
// In the Cosmos SDK, the AppHash of a block header becomes the root.
type MerkleRoot struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *MerkleRoot) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MerkleRoot) String() string            { _ = "STUB: not implemented"; return "" }
func (*MerkleRoot) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MerkleRoot) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MerkleRoot) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MerkleRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MerkleRoot) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MerkleRoot) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MerkleRoot) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MerkleRoot proto.InternalMessageInfo

// MerklePrefix is merkle path prefixed to the key.
// The constructed key from the Path and the key will be append(Path.KeyPath,
// append(Path.KeyPrefix, key...))
type MerklePrefix struct {
	KeyPrefix []byte `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
}

func (m *MerklePrefix) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MerklePrefix) String() string            { _ = "STUB: not implemented"; return "" }
func (*MerklePrefix) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MerklePrefix) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MerklePrefix) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MerklePrefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MerklePrefix) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MerklePrefix) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MerklePrefix) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MerklePrefix proto.InternalMessageInfo

func (m *MerklePrefix) GetKeyPrefix() []byte { _ = "STUB: not implemented"; return nil }

// MerkleProof is a wrapper type over a chain of CommitmentProofs.
// It demonstrates membership or non-membership for an element or set of
// elements, verifiable in conjunction with a known commitment root. Proofs
// should be succinct.
// MerkleProofs are ordered from leaf-to-root
type MerkleProof struct {
	Proofs []*_go.CommitmentProof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
}

func (m *MerkleProof) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MerkleProof) String() string            { _ = "STUB: not implemented"; return "" }
func (*MerkleProof) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MerkleProof) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MerkleProof) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MerkleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MerkleProof) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MerkleProof) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MerkleProof) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MerkleProof proto.InternalMessageInfo

func (m *MerkleProof) GetProofs() []*_go.CommitmentProof { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*MerkleRoot)(nil), "ibc.core.commitment.v1.MerkleRoot")
	proto.RegisterType((*MerklePrefix)(nil), "ibc.core.commitment.v1.MerklePrefix")
	proto.RegisterType((*MerkleProof)(nil), "ibc.core.commitment.v1.MerkleProof")
}

func init() {
	proto.RegisterFile("ibc/core/commitment/v1/commitment.proto", fileDescriptor_7921d88972a41469)
}

var fileDescriptor_7921d88972a41469 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0xc3, 0x40,
	0x18, 0x86, 0x73, 0x58, 0x0a, 0x5e, 0x3b, 0x05, 0x91, 0x52, 0xf4, 0x2c, 0x1d, 0xb4, 0x4b, 0xee,
	0x48, 0xb2, 0x88, 0xe0, 0xa2, 0x83, 0x93, 0x20, 0x59, 0x04, 0x17, 0x31, 0xe7, 0x25, 0x39, 0xd2,
	0xf8, 0x85, 0xdc, 0x35, 0x98, 0x7f, 0xe0, 0xe8, 0x4f, 0xf0, 0xe7, 0x38, 0x76, 0x74, 0x94, 0xe4,
	0x8f, 0x48, 0xee, 0x5a, 0xc9, 0xf6, 0x7d, 0xbc, 0xcf, 0xdd, 0xf7, 0xbe, 0x2f, 0xbe, 0x90, 0x31,
	0x67, 0x1c, 0x2a, 0xc1, 0x38, 0x14, 0x85, 0xd4, 0x85, 0x78, 0xd3, 0xac, 0xf6, 0x07, 0x1b, 0x2d,
	0x2b, 0xd0, 0xe0, 0x1e, 0xcb, 0x98, 0xd3, 0x1e, 0xa4, 0x03, 0xa9, 0xf6, 0xe7, 0x47, 0x29, 0xa4,
	0x60, 0x10, 0xd6, 0x4f, 0x96, 0x9e, 0x9f, 0x70, 0x50, 0x05, 0x28, 0x26, 0xb9, 0x0a, 0xc2, 0xfe,
	0xbf, 0xb2, 0x02, 0x48, 0x94, 0x55, 0x97, 0xe7, 0x18, 0xdf, 0x8b, 0x2a, 0x5f, 0x8b, 0x08, 0x40,
	0xbb, 0x2e, 0x1e, 0x65, 0x2f, 0x2a, 0x9b, 0xa1, 0x05, 0x5a, 0x4d, 0x23, 0x33, 0x5f, 0x8d, 0x3e,
	0xbe, 0xce, 0x9c, 0xa5, 0x87, 0xa7, 0x96, 0x7b, 0xa8, 0x44, 0x22, 0xdf, 0xdd, 0x53, 0x8c, 0x73,
	0xd1, 0x3c, 0x97, 0x66, 0xdb, 0xf1, 0x87, 0xb9, 0x68, 0xac, 0xbc, 0xbc, 0xc3, 0x93, 0x3d, 0x0e,
	0x90, 0xb8, 0x97, 0x78, 0x6c, 0xaf, 0xce, 0xd0, 0xe2, 0x60, 0x35, 0x09, 0x16, 0xd4, 0x9a, 0xa2,
	0xc6, 0x14, 0xad, 0x7d, 0x7a, 0xfb, 0x9f, 0xc4, 0xbc, 0x88, 0x76, 0xfc, 0xcd, 0xe3, 0x77, 0x4b,
	0xd0, 0xb6, 0x25, 0xe8, 0xb7, 0x25, 0xe8, 0xb3, 0x23, 0xce, 0xb6, 0x23, 0xce, 0x4f, 0x47, 0x9c,
	0xa7, 0xeb, 0x54, 0xea, 0x6c, 0x13, 0xf7, 0x1d, 0xb0, 0x7d, 0xc4, 0x98, 0x7b, 0x29, 0xb0, 0xda,
	0xf7, 0x59, 0x01, 0xaf, 0x9b, 0xb5, 0x50, 0xb6, 0xcf, 0x20, 0xf4, 0x06, 0x95, 0xea, 0xa6, 0x14,
	0x2a, 0x1e, 0x9b, 0xfc, 0xe1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x84, 0x54, 0xdf, 0x76,
	0x01, 0x00, 0x00,
}

func (m *MerkleRoot) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *MerkleRoot) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *MerkleRoot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MerklePrefix) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MerklePrefix) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MerklePrefix) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MerkleProof) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MerkleProof) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *MerkleProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintCommitment(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *MerkleRoot) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MerklePrefix) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MerkleProof) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovCommitment(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozCommitment(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MerkleRoot) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MerklePrefix) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MerkleProof) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipCommitment(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthCommitment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommitment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommitment = fmt.Errorf("proto: unexpected end of group")
)
