// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/client/v2/config.proto

package types

import (
	fmt "fmt"
	math "math"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Config is a **per-client** configuration struct that sets which relayers are allowed to relay v2 IBC messages
// for a given client.
// If it is set, then only relayers in the allow list can send v2 messages
// If it is not set, then the client allows permissionless relaying of v2 messages
type Config struct {
	// allowed_relayers defines the set of allowed relayers for IBC V2 protocol for the given client
	AllowedRelayers []string `protobuf:"bytes,1,rep,name=allowed_relayers,json=allowedRelayers,proto3" json:"allowed_relayers,omitempty"`
}

func (m *Config) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Config) String() string            { _ = "STUB: not implemented"; return "" }
func (*Config) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Config) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Config) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Config) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Config) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Config) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetAllowedRelayers() []string { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*Config)(nil), "ibc.core.client.v2.Config")
}

func init() { proto.RegisterFile("ibc/core/client/v2/config.proto", fileDescriptor_e89b8f1b1dcb51cb) }

var fileDescriptor_e89b8f1b1dcb51cb = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x4c, 0x4a, 0xd6,
	0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2f, 0x33, 0xd2, 0x4f,
	0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xca, 0x4c, 0x4a,
	0xd6, 0x03, 0x29, 0xd0, 0x83, 0x28, 0xd0, 0x2b, 0x33, 0x52, 0x32, 0xe6, 0x62, 0x73, 0x06, 0xab,
	0x11, 0xd2, 0xe4, 0x12, 0x48, 0xcc, 0xc9, 0xc9, 0x2f, 0x4f, 0x4d, 0x89, 0x2f, 0x4a, 0xcd, 0x49,
	0xac, 0x4c, 0x2d, 0x2a, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0xe2, 0x87, 0x8a, 0x07, 0x41,
	0x85, 0x9d, 0xc2, 0x4e, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6,
	0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0xca, 0x26, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0x39, 0xbf, 0x38, 0x37, 0xbf, 0x58,
	0x3f, 0x33, 0x29, 0x59, 0x37, 0x3d, 0x5f, 0xbf, 0xcc, 0xd0, 0x50, 0x3f, 0x37, 0x3f, 0xa5, 0x34,
	0x27, 0xb5, 0x18, 0xe2, 0x48, 0x03, 0x23, 0x5d, 0x84, 0x3b, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0x93,
	0xd8, 0xc0, 0xee, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x75, 0xc1, 0xad, 0x3a, 0xca, 0x00,
	0x00, 0x00,
}

func (m *Config) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Config) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Config) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovConfig(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozConfig(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Config) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipConfig(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
