// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/client/v2/counterparty.proto

package types

import (
	fmt "fmt"
	math "math"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CounterpartyInfo defines the key that the counterparty will use to message our client
type CounterpartyInfo struct {
	// merkle prefix key is the prefix that ics provable keys are stored under
	MerklePrefix [][]byte `protobuf:"bytes,1,rep,name=merkle_prefix,json=merklePrefix,proto3" json:"merkle_prefix,omitempty"`
	// client identifier is the identifier used to send packet messages to our client
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *CounterpartyInfo) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CounterpartyInfo) String() string            { _ = "STUB: not implemented"; return "" }
func (*CounterpartyInfo) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CounterpartyInfo) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CounterpartyInfo) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CounterpartyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CounterpartyInfo) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CounterpartyInfo) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CounterpartyInfo) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CounterpartyInfo proto.InternalMessageInfo

func (m *CounterpartyInfo) GetMerklePrefix() [][]byte { _ = "STUB: not implemented"; return nil }

func (m *CounterpartyInfo) GetClientId() string { _ = "STUB: not implemented"; return "" }

func init() {
	proto.RegisterType((*CounterpartyInfo)(nil), "ibc.core.client.v2.CounterpartyInfo")
}

func init() {
	proto.RegisterFile("ibc/core/client/v2/counterparty.proto", fileDescriptor_bc4a81c3d2196cf1)
}

var fileDescriptor_bc4a81c3d2196cf1 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcd, 0x4c, 0x4a, 0xd6,
	0x4f, 0xce, 0x2f, 0x4a, 0xd5, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0xd1, 0x2f, 0x33, 0xd2, 0x4f,
	0xce, 0x2f, 0xcd, 0x2b, 0x49, 0x2d, 0x2a, 0x48, 0x2c, 0x2a, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0xca, 0x4c, 0x4a, 0xd6, 0x03, 0x29, 0xd3, 0x83, 0x28, 0xd3, 0x2b, 0x33, 0x52,
	0x0a, 0xe1, 0x12, 0x70, 0x46, 0x52, 0xe9, 0x99, 0x97, 0x96, 0x2f, 0xa4, 0xcc, 0xc5, 0x9b, 0x9b,
	0x5a, 0x94, 0x9d, 0x93, 0x1a, 0x5f, 0x50, 0x94, 0x9a, 0x96, 0x59, 0x21, 0xc1, 0xa8, 0xc0, 0xac,
	0xc1, 0x13, 0xc4, 0x03, 0x11, 0x0c, 0x00, 0x8b, 0x09, 0x49, 0x73, 0x71, 0x42, 0x4c, 0x89, 0xcf,
	0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x80, 0x08, 0x78, 0xa6, 0x38, 0x85, 0x9d,
	0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31,
	0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x4d, 0x7a, 0x66, 0x49, 0x46, 0x69,
	0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x72, 0x7e, 0x71, 0x6e, 0x7e, 0xb1, 0x7e, 0x66, 0x52, 0xb2,
	0x6e, 0x7a, 0xbe, 0x7e, 0x99, 0xa1, 0xa1, 0x7e, 0x6e, 0x7e, 0x4a, 0x69, 0x4e, 0x6a, 0x31, 0xc4,
	0x2f, 0x06, 0x46, 0xba, 0x08, 0xef, 0x94, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0x3d, 0x62,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x87, 0xc3, 0xd2, 0x97, 0xf1, 0x00, 0x00, 0x00,
}

func (m *CounterpartyInfo) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CounterpartyInfo) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CounterpartyInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintCounterparty(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *CounterpartyInfo) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovCounterparty(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozCounterparty(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CounterpartyInfo) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipCounterparty(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthCounterparty        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCounterparty          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCounterparty = fmt.Errorf("proto: unexpected end of group")
)
