// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/tendermint/v1/tendermint.proto

package tendermint

import (
	fmt "fmt"
	math "math"
	time "time"

	github_com_cometbft_cometbft_libs_bytes "github.com/cometbft/cometbft/libs/bytes"
	types2 "github.com/cometbft/cometbft/proto/tendermint/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
	types1 "github.com/cosmos/ibc-go/v11/modules/core/23-commitment/types"
	_go "github.com/cosmos/ics23/go"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientState from Tendermint tracks the current validator set, latest height,
// and a possible frozen height.
type ClientState struct {
	ChainId    string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TrustLevel Fraction `protobuf:"bytes,2,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level"`
	// duration of the period since the LatestTimestamp during which the
	// submitted headers are valid for upgrade
	TrustingPeriod time.Duration `protobuf:"bytes,3,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	// duration of the staking unbonding period
	UnbondingPeriod time.Duration `protobuf:"bytes,4,opt,name=unbonding_period,json=unbondingPeriod,proto3,stdduration" json:"unbonding_period"`
	// defines how much new (untrusted) header's Time can drift into the future.
	MaxClockDrift time.Duration `protobuf:"bytes,5,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	// Block height when the client was frozen due to a misbehaviour
	FrozenHeight types.Height `protobuf:"bytes,6,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height"`
	// Latest height the client was updated to
	LatestHeight types.Height `protobuf:"bytes,7,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height"`
	// Proof specifications used in verifying counterparty state
	ProofSpecs []*_go.ProofSpec `protobuf:"bytes,8,rep,name=proof_specs,json=proofSpecs,proto3" json:"proof_specs,omitempty"`
	// Path at which next upgraded client will be committed.
	// Each element corresponds to the key for a single CommitmentProof in the
	// chained proof. NOTE: ClientState must stored under
	// `{upgradePath}/{upgradeHeight}/clientState` ConsensusState must be stored
	// under `{upgradepath}/{upgradeHeight}/consensusState` For SDK chains using
	// the default upgrade module, upgrade_path should be []string{"upgrade",
	// "upgradedIBCState"}`
	UpgradePath []string `protobuf:"bytes,9,rep,name=upgrade_path,json=upgradePath,proto3" json:"upgrade_path,omitempty"`
	// allow_update_after_expiry is deprecated
	AllowUpdateAfterExpiry bool `protobuf:"varint,10,opt,name=allow_update_after_expiry,json=allowUpdateAfterExpiry,proto3" json:"allow_update_after_expiry,omitempty"` // Deprecated: Do not use.
	// allow_update_after_misbehaviour is deprecated
	AllowUpdateAfterMisbehaviour bool `protobuf:"varint,11,opt,name=allow_update_after_misbehaviour,json=allowUpdateAfterMisbehaviour,proto3" json:"allow_update_after_misbehaviour,omitempty"` // Deprecated: Do not use.
}

func (m *ClientState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// ConsensusState defines the consensus state from Tendermint.
type ConsensusState struct {
	// timestamp that corresponds to the block height in which the ConsensusState
	// was stored.
	Timestamp time.Time `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	// commitment root (i.e app hash)
	Root               types1.MerkleRoot                                `protobuf:"bytes,2,opt,name=root,proto3" json:"root"`
	NextValidatorsHash github_com_cometbft_cometbft_libs_bytes.HexBytes `protobuf:"bytes,3,opt,name=next_validators_hash,json=nextValidatorsHash,proto3,casttype=github.com/cometbft/cometbft/libs/bytes.HexBytes" json:"next_validators_hash,omitempty"`
}

func (m *ConsensusState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConsensusState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConsensusState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConsensusState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConsensusState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// Misbehaviour is a wrapper over two conflicting Headers
// that implements Misbehaviour interface expected by ICS-02
type Misbehaviour struct {
	// ClientID is deprecated
	ClientId string  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Deprecated: Do not use.
	Header1  *Header `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header2  *Header `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
}

func (m *Misbehaviour) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Misbehaviour) String() string            { _ = "STUB: not implemented"; return "" }
func (*Misbehaviour) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Misbehaviour) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Misbehaviour) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Misbehaviour) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Misbehaviour) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Misbehaviour) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

// Header defines the Tendermint client consensus Header.
// It encapsulates all the information necessary to update from a trusted
// Tendermint ConsensusState. The inclusion of TrustedHeight and
// TrustedValidators allows this update to process correctly, so long as the
// ConsensusState for the TrustedHeight exists, this removes race conditions
// among relayers The SignedHeader and ValidatorSet are the new untrusted update
// fields for the client. The TrustedHeight is the height of a stored
// ConsensusState on the client that will be used to verify the new untrusted
// header. The Trusted ConsensusState must be within the unbonding period of
// current time in order to correctly verify, and the TrustedValidators must
// hash to TrustedConsensusState.NextValidatorsHash since that is the last
// trusted validator set at the TrustedHeight.
type Header struct {
	*types2.SignedHeader `protobuf:"bytes,1,opt,name=signed_header,json=signedHeader,proto3,embedded=signed_header" json:"signed_header,omitempty"`
	ValidatorSet         *types2.ValidatorSet `protobuf:"bytes,2,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	TrustedHeight        types.Height         `protobuf:"bytes,3,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height"`
	TrustedValidators    *types2.ValidatorSet `protobuf:"bytes,4,opt,name=trusted_validators,json=trustedValidators,proto3" json:"trusted_validators,omitempty"`
}

func (m *Header) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Header) String() string            { _ = "STUB: not implemented"; return "" }
func (*Header) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Header) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Header) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Header) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Header) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetValidatorSet() *types2.ValidatorSet { _ = "STUB: not implemented"; return nil }

func (m *Header) GetTrustedHeight() types.Height {
	_ = "STUB: not implemented"
	return *new(types.Height)
}

func (m *Header) GetTrustedValidators() *types2.ValidatorSet { _ = "STUB: not implemented"; return nil }

// Fraction defines the protobuf message type for tmmath.Fraction that only
// supports positive values.
type Fraction struct {
	Numerator   uint64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator uint64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Fraction) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Fraction) String() string            { _ = "STUB: not implemented"; return "" }
func (*Fraction) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Fraction) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Fraction) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Fraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Fraction) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Fraction) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Fraction) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Fraction proto.InternalMessageInfo

func (m *Fraction) GetNumerator() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *Fraction) GetDenominator() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.tendermint.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.tendermint.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.tendermint.v1.Misbehaviour")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.tendermint.v1.Header")
	proto.RegisterType((*Fraction)(nil), "ibc.lightclients.tendermint.v1.Fraction")
}

func init() {
	proto.RegisterFile("ibc/lightclients/tendermint/v1/tendermint.proto", fileDescriptor_c6d6cf2b288949be)
}

var fileDescriptor_c6d6cf2b288949be = []byte{
	// 942 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe3, 0x34, 0xdb, 0x26, 0x93, 0x64, 0x0b, 0xa3, 0x15, 0x72, 0xab, 0x2a, 0x09, 0x3d,
	0x40, 0x2e, 0xb5, 0x37, 0x59, 0x24, 0x24, 0x16, 0x0e, 0xa4, 0xbb, 0xd0, 0xb2, 0x5b, 0xa8, 0x5c,
	0xe0, 0xc0, 0xc5, 0x1a, 0xdb, 0x13, 0x7b, 0xb4, 0xb6, 0xc7, 0x9a, 0x19, 0x87, 0x94, 0x13, 0x47,
	0x8e, 0x7b, 0xe4, 0xc8, 0x47, 0xe0, 0x63, 0xec, 0xb1, 0x17, 0x24, 0x4e, 0x05, 0xa5, 0xdf, 0x82,
	0x13, 0x9a, 0x17, 0x27, 0xa6, 0xac, 0xd8, 0x8a, 0x4b, 0xf4, 0xcc, 0x3c, 0xff, 0xe7, 0x97, 0x99,
	0xe7, 0x65, 0x0c, 0x5c, 0x12, 0x84, 0x6e, 0x4a, 0xe2, 0x44, 0x84, 0x29, 0xc1, 0xb9, 0xe0, 0xae,
	0xc0, 0x79, 0x84, 0x59, 0x46, 0x72, 0xe1, 0x2e, 0x26, 0xb5, 0x95, 0x53, 0x30, 0x2a, 0x28, 0x1c,
	0x90, 0x20, 0x74, 0xea, 0x01, 0x4e, 0x4d, 0xb2, 0x98, 0xec, 0x8f, 0x6a, 0xf1, 0xe2, 0xb2, 0xc0,
	0xdc, 0x5d, 0xa0, 0x94, 0x44, 0x48, 0x50, 0xa6, 0x09, 0xfb, 0x07, 0xff, 0x52, 0xa8, 0xdf, 0xca,
	0x1b, 0x52, 0x9e, 0x51, 0xee, 0x92, 0x90, 0x4f, 0x1f, 0xc9, 0x13, 0x14, 0x8c, 0xd2, 0x79, 0xe5,
	0x1d, 0xc4, 0x94, 0xc6, 0x29, 0x76, 0xd5, 0x2a, 0x28, 0xe7, 0x6e, 0x54, 0x32, 0x24, 0x08, 0xcd,
	0x8d, 0x7f, 0x78, 0xdb, 0x2f, 0x48, 0x86, 0xb9, 0x40, 0x59, 0x51, 0x09, 0xe4, 0x7d, 0x43, 0xca,
	0xb0, 0xab, 0x8f, 0x2f, 0xff, 0x41, 0x5b, 0x46, 0xf0, 0xfe, 0x46, 0x40, 0xb3, 0x8c, 0x88, 0xac,
	0x12, 0xad, 0x57, 0x46, 0xf8, 0x20, 0xa6, 0x31, 0x55, 0xa6, 0x2b, 0x2d, 0xbd, 0x7b, 0xb8, 0xba,
	0x07, 0xba, 0xc7, 0x8a, 0x77, 0x21, 0x90, 0xc0, 0x70, 0x0f, 0xb4, 0xc3, 0x04, 0x91, 0xdc, 0x27,
	0x91, 0x6d, 0x8d, 0xac, 0x71, 0xc7, 0xdb, 0x51, 0xeb, 0xd3, 0x08, 0x7e, 0x05, 0xba, 0x82, 0x95,
	0x5c, 0xf8, 0x29, 0x5e, 0xe0, 0xd4, 0x6e, 0x8e, 0xac, 0x71, 0x77, 0x3a, 0x76, 0xfe, 0x3b, 0xbf,
	0xce, 0x67, 0x0c, 0x85, 0xf2, 0xc2, 0xb3, 0xd6, 0xab, 0xeb, 0x61, 0xc3, 0x03, 0x0a, 0xf1, 0x5c,
	0x12, 0xe0, 0x73, 0xb0, 0xab, 0x56, 0x24, 0x8f, 0xfd, 0x02, 0x33, 0x42, 0x23, 0x7b, 0x4b, 0x41,
	0xf7, 0x1c, 0x9d, 0x16, 0xa7, 0x4a, 0x8b, 0xf3, 0xc4, 0xa4, 0x6d, 0xd6, 0x96, 0x94, 0x9f, 0xff,
	0x18, 0x5a, 0xde, 0xfd, 0x2a, 0xf6, 0x5c, 0x85, 0xc2, 0x2f, 0xc1, 0x5b, 0x65, 0x1e, 0xd0, 0x3c,
	0xaa, 0xe1, 0x5a, 0x77, 0xc7, 0xed, 0xae, 0x83, 0x0d, 0xef, 0x19, 0xd8, 0xcd, 0xd0, 0xd2, 0x0f,
	0x53, 0x1a, 0xbe, 0xf0, 0x23, 0x46, 0xe6, 0xc2, 0xbe, 0x77, 0x77, 0x5c, 0x3f, 0x43, 0xcb, 0x63,
	0x19, 0xfa, 0x44, 0x46, 0xc2, 0xa7, 0xa0, 0x3f, 0x67, 0xf4, 0x07, 0x9c, 0xfb, 0x09, 0x96, 0xb9,
	0xb2, 0xb7, 0x15, 0x6a, 0x5f, 0x65, 0x4f, 0x56, 0xcf, 0x31, 0x45, 0x5d, 0x4c, 0x9c, 0x13, 0xa5,
	0x30, 0xf9, 0xea, 0xe9, 0x30, 0xbd, 0x27, 0x31, 0x29, 0x12, 0x98, 0x8b, 0x0a, 0xb3, 0x73, 0x57,
	0x8c, 0x0e, 0x33, 0x98, 0xc7, 0xa0, 0xab, 0xba, 0xd4, 0xe7, 0x05, 0x0e, 0xb9, 0xdd, 0x1e, 0x6d,
	0x29, 0x88, 0xee, 0x64, 0x47, 0x75, 0xb2, 0x24, 0x9c, 0x4b, 0xcd, 0x45, 0x81, 0x43, 0x0f, 0x14,
	0x95, 0xc9, 0xe1, 0xbb, 0xa0, 0x57, 0x16, 0x31, 0x43, 0x11, 0xf6, 0x0b, 0x24, 0x12, 0xbb, 0x33,
	0xda, 0x1a, 0x77, 0xbc, 0xae, 0xd9, 0x3b, 0x47, 0x22, 0x81, 0x9f, 0x80, 0x3d, 0x94, 0xa6, 0xf4,
	0x7b, 0xbf, 0x2c, 0x22, 0x24, 0xb0, 0x8f, 0xe6, 0x02, 0x33, 0x1f, 0x2f, 0x0b, 0xc2, 0x2e, 0x6d,
	0x30, 0xb2, 0xc6, 0xed, 0x59, 0xd3, 0xb6, 0xbc, 0x77, 0x94, 0xe8, 0x1b, 0xa5, 0xf9, 0x54, 0x4a,
	0x9e, 0x2a, 0x05, 0x3c, 0x05, 0xc3, 0xd7, 0x84, 0x67, 0x84, 0x07, 0x38, 0x41, 0x0b, 0x42, 0x4b,
	0x66, 0x77, 0xd7, 0x90, 0x83, 0xdb, 0x90, 0xb3, 0x9a, 0xee, 0xa3, 0xd6, 0x4f, 0xbf, 0x0c, 0x1b,
	0x87, 0x3f, 0x36, 0xc1, 0xfd, 0x63, 0x9a, 0x73, 0x9c, 0xf3, 0x92, 0xeb, 0x3e, 0x9f, 0x81, 0xce,
	0x7a, 0xd4, 0x54, 0xa3, 0xcb, 0x04, 0xdc, 0xae, 0xeb, 0xd7, 0x95, 0x42, 0x17, 0xf6, 0xa5, 0x2c,
	0xec, 0x26, 0x0c, 0x7e, 0x0c, 0x5a, 0x8c, 0x52, 0x61, 0x26, 0xe1, 0xb0, 0x56, 0x84, 0xcd, 0xec,
	0x2d, 0x26, 0xce, 0x19, 0x66, 0x2f, 0x52, 0xec, 0x51, 0x5a, 0x15, 0x43, 0x45, 0xc1, 0x39, 0x78,
	0x90, 0xe3, 0xa5, 0xf0, 0xd7, 0xcf, 0x0d, 0xf7, 0x13, 0xc4, 0x13, 0x35, 0x02, 0xbd, 0xd9, 0x07,
	0x7f, 0x5d, 0x0f, 0x1f, 0xc6, 0x44, 0x24, 0x65, 0x20, 0x71, 0x72, 0x9c, 0xb1, 0x08, 0xe6, 0x62,
	0x63, 0xa4, 0x24, 0xe0, 0x6e, 0x70, 0x29, 0x30, 0x77, 0x4e, 0xf0, 0x72, 0x26, 0x0d, 0x0f, 0x4a,
	0xe2, 0xb7, 0x6b, 0xe0, 0x09, 0xe2, 0x89, 0x49, 0xc1, 0x6f, 0x16, 0xe8, 0xd5, 0x33, 0x03, 0x87,
	0xa0, 0xa3, 0x7b, 0x65, 0x3d, 0xe9, 0x2a, 0x9d, 0x6d, 0xbd, 0x79, 0x2a, 0xe7, 0xa9, 0x9d, 0x60,
	0x14, 0x61, 0xe6, 0x4f, 0xcc, 0x0d, 0xdf, 0x7b, 0xd3, 0xac, 0x9f, 0x28, 0xfd, 0xac, 0xbb, 0xba,
	0x1e, 0xee, 0x68, 0x7b, 0xe2, 0xed, 0x68, 0xc8, 0xa4, 0xc6, 0x9b, 0x9a, 0x31, 0xff, 0x1f, 0xbc,
	0x69, 0xc5, 0x9b, 0x9a, 0x7b, 0xfd, 0xda, 0x04, 0xdb, 0xda, 0x05, 0x4f, 0x41, 0x9f, 0x93, 0x38,
	0xc7, 0x91, 0xaf, 0x25, 0xa6, 0xac, 0x83, 0x3a, 0x54, 0xbf, 0xdc, 0x17, 0x4a, 0x66, 0xe8, 0xad,
	0xab, 0xeb, 0xa1, 0xe5, 0xf5, 0x78, 0x6d, 0x0f, 0x1e, 0x83, 0xfe, 0xba, 0x2c, 0x3e, 0xc7, 0x55,
	0x89, 0x5f, 0x83, 0x5a, 0x27, 0xfb, 0x02, 0x0b, 0xaf, 0xb7, 0xa8, 0xad, 0xe0, 0xe7, 0x40, 0x3f,
	0x51, 0xea, 0x40, 0x6a, 0x5a, 0xb7, 0xee, 0x38, 0xad, 0x7d, 0x13, 0x67, 0xc6, 0xf5, 0x0c, 0xc0,
	0x0a, 0xb4, 0x69, 0x16, 0xf3, 0xb6, 0xbd, 0xe9, 0x48, 0x6f, 0x9b, 0xc8, 0x4d, 0x53, 0x1c, 0x7e,
	0x01, 0xda, 0xd5, 0xa3, 0x0c, 0x0f, 0x40, 0x27, 0x2f, 0x33, 0xcc, 0xa4, 0x47, 0xe5, 0xab, 0xe5,
	0x6d, 0x36, 0xe0, 0x08, 0x74, 0x23, 0x9c, 0xd3, 0x8c, 0xe4, 0xca, 0xdf, 0x54, 0xfe, 0xfa, 0xd6,
	0x0c, 0xbf, 0x5a, 0x0d, 0xac, 0xab, 0xd5, 0xc0, 0xfa, 0x73, 0x35, 0xb0, 0x5e, 0xde, 0x0c, 0x1a,
	0x57, 0x37, 0x83, 0xc6, 0xef, 0x37, 0x83, 0xc6, 0x77, 0xcf, 0xfe, 0xd1, 0xbc, 0xfa, 0x13, 0x19,
	0x84, 0x47, 0x31, 0x75, 0x17, 0x93, 0x89, 0x9b, 0xd1, 0xa8, 0x4c, 0x31, 0xd7, 0x5f, 0xf2, 0xa3,
	0xea, 0x53, 0xfe, 0xf0, 0xc3, 0xa3, 0xcd, 0x6d, 0x1e, 0x6f, 0xcc, 0x60, 0x5b, 0x8d, 0xe4, 0xa3,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xef, 0x7b, 0xd9, 0x79, 0xfe, 0x07, 0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Fraction) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Fraction) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Fraction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTendermint(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *ClientState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Misbehaviour) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Header) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Fraction) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTendermint(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTendermint(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Misbehaviour) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Fraction) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipTendermint(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTendermint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTendermint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTendermint = fmt.Errorf("proto: unexpected end of group")
)
