// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/packet_forward_middleware/v1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the packetforward genesis state
type GenesisState struct {
	// key - information about forwarded packet: src_channel
	// (parsedReceiver.Channel), src_port (parsedReceiver.Port), sequence value -
	// information about original packet for refunding if necessary: retries,
	// srcPacketSender, srcPacket.DestinationChannel, srcPacket.DestinationPort
	InFlightPackets map[string]InFlightPacket `protobuf:"bytes,2,rep,name=in_flight_packets,json=inFlightPackets,proto3" json:"in_flight_packets" yaml:"in_flight_packets" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetInFlightPackets() map[string]InFlightPacket {
	_ = "STUB: not implemented"
	return nil
}

// InFlightPacket contains information about original packet for
// writing the acknowledgement and refunding if necessary.
type InFlightPacket struct {
	OriginalSenderAddress  string `protobuf:"bytes,1,opt,name=original_sender_address,json=originalSenderAddress,proto3" json:"original_sender_address,omitempty"`
	RefundChannelId        string `protobuf:"bytes,2,opt,name=refund_channel_id,json=refundChannelId,proto3" json:"refund_channel_id,omitempty"`
	RefundPortId           string `protobuf:"bytes,3,opt,name=refund_port_id,json=refundPortId,proto3" json:"refund_port_id,omitempty"`
	PacketSrcChannelId     string `protobuf:"bytes,4,opt,name=packet_src_channel_id,json=packetSrcChannelId,proto3" json:"packet_src_channel_id,omitempty"`
	PacketSrcPortId        string `protobuf:"bytes,5,opt,name=packet_src_port_id,json=packetSrcPortId,proto3" json:"packet_src_port_id,omitempty"`
	PacketTimeoutTimestamp uint64 `protobuf:"varint,6,opt,name=packet_timeout_timestamp,json=packetTimeoutTimestamp,proto3" json:"packet_timeout_timestamp,omitempty"`
	PacketTimeoutHeight    string `protobuf:"bytes,7,opt,name=packet_timeout_height,json=packetTimeoutHeight,proto3" json:"packet_timeout_height,omitempty"`
	PacketData             []byte `protobuf:"bytes,8,opt,name=packet_data,json=packetData,proto3" json:"packet_data,omitempty"`
	RefundSequence         uint64 `protobuf:"varint,9,opt,name=refund_sequence,json=refundSequence,proto3" json:"refund_sequence,omitempty"`
	RetriesRemaining       int32  `protobuf:"varint,10,opt,name=retries_remaining,json=retriesRemaining,proto3" json:"retries_remaining,omitempty"`
	Timeout                uint64 `protobuf:"varint,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (m *InFlightPacket) Reset()                    { _ = "STUB: not implemented"; return }
func (m *InFlightPacket) String() string            { _ = "STUB: not implemented"; return "" }
func (*InFlightPacket) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*InFlightPacket) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *InFlightPacket) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InFlightPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InFlightPacket) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *InFlightPacket) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *InFlightPacket) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_InFlightPacket proto.InternalMessageInfo

func (m *InFlightPacket) GetOriginalSenderAddress() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetRefundChannelId() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetRefundPortId() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetPacketSrcChannelId() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetPacketSrcPortId() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetPacketTimeoutTimestamp() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *InFlightPacket) GetPacketTimeoutHeight() string { _ = "STUB: not implemented"; return "" }

func (m *InFlightPacket) GetPacketData() []byte { _ = "STUB: not implemented"; return nil }

func (m *InFlightPacket) GetRefundSequence() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *InFlightPacket) GetRetriesRemaining() int32 { _ = "STUB: not implemented"; return 0 }

func (m *InFlightPacket) GetTimeout() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterType((*GenesisState)(nil), "ibc.applications.packet_forward_middleware.v1.GenesisState")
	proto.RegisterMapType((map[string]InFlightPacket)(nil), "ibc.applications.packet_forward_middleware.v1.GenesisState.InFlightPacketsEntry")
	proto.RegisterType((*InFlightPacket)(nil), "ibc.applications.packet_forward_middleware.v1.InFlightPacket")
}

func init() {
	proto.RegisterFile("ibc/applications/packet_forward_middleware/v1/genesis.proto", fileDescriptor_421a822166afb238)
}

var fileDescriptor_421a822166afb238 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x86, 0x33, 0x49, 0xaf, 0x4e, 0xe8, 0xc5, 0xb4, 0x60, 0x75, 0x91, 0x8e, 0x22, 0x24, 0x22,
	0xaa, 0xcc, 0x28, 0x45, 0x42, 0x55, 0x11, 0x0b, 0xca, 0x35, 0xac, 0xaa, 0x49, 0x57, 0x6c, 0x46,
	0x8e, 0xed, 0x4e, 0xac, 0xce, 0xd8, 0x83, 0xed, 0xa4, 0xca, 0x92, 0x37, 0xe0, 0x09, 0x78, 0x09,
	0x5e, 0xa2, 0xcb, 0x2e, 0x59, 0x55, 0xa8, 0x7d, 0x03, 0x5e, 0x00, 0x94, 0xb1, 0xa7, 0x24, 0x02,
	0x16, 0x5d, 0xc5, 0x39, 0xff, 0xf9, 0xbf, 0xf3, 0xe7, 0x28, 0x07, 0x3c, 0xe7, 0x03, 0x12, 0xe2,
	0x3c, 0x4f, 0x39, 0xc1, 0x86, 0x4b, 0xa1, 0xc3, 0x1c, 0x93, 0x33, 0x66, 0xe2, 0x53, 0xa9, 0xce,
	0xb1, 0xa2, 0x71, 0xc6, 0x29, 0x4d, 0xd9, 0x39, 0x56, 0x2c, 0x1c, 0x77, 0xc3, 0x84, 0x09, 0xa6,
	0xb9, 0x0e, 0x72, 0x25, 0x8d, 0x84, 0x1d, 0x3e, 0x20, 0xc1, 0xac, 0x39, 0xf8, 0xaf, 0x39, 0x18,
	0x77, 0x77, 0xb6, 0x12, 0x99, 0xc8, 0xc2, 0x19, 0x4e, 0x5f, 0x16, 0xd2, 0xfa, 0x56, 0x05, 0x8d,
	0x77, 0x16, 0xdb, 0x37, 0xd8, 0x30, 0xf8, 0xd5, 0x03, 0x9b, 0x5c, 0xc4, 0xa7, 0x29, 0x4f, 0x86,
	0x26, 0xb6, 0x44, 0x8d, 0xaa, 0x7e, 0xad, 0x5d, 0xdf, 0x3f, 0x0e, 0xee, 0x34, 0x32, 0x98, 0x05,
	0x07, 0x3d, 0xf1, 0xb6, 0x60, 0x1e, 0x5b, 0xe4, 0x1b, 0x61, 0xd4, 0xe4, 0xc8, 0xbf, 0xb8, 0xda,
	0xad, 0xfc, 0xbc, 0xda, 0x45, 0x13, 0x9c, 0xa5, 0x87, 0xad, 0xbf, 0x06, 0xb7, 0xa2, 0x75, 0x3e,
	0xef, 0xdb, 0xf9, 0xec, 0x81, 0xad, 0x7f, 0xb1, 0xe0, 0x06, 0xa8, 0x9d, 0xb1, 0x09, 0xf2, 0x7c,
	0xaf, 0xbd, 0x1a, 0x4d, 0x9f, 0xb0, 0x0f, 0x16, 0xc7, 0x38, 0x1d, 0x31, 0x54, 0xf5, 0xbd, 0x76,
	0x7d, 0xff, 0xc5, 0x1d, 0xe3, 0xcf, 0x4f, 0x89, 0x2c, 0xeb, 0xb0, 0x7a, 0xe0, 0xb5, 0x7e, 0xd5,
	0xc0, 0xda, 0xbc, 0x0a, 0x9f, 0x81, 0x87, 0x52, 0xf1, 0x84, 0x0b, 0x9c, 0xc6, 0x9a, 0x09, 0xca,
	0x54, 0x8c, 0x29, 0x55, 0x4c, 0x6b, 0x97, 0x68, 0xbb, 0x94, 0xfb, 0x85, 0xfa, 0xd2, 0x8a, 0xf0,
	0x09, 0xd8, 0x54, 0xec, 0x74, 0x24, 0x68, 0x4c, 0x86, 0x58, 0x08, 0x96, 0xc6, 0x9c, 0x16, 0x79,
	0x57, 0xa3, 0x75, 0x2b, 0xbc, 0xb2, 0xf5, 0x1e, 0x85, 0x8f, 0xc0, 0x9a, 0xeb, 0xcd, 0xa5, 0x32,
	0xd3, 0xc6, 0x5a, 0xd1, 0xd8, 0xb0, 0xd5, 0x63, 0xa9, 0x4c, 0x8f, 0xc2, 0x2e, 0xd8, 0x76, 0x3f,
	0x4b, 0x2b, 0x32, 0x4b, 0x5d, 0x28, 0x9a, 0xa1, 0x15, 0xfb, 0x8a, 0xfc, 0x01, 0xef, 0x01, 0x38,
	0x63, 0x29, 0xe1, 0x8b, 0x36, 0xc5, 0x6d, 0xbf, 0xe3, 0x1f, 0x00, 0xe4, 0x9a, 0x0d, 0xcf, 0x98,
	0x1c, 0xd9, 0x4f, 0x6d, 0x70, 0x96, 0xa3, 0x25, 0xdf, 0x6b, 0x2f, 0x44, 0x0f, 0xac, 0x7e, 0x62,
	0xe5, 0x93, 0x52, 0x85, 0xfb, 0xb7, 0xc9, 0x4a, 0xe7, 0x90, 0x4d, 0x57, 0x88, 0x96, 0x8b, 0x49,
	0xf7, 0xe7, 0x6c, 0xef, 0x0b, 0x09, 0xee, 0x82, 0xba, 0xf3, 0x50, 0x6c, 0x30, 0x5a, 0xf1, 0xbd,
	0x76, 0x23, 0x02, 0xb6, 0xf4, 0x1a, 0x1b, 0x0c, 0x1f, 0x03, 0xb7, 0xa7, 0x58, 0xb3, 0x4f, 0x23,
	0x26, 0x08, 0x43, 0xab, 0x45, 0x0a, 0xb7, 0xab, 0xbe, 0xab, 0xc2, 0xbd, 0xe9, 0xa6, 0x8d, 0xe2,
	0x4c, 0xc7, 0x8a, 0x65, 0x98, 0x0b, 0x2e, 0x12, 0x04, 0x7c, 0xaf, 0xbd, 0x18, 0x6d, 0x38, 0x21,
	0x2a, 0xeb, 0x10, 0x81, 0x65, 0x97, 0x11, 0xd5, 0x0b, 0x5a, 0xf9, 0xf5, 0xc3, 0xc2, 0x4a, 0x63,
	0xe3, 0xde, 0x11, 0xb9, 0xb8, 0x6e, 0x7a, 0x97, 0xd7, 0x4d, 0xef, 0xc7, 0x75, 0xd3, 0xfb, 0x72,
	0xd3, 0xac, 0x5c, 0xde, 0x34, 0x2b, 0xdf, 0x6f, 0x9a, 0x95, 0x8f, 0xbd, 0x84, 0x9b, 0xe1, 0x68,
	0x10, 0x10, 0x99, 0x85, 0x44, 0xea, 0x4c, 0xea, 0x90, 0x0f, 0x48, 0x27, 0x91, 0xe1, 0xb8, 0xdb,
	0x0d, 0x33, 0x49, 0x47, 0x29, 0xd3, 0xd3, 0xa3, 0x2f, 0x8f, 0xbd, 0xe3, 0xfe, 0x7d, 0x9d, 0x99,
	0x63, 0x37, 0x93, 0x9c, 0xe9, 0xc1, 0x52, 0x71, 0xa3, 0x4f, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x60, 0x06, 0x08, 0x57, 0x27, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InFlightPacket) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *InFlightPacket) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *InFlightPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *InFlightPacket) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *InFlightPacket) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
