package keeper

import (
	wasmvm "github.com/CosmWasm/wasmvm/v3"

	"cosmossdk.io/collections"
	"cosmossdk.io/core/store"
	"cosmossdk.io/log/v2"

	"github.com/cosmos/cosmos-sdk/codec"
	sdk "github.com/cosmos/cosmos-sdk/types"

	"github.com/cosmos/ibc-go/modules/light-clients/08-wasm/v11/types"
)

// Keeper defines the 08-wasm keeper
type Keeper struct {
	// implements gRPC QueryServer interface
	types.QueryServer

	cdc          codec.BinaryCodec
	clientKeeper types.ClientKeeper

	vm types.WasmEngine

	checksums    collections.KeySet[[]byte]
	storeService store.KVStoreService

	queryPlugins QueryPlugins

	authority string
}

// Codec returns the 08-wasm module's codec.
func (k *Keeper) Codec() codec.BinaryCodec {
	_ = "STUB: not implemented"

	// GetAuthority returns the 08-wasm module's authority.
	return *new(codec.BinaryCodec)
}

func (k *Keeper) GetAuthority() string {
	_ = "STUB: not implemented"

	// Logger returns a module-specific logger.
	return ""
}

func (*Keeper) Logger(ctx sdk.Context) log.Logger {
	_ = "STUB: not implemented"
	return *new(log.Logger)
}

func moduleLogger(ctx sdk.Context) log.Logger { _ = "STUB: not implemented"; return *new(log.Logger) }

// GetVM returns the keeper's vm engine.
func (k *Keeper) GetVM() types.WasmEngine {
	_ = "STUB: not implemented"

	// GetChecksums returns the stored checksums.
	return *new(types.WasmEngine)
}

func (k *Keeper) GetChecksums() collections.KeySet[[]byte] {
	_ = "STUB: not implemented"

	// getQueryPlugins returns the set query plugins.
	return nil
}

func (k *Keeper) getQueryPlugins() QueryPlugins {
	_ = "STUB: not implemented"
	return *

	// setQueryPlugins sets the plugins.
	new(QueryPlugins)
}

func (k *Keeper) setQueryPlugins(plugins QueryPlugins) { _ = "STUB: not implemented"; return }

func (k *Keeper) newQueryHandler(ctx sdk.Context, callerID string) *queryHandler {
	_ = "STUB: not implemented"
	return nil
}

// storeWasmCode stores the contract to the VM, pins the checksum in the VM's in memory cache and stores the checksum
// in the 08-wasm store. The checksum identifying it is returned if successful. The following checks are made to the
// contract code before storing:
// - Size bounds are checked. Contract length must not be 0 or exceed a specific size (maxWasmSize).
// - The contract must not have already been stored in store.
func (k *Keeper) storeWasmCode(ctx sdk.Context, code []byte, storeFn func(code wasmvm.WasmCode, gasLimit uint64) (wasmvm.Checksum, uint64, error)) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// run the code through the wasm light client validation process

// Check to see if store already has checksum.

// create the code in the vm

// SANITY: We've checked our store, additional safety check to assert that the checksum returned by WasmVM equals checksum generated by us.

// pin the code to the vm in-memory cache

// store the checksum

// migrateContractCode migrates the contract for a given light client to one denoted by the given new checksum. The checksum we
// are migrating to must first be stored using storeWasmCode and must not match the checksum currently stored for this light client.
func (k *Keeper) migrateContractCode(ctx sdk.Context, clientID string, newChecksum, migrateMsg []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// update the checksum, this needs to be done before the contract migration
// so that wasmMigrate can call the right code. Note that this is not
// persisted to the client store.

// client state may be updated by the contract migration

// note that this also ensures that the updated client state is
// still a wasm client state

// update the client state checksum before persisting it

// GetWasmClientState returns the 08-wasm client state for the given client identifier.
func (k *Keeper) GetWasmClientState(ctx sdk.Context, clientID string) (*types.ClientState, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAllChecksums is a helper to get all checksums from the store.
// It returns an empty slice if no checksums are found
func (k *Keeper) GetAllChecksums(ctx sdk.Context) ([]types.Checksum, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// HasChecksum returns true if the given checksum exists in the store and
// false otherwise.
func (k *Keeper) HasChecksum(ctx sdk.Context, checksum types.Checksum) bool {
	_ = "STUB: not implemented"
	return false
}

// InitializePinnedCodes updates wasmvm to pin to cache all contracts marked as pinned
func (k *Keeper) InitializePinnedCodes(ctx sdk.Context) error {
	_ = "STUB: not implemented"
	return nil
}
