// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/solomachine/v3/solomachine.proto

package solomachine

import (
	fmt "fmt"
	math "math"

	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientState defines a solo machine client that tracks the current consensus
// state and if the client is frozen.
type ClientState struct {
	// latest sequence of the client state
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// frozen sequence of the solo machine
	IsFrozen       bool            `protobuf:"varint,2,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
	ConsensusState *ConsensusState `protobuf:"bytes,3,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
}

func (m *ClientState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// ConsensusState defines a solo machine consensus state. The sequence of a
// consensus state is contained in the "height" key used in storing the
// consensus state.
type ConsensusState struct {
	// public key of the solo machine
	PublicKey *types.Any `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// diversifier allows the same public key to be reused across different solo
	// machine clients (potentially on different chains) without being considered
	// misbehaviour.
	Diversifier string `protobuf:"bytes,2,opt,name=diversifier,proto3" json:"diversifier,omitempty"`
	Timestamp   uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *ConsensusState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConsensusState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConsensusState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConsensusState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConsensusState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// Header defines a solo machine consensus header
type Header struct {
	Timestamp      uint64     `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature      []byte     `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	NewPublicKey   *types.Any `protobuf:"bytes,3,opt,name=new_public_key,json=newPublicKey,proto3" json:"new_public_key,omitempty"`
	NewDiversifier string     `protobuf:"bytes,4,opt,name=new_diversifier,json=newDiversifier,proto3" json:"new_diversifier,omitempty"`
}

func (m *Header) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Header) String() string            { _ = "STUB: not implemented"; return "" }
func (*Header) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Header) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Header) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Header) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Header) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Header proto.InternalMessageInfo

// Misbehaviour defines misbehaviour for a solo machine which consists
// of a sequence and two signatures over different messages at that sequence.
type Misbehaviour struct {
	Sequence     uint64            `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SignatureOne *SignatureAndData `protobuf:"bytes,2,opt,name=signature_one,json=signatureOne,proto3" json:"signature_one,omitempty"`
	SignatureTwo *SignatureAndData `protobuf:"bytes,3,opt,name=signature_two,json=signatureTwo,proto3" json:"signature_two,omitempty"`
}

func (m *Misbehaviour) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Misbehaviour) String() string            { _ = "STUB: not implemented"; return "" }
func (*Misbehaviour) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Misbehaviour) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Misbehaviour) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Misbehaviour) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Misbehaviour) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Misbehaviour) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

// SignatureAndData contains a signature and the data signed over to create that
// signature.
type SignatureAndData struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Path      []byte `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *SignatureAndData) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignatureAndData) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignatureAndData) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignatureAndData) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignatureAndData) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignatureAndData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignatureAndData) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignatureAndData) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignatureAndData) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignatureAndData proto.InternalMessageInfo

// TimestampedSignatureData contains the signature data and the timestamp of the
// signature.
type TimestampedSignatureData struct {
	SignatureData []byte `protobuf:"bytes,1,opt,name=signature_data,json=signatureData,proto3" json:"signature_data,omitempty"`
	Timestamp     uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *TimestampedSignatureData) Reset()         { _ = "STUB: not implemented"; return }
func (m *TimestampedSignatureData) String() string { _ = "STUB: not implemented"; return "" }
func (*TimestampedSignatureData) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*TimestampedSignatureData) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimestampedSignatureData) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *TimestampedSignatureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimestampedSignatureData) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *TimestampedSignatureData) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *TimestampedSignatureData) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_TimestampedSignatureData proto.InternalMessageInfo

// SignBytes defines the signed bytes used for signature verification.
type SignBytes struct {
	// the sequence number
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// the proof timestamp
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// the public key diversifier
	Diversifier string `protobuf:"bytes,3,opt,name=diversifier,proto3" json:"diversifier,omitempty"`
	// the standardised path bytes
	Path []byte `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// the marshaled data bytes
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *SignBytes) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SignBytes) String() string            { _ = "STUB: not implemented"; return "" }
func (*SignBytes) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SignBytes) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignBytes) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignBytes) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SignBytes) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SignBytes) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SignBytes proto.InternalMessageInfo

// HeaderData returns the SignBytes data for update verification.
type HeaderData struct {
	// header public key
	NewPubKey *types.Any `protobuf:"bytes,1,opt,name=new_pub_key,json=newPubKey,proto3" json:"new_pub_key,omitempty"`
	// header diversifier
	NewDiversifier string `protobuf:"bytes,2,opt,name=new_diversifier,json=newDiversifier,proto3" json:"new_diversifier,omitempty"`
}

func (m *HeaderData) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HeaderData) String() string            { _ = "STUB: not implemented"; return "" }
func (*HeaderData) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HeaderData) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HeaderData) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeaderData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HeaderData) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HeaderData) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HeaderData) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HeaderData proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.solomachine.v3.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.solomachine.v3.ConsensusState")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.solomachine.v3.Header")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.solomachine.v3.Misbehaviour")
	proto.RegisterType((*SignatureAndData)(nil), "ibc.lightclients.solomachine.v3.SignatureAndData")
	proto.RegisterType((*TimestampedSignatureData)(nil), "ibc.lightclients.solomachine.v3.TimestampedSignatureData")
	proto.RegisterType((*SignBytes)(nil), "ibc.lightclients.solomachine.v3.SignBytes")
	proto.RegisterType((*HeaderData)(nil), "ibc.lightclients.solomachine.v3.HeaderData")
}

func init() {
	proto.RegisterFile("ibc/lightclients/solomachine/v3/solomachine.proto", fileDescriptor_264187157b9220a4)
}

var fileDescriptor_264187157b9220a4 = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xcf, 0xb5, 0xa6, 0x6a, 0xce, 0x21, 0x45, 0x56, 0x87, 0x50, 0x90, 0x1b, 0x55, 0x42, 0x74,
	0xa9, 0x4d, 0x12, 0xc4, 0x50, 0xa6, 0xb6, 0x11, 0x42, 0x42, 0x15, 0xc8, 0xad, 0x10, 0x62, 0x89,
	0xce, 0xf6, 0xc5, 0x39, 0x61, 0xdf, 0xa5, 0xbe, 0x73, 0xa2, 0x20, 0x3e, 0x00, 0x12, 0x0b, 0x0b,
	0x3b, 0x13, 0x2b, 0x5f, 0x83, 0xb1, 0x23, 0x63, 0x95, 0x7c, 0x11, 0xe4, 0xb3, 0x1d, 0x3b, 0x6e,
	0x9a, 0x0c, 0x6c, 0xef, 0x3d, 0xbf, 0xf7, 0xbb, 0xdf, 0xef, 0xfd, 0x31, 0x6c, 0x11, 0xdb, 0x31,
	0x7d, 0xe2, 0x0d, 0x84, 0xe3, 0x13, 0x4c, 0x05, 0x37, 0x39, 0xf3, 0x59, 0x80, 0x9c, 0x01, 0xa1,
	0xd8, 0x1c, 0x75, 0x8a, 0xae, 0x31, 0x0c, 0x99, 0x60, 0xda, 0x3e, 0xb1, 0x1d, 0xa3, 0x58, 0x62,
	0x14, 0x73, 0x46, 0x9d, 0xbd, 0x5d, 0x8f, 0x79, 0x4c, 0xe6, 0x9a, 0xb1, 0x95, 0x94, 0xed, 0x3d,
	0xf4, 0x18, 0xf3, 0x7c, 0x6c, 0x4a, 0xcf, 0x8e, 0xfa, 0x26, 0xa2, 0x93, 0xe4, 0xd3, 0xc1, 0x2f,
	0x00, 0xd5, 0x33, 0x89, 0x75, 0x21, 0x90, 0xc0, 0xda, 0x1e, 0xdc, 0xe6, 0xf8, 0x2a, 0xc2, 0xd4,
	0xc1, 0x0d, 0xd0, 0x04, 0x87, 0x8a, 0x35, 0xf7, 0xb5, 0x47, 0xb0, 0x4a, 0x78, 0xaf, 0x1f, 0xb2,
	0xcf, 0x98, 0x36, 0x36, 0x9a, 0xe0, 0x70, 0xdb, 0xda, 0x26, 0xfc, 0x95, 0xf4, 0xb5, 0x0f, 0x70,
	0xc7, 0x61, 0x94, 0x63, 0xca, 0x23, 0xde, 0xe3, 0x31, 0x56, 0x63, 0xb3, 0x09, 0x0e, 0xd5, 0xb6,
	0x69, 0xac, 0x21, 0x6d, 0x9c, 0x65, 0x75, 0x92, 0x82, 0x55, 0x77, 0x16, 0xfc, 0x63, 0xe5, 0xeb,
	0xcf, 0xfd, 0xca, 0xc1, 0x37, 0x00, 0xeb, 0x8b, 0x89, 0x5a, 0x07, 0xc2, 0x61, 0x64, 0xfb, 0xc4,
	0xe9, 0x7d, 0xc2, 0x13, 0xc9, 0x56, 0x6d, 0xef, 0x1a, 0x89, 0x56, 0x23, 0xd3, 0x6a, 0x9c, 0xd0,
	0x89, 0x55, 0x4d, 0xf2, 0xde, 0xe0, 0x89, 0xd6, 0x84, 0xaa, 0x4b, 0x46, 0x38, 0xe4, 0xa4, 0x4f,
	0x70, 0x28, 0x65, 0x54, 0xad, 0x62, 0x48, 0x7b, 0x0c, 0xab, 0x82, 0x04, 0x98, 0x0b, 0x14, 0x0c,
	0xa5, 0x06, 0xc5, 0xca, 0x03, 0x29, 0x9b, 0xdf, 0x00, 0x6e, 0xbd, 0xc6, 0xc8, 0x2d, 0xa7, 0x83,
	0x52, 0x7a, 0xfc, 0x95, 0x13, 0x8f, 0x22, 0x11, 0x85, 0x58, 0x3e, 0x56, 0xb3, 0xf2, 0x80, 0x76,
	0x0c, 0xeb, 0x14, 0x8f, 0x7b, 0x05, 0x15, 0x9b, 0x2b, 0x54, 0xd4, 0x28, 0x1e, 0xbf, 0x9b, 0x0b,
	0x79, 0x0a, 0x77, 0xe2, 0xda, 0xa2, 0x18, 0x45, 0x8a, 0x89, 0x21, 0xbb, 0x79, 0x34, 0x65, 0x7c,
	0x03, 0x60, 0xed, 0x9c, 0x70, 0x1b, 0x0f, 0xd0, 0x88, 0xb0, 0x28, 0x5c, 0x39, 0xe9, 0xf7, 0xf0,
	0xfe, 0x9c, 0x64, 0x8f, 0xd1, 0x84, 0xb9, 0xda, 0x6e, 0xad, 0x1d, 0xe5, 0x45, 0x56, 0x75, 0x42,
	0xdd, 0x2e, 0x12, 0xc8, 0xaa, 0xcd, 0x71, 0xde, 0xd2, 0x12, 0xae, 0x18, 0xb3, 0x54, 0xee, 0x7f,
	0xe1, 0x5e, 0x8e, 0x59, 0x2a, 0xf1, 0x0b, 0x7c, 0x50, 0xce, 0x5b, 0xec, 0x3f, 0x28, 0xf7, 0x5f,
	0x83, 0xca, 0x10, 0x89, 0x41, 0x3a, 0x18, 0x69, 0xc7, 0x31, 0x17, 0x09, 0x24, 0xa9, 0xd5, 0x2c,
	0x69, 0x2f, 0xce, 0x58, 0x59, 0xbe, 0x12, 0x18, 0x36, 0x2e, 0xb3, 0x10, 0x76, 0xe7, 0x44, 0x24,
	0x8b, 0x27, 0xb0, 0x9e, 0xeb, 0x96, 0xe8, 0x09, 0x95, 0xbc, 0x1b, 0xdd, 0x5b, 0xcf, 0x6c, 0x2c,
	0x7f, 0xe6, 0x07, 0x80, 0xd5, 0x18, 0xfc, 0x74, 0x22, 0x30, 0x5f, 0x39, 0xc4, 0x95, 0x68, 0xe5,
	0x3b, 0xd8, 0xbc, 0x7d, 0x07, 0x59, 0x73, 0x94, 0x25, 0xcd, 0xb9, 0x97, 0x37, 0x27, 0xe5, 0x75,
	0x05, 0x61, 0x72, 0x10, 0x52, 0xc9, 0x73, 0xa8, 0xa6, 0x8b, 0xbd, 0xfe, 0x36, 0x93, 0xad, 0xbe,
	0x63, 0xa5, 0x37, 0xee, 0x5e, 0xe9, 0x53, 0xef, 0xcf, 0x54, 0x07, 0xd7, 0x53, 0x1d, 0xdc, 0x4c,
	0x75, 0xf0, 0x7d, 0xa6, 0x57, 0xae, 0x67, 0x7a, 0xe5, 0xef, 0x4c, 0xaf, 0x7c, 0x3c, 0xf7, 0x88,
	0x18, 0x44, 0xb6, 0xe1, 0xb0, 0xc0, 0x74, 0x18, 0x0f, 0x18, 0x37, 0x89, 0xed, 0x1c, 0x79, 0xcc,
	0x1c, 0xb5, 0x5a, 0x66, 0xc0, 0xdc, 0xc8, 0xc7, 0x3c, 0xf9, 0xf7, 0x1e, 0x65, 0x3f, 0xdf, 0x67,
	0x2f, 0x8e, 0x0a, 0x4b, 0xf7, 0xb2, 0x60, 0xdb, 0x5b, 0x92, 0x70, 0xe7, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1c, 0xa4, 0x3f, 0xc8, 0xb2, 0x05, 0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Header) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignatureAndData) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SignatureAndData) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignatureAndData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimestampedSignatureData) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *TimestampedSignatureData) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *TimestampedSignatureData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SignBytes) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *SignBytes) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *SignBytes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HeaderData) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *HeaderData) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *HeaderData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintSolomachine(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *ClientState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Header) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Misbehaviour) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignatureAndData) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *TimestampedSignatureData) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SignBytes) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HeaderData) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovSolomachine(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozSolomachine(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Header) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Misbehaviour) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SignatureAndData) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *TimestampedSignatureData) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *SignBytes) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HeaderData) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipSolomachine(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthSolomachine        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSolomachine          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSolomachine = fmt.Errorf("proto: unexpected end of group")
)
