// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/gmp/v1/account.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AccountIdentifier is used to identify a ICS27 account.
type AccountIdentifier struct {
	// The (local) client identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The sender of the packet
	Sender string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// The salt of the packet
	Salt []byte `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (m *AccountIdentifier) Reset()                    { _ = "STUB: not implemented"; return }
func (m *AccountIdentifier) String() string            { _ = "STUB: not implemented"; return "" }
func (*AccountIdentifier) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*AccountIdentifier) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *AccountIdentifier) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *AccountIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AccountIdentifier) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *AccountIdentifier) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *AccountIdentifier) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_AccountIdentifier proto.InternalMessageInfo

func (m *AccountIdentifier) GetClientId() string { _ = "STUB: not implemented"; return "" }

func (m *AccountIdentifier) GetSender() string { _ = "STUB: not implemented"; return "" }

func (m *AccountIdentifier) GetSalt() []byte { _ = "STUB: not implemented"; return nil }

// An ICS27Account is defined as a BaseAccount & the account identifier
type ICS27Account struct {
	Address   string             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AccountId *AccountIdentifier `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (m *ICS27Account) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ICS27Account) String() string            { _ = "STUB: not implemented"; return "" }
func (*ICS27Account) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ICS27Account) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ICS27Account) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ICS27Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ICS27Account) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ICS27Account) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ICS27Account) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ICS27Account proto.InternalMessageInfo

func (m *ICS27Account) GetAddress() string { _ = "STUB: not implemented"; return "" }

func (m *ICS27Account) GetAccountId() *AccountIdentifier { _ = "STUB: not implemented"; return nil }

// CosmosTx contains a list of sdk.Msg's. It should be used when sending transactions to an SDK host chain.
type CosmosTx struct {
	Messages []*types.Any `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (m *CosmosTx) Reset()                    { _ = "STUB: not implemented"; return }
func (m *CosmosTx) String() string            { _ = "STUB: not implemented"; return "" }
func (*CosmosTx) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*CosmosTx) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *CosmosTx) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CosmosTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *CosmosTx) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *CosmosTx) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *CosmosTx) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_CosmosTx proto.InternalMessageInfo

func (m *CosmosTx) GetMessages() []*types.Any { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*AccountIdentifier)(nil), "ibc.applications.gmp.v1.AccountIdentifier")
	proto.RegisterType((*ICS27Account)(nil), "ibc.applications.gmp.v1.ICS27Account")
	proto.RegisterType((*CosmosTx)(nil), "ibc.applications.gmp.v1.CosmosTx")
}

func init() {
	proto.RegisterFile("ibc/applications/gmp/v1/account.proto", fileDescriptor_5d5b886ccdedc1db)
}

var fileDescriptor_5d5b886ccdedc1db = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x6b, 0xdb, 0x30,
	0x18, 0x8d, 0x97, 0x91, 0x25, 0x4a, 0x2e, 0x13, 0x61, 0x73, 0x32, 0x30, 0x21, 0x30, 0x08, 0x83,
	0x48, 0xb3, 0x07, 0xcb, 0x65, 0x97, 0x24, 0x27, 0xdf, 0x86, 0xb3, 0xd3, 0x18, 0x04, 0x59, 0x56,
	0x34, 0x81, 0x2d, 0x19, 0x4b, 0x0e, 0xcd, 0x8f, 0x28, 0xf4, 0xc7, 0xf4, 0x47, 0xf4, 0x18, 0x7a,
	0xea, 0xb1, 0x24, 0x7f, 0xa4, 0xd8, 0x72, 0x4a, 0xa1, 0xf4, 0xe6, 0xf7, 0xbd, 0xe7, 0xef, 0x3d,
	0xbd, 0x0f, 0x7c, 0x15, 0x31, 0xc5, 0x24, 0xcf, 0x53, 0x41, 0x89, 0x11, 0x4a, 0x6a, 0xcc, 0xb3,
	0x1c, 0xef, 0x7d, 0x4c, 0x28, 0x55, 0xa5, 0x34, 0x28, 0x2f, 0x94, 0x51, 0xf0, 0xb3, 0x88, 0x29,
	0x7a, 0x29, 0x43, 0x3c, 0xcb, 0xd1, 0xde, 0x1f, 0x8f, 0xb8, 0x52, 0x3c, 0x65, 0xb8, 0x96, 0xc5,
	0xe5, 0x0e, 0x13, 0x79, 0xb0, 0xff, 0x8c, 0x47, 0x54, 0xe9, 0x4c, 0xe9, 0x6d, 0x8d, 0xb0, 0x05,
	0x96, 0x9a, 0xfe, 0x03, 0x1f, 0x97, 0x76, 0x7f, 0x98, 0x30, 0x69, 0xc4, 0x4e, 0xb0, 0x02, 0x7e,
	0x01, 0x3d, 0x9a, 0x0a, 0x26, 0xcd, 0x56, 0x24, 0xae, 0x33, 0x71, 0x66, 0xbd, 0xa8, 0x6b, 0x07,
	0x61, 0x02, 0x3f, 0x81, 0x8e, 0x66, 0x32, 0x61, 0x85, 0xfb, 0xae, 0x66, 0x1a, 0x04, 0x21, 0x78,
	0xaf, 0x49, 0x6a, 0xdc, 0xf6, 0xc4, 0x99, 0x0d, 0xa2, 0xfa, 0x7b, 0x7a, 0xed, 0x80, 0x41, 0xb8,
	0xde, 0x04, 0x8b, 0xc6, 0x03, 0x06, 0xe0, 0x03, 0x49, 0x92, 0x82, 0x69, 0x6d, 0xf7, 0xae, 0xdc,
	0xfb, 0xdb, 0xf9, 0xb0, 0x49, 0xb4, 0xb4, 0xcc, 0xc6, 0x14, 0x42, 0xf2, 0xe8, 0x22, 0x84, 0x21,
	0x00, 0x4d, 0x05, 0x55, 0x9c, 0xca, 0xb4, 0x1f, 0x7c, 0x43, 0x6f, 0xd4, 0x80, 0x5e, 0xbd, 0x26,
	0xea, 0x91, 0xcb, 0x68, 0xfa, 0x0b, 0x74, 0xd7, 0xb5, 0xd7, 0x9f, 0x2b, 0xf8, 0x1d, 0x74, 0x33,
	0xa6, 0x35, 0xe1, 0xac, 0xca, 0xd2, 0x9e, 0xf5, 0x83, 0x21, 0xb2, 0x15, 0xa2, 0x4b, 0x85, 0x68,
	0x29, 0x0f, 0xd1, 0xb3, 0x6a, 0xf5, 0xfb, 0xee, 0xe4, 0x39, 0xc7, 0x93, 0xe7, 0x3c, 0x9e, 0x3c,
	0xe7, 0xe6, 0xec, 0xb5, 0x8e, 0x67, 0xaf, 0xf5, 0x70, 0xf6, 0x5a, 0x7f, 0x7f, 0x72, 0x61, 0xfe,
	0x97, 0x31, 0xa2, 0x2a, 0x6b, 0xea, 0xc5, 0x22, 0xa6, 0x73, 0xae, 0xf0, 0xde, 0xf7, 0x71, 0xa6,
	0x92, 0x32, 0x65, 0xba, 0x3a, 0xae, 0xc6, 0xc1, 0x62, 0x5e, 0xdd, 0xd5, 0x1c, 0x72, 0xa6, 0xe3,
	0x4e, 0xed, 0xf4, 0xe3, 0x29, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x4f, 0x31, 0xa4, 0xfc, 0x01, 0x00,
	0x00,
}

func (m *AccountIdentifier) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *AccountIdentifier) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *AccountIdentifier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ICS27Account) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ICS27Account) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ICS27Account) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *CosmosTx) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *CosmosTx) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *CosmosTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintAccount(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *AccountIdentifier) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ICS27Account) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *CosmosTx) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovAccount(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozAccount(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *AccountIdentifier) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ICS27Account) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *CosmosTx) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipAccount(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAccount = fmt.Errorf("proto: unexpected end of group")
)
