// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/gmp/v1/genesis.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the 27-gmp genesis state
type GenesisState struct {
	// The list of registered ICS27 accounts
	Ics27Accounts []RegisteredICS27Account `protobuf:"bytes,2,rep,name=ics27_accounts,json=ics27Accounts,proto3" json:"ics27_accounts"`
}

func (m *GenesisState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *GenesisState) String() string            { _ = "STUB: not implemented"; return "" }
func (*GenesisState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*GenesisState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *GenesisState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *GenesisState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetIcs27Accounts() []RegisteredICS27Account {
	_ = "STUB: not implemented"
	return nil
}

// RegisteredICS27Account contains an account identifier and associated interchain account address
type RegisteredICS27Account struct {
	/// The address of the ics27 account
	AccountAddress string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	/// The account identifier
	AccountId AccountIdentifier `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id"`
}

func (m *RegisteredICS27Account) Reset()         { _ = "STUB: not implemented"; return }
func (m *RegisteredICS27Account) String() string { _ = "STUB: not implemented"; return "" }
func (*RegisteredICS27Account) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*RegisteredICS27Account) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredICS27Account) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *RegisteredICS27Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredICS27Account) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *RegisteredICS27Account) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *RegisteredICS27Account) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_RegisteredICS27Account proto.InternalMessageInfo

func (m *RegisteredICS27Account) GetAccountAddress() string { _ = "STUB: not implemented"; return "" }

func (m *RegisteredICS27Account) GetAccountId() AccountIdentifier {
	_ = "STUB: not implemented"
	return *new(AccountIdentifier)
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "ibc.applications.gmp.v1.GenesisState")
	proto.RegisterType((*RegisteredICS27Account)(nil), "ibc.applications.gmp.v1.RegisteredICS27Account")
}

func init() {
	proto.RegisterFile("ibc/applications/gmp/v1/genesis.proto", fileDescriptor_7cccbdb788964d3f)
}

var fileDescriptor_7cccbdb788964d3f = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0x02, 0x41,
	0x14, 0xc6, 0x77, 0x2c, 0x02, 0xc7, 0x32, 0x58, 0xa2, 0xc4, 0xc3, 0x26, 0x42, 0x24, 0x81, 0x33,
	0xec, 0x06, 0x79, 0xd6, 0x0e, 0xe1, 0xa9, 0xd0, 0x5b, 0x04, 0xb2, 0x3b, 0x3b, 0x4d, 0x0f, 0xdc,
	0x9d, 0x61, 0xdf, 0x28, 0xf4, 0x5f, 0x44, 0x7f, 0x95, 0x47, 0x8f, 0x9d, 0x22, 0xf4, 0x1f, 0x09,
	0xdd, 0x11, 0x3a, 0xe4, 0xed, 0xf1, 0xbd, 0xef, 0xf7, 0xbe, 0xc7, 0x47, 0xaf, 0x20, 0x11, 0x3c,
	0x36, 0x66, 0x0a, 0x22, 0xb6, 0xa0, 0x73, 0xe4, 0x2a, 0x33, 0x7c, 0x1e, 0x72, 0x25, 0x73, 0x89,
	0x80, 0xcc, 0x14, 0xda, 0x6a, 0xff, 0x02, 0x12, 0xc1, 0xfe, 0xda, 0x98, 0xca, 0x0c, 0x9b, 0x87,
	0xcd, 0xbd, 0x7c, 0x2c, 0x84, 0x9e, 0xe5, 0xb6, 0xe4, 0x9b, 0x67, 0x4a, 0x2b, 0xbd, 0x1d, 0xf9,
	0x66, 0x2a, 0xd5, 0xf6, 0x94, 0x1e, 0x3f, 0x94, 0x31, 0x63, 0x1b, 0x5b, 0xe9, 0xbf, 0xd0, 0x3a,
	0x08, 0x8c, 0x7a, 0x13, 0x07, 0x63, 0xa3, 0xd2, 0x3a, 0xe8, 0xd4, 0x22, 0xce, 0xf6, 0xc4, 0xb3,
	0x91, 0x54, 0x80, 0x56, 0x16, 0x32, 0x1d, 0xde, 0x8f, 0xa3, 0x5e, 0xbf, 0xe4, 0x06, 0x87, 0x8b,
	0xef, 0x4b, 0x6f, 0x74, 0xb2, 0x3d, 0xe6, 0x34, 0x6c, 0x7f, 0x12, 0x7a, 0xfe, 0xbf, 0xdf, 0xbf,
	0xa6, 0xa7, 0x2e, 0x72, 0x12, 0xa7, 0x69, 0x21, 0x11, 0x1b, 0xa4, 0x45, 0x3a, 0xd5, 0x51, 0xdd,
	0xc9, 0xfd, 0x52, 0xf5, 0x1f, 0x29, 0xdd, 0x19, 0x21, 0x6d, 0x54, 0x5a, 0xa4, 0x53, 0x8b, 0x6e,
	0xf6, 0x7e, 0xe7, 0xce, 0x0f, 0x53, 0x99, 0x5b, 0x78, 0x05, 0x59, 0xb8, 0xc7, 0xaa, 0xf1, 0x6e,
	0x31, 0x78, 0x5a, 0xac, 0x02, 0xb2, 0x5c, 0x05, 0xe4, 0x67, 0x15, 0x90, 0x8f, 0x75, 0xe0, 0x2d,
	0xd7, 0x81, 0xf7, 0xb5, 0x0e, 0xbc, 0xe7, 0x3b, 0x05, 0xf6, 0x6d, 0x96, 0x30, 0xa1, 0x33, 0x2e,
	0x34, 0x66, 0x1a, 0x39, 0x24, 0xa2, 0xab, 0x34, 0x9f, 0x87, 0x21, 0xcf, 0x74, 0x3a, 0x9b, 0x4a,
	0xdc, 0x54, 0x8f, 0x3c, 0xea, 0x75, 0x37, 0xad, 0xdb, 0x77, 0x23, 0x31, 0x39, 0xda, 0x76, 0x7b,
	0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x9d, 0xfa, 0x27, 0xda, 0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RegisteredICS27Account) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *RegisteredICS27Account) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *RegisteredICS27Account) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *GenesisState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *RegisteredICS27Account) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozGenesis(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *GenesisState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *RegisteredICS27Account) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipGenesis(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
