// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/channel/v1/channel.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// State defines if a channel is in one of the following states:
// CLOSED, INIT, TRYOPEN, OPEN, or UNINITIALIZED.
type State int32

const (
	// Default State
	UNINITIALIZED State = 0
	// A channel has just started the opening handshake.
	INIT State = 1
	// A channel has acknowledged the handshake step on the counterparty chain.
	TRYOPEN State = 2
	// A channel has completed the handshake. Open channels are
	// ready to send and receive packets.
	OPEN State = 3
	// A channel has been closed and can no longer be used to send or receive
	// packets.
	CLOSED State = 4
)

var State_name = map[int32]string{
	0: "STATE_UNINITIALIZED_UNSPECIFIED",
	1: "STATE_INIT",
	2: "STATE_TRYOPEN",
	3: "STATE_OPEN",
	4: "STATE_CLOSED",
}

var State_value = map[string]int32{
	"STATE_UNINITIALIZED_UNSPECIFIED": 0,
	"STATE_INIT":                      1,
	"STATE_TRYOPEN":                   2,
	"STATE_OPEN":                      3,
	"STATE_CLOSED":                    4,
}

func (x State) String() string { _ = "STUB: not implemented"; return "" }

func (State) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Order defines if a channel is ORDERED or UNORDERED
type Order int32

const (
	// zero-value for channel ordering
	NONE Order = 0
	// packets can be delivered in any order, which may differ from the order in
	// which they were sent.
	UNORDERED Order = 1
	// packets are delivered exactly in the order which they were sent
	ORDERED Order = 2
)

var Order_name = map[int32]string{
	0: "ORDER_NONE_UNSPECIFIED",
	1: "ORDER_UNORDERED",
	2: "ORDER_ORDERED",
}

var Order_value = map[string]int32{
	"ORDER_NONE_UNSPECIFIED": 0,
	"ORDER_UNORDERED":        1,
	"ORDER_ORDERED":          2,
}

func (x Order) String() string { _ = "STUB: not implemented"; return "" }

func (Order) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// Channel defines pipeline for exactly-once packet delivery between specific
// modules on separate blockchains, which has at least one end capable of
// sending packets and one end capable of receiving packets.
type Channel struct {
	// current state of the channel end
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=ibc.core.channel.v1.State" json:"state,omitempty"`
	// whether the channel is ordered or unordered
	Ordering Order `protobuf:"varint,2,opt,name=ordering,proto3,enum=ibc.core.channel.v1.Order" json:"ordering,omitempty"`
	// counterparty channel end
	Counterparty Counterparty `protobuf:"bytes,3,opt,name=counterparty,proto3" json:"counterparty"`
	// list of connection identifiers, in order, along which packets sent on
	// this channel will travel
	ConnectionHops []string `protobuf:"bytes,4,rep,name=connection_hops,json=connectionHops,proto3" json:"connection_hops,omitempty"`
	// opaque channel version, which is agreed upon during the handshake
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *Channel) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Channel) String() string            { _ = "STUB: not implemented"; return "" }
func (*Channel) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Channel) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Channel) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Channel) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Channel) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Channel) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Channel proto.InternalMessageInfo

// IdentifiedChannel defines a channel with additional port and channel
// identifier fields.
type IdentifiedChannel struct {
	// current state of the channel end
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=ibc.core.channel.v1.State" json:"state,omitempty"`
	// whether the channel is ordered or unordered
	Ordering Order `protobuf:"varint,2,opt,name=ordering,proto3,enum=ibc.core.channel.v1.Order" json:"ordering,omitempty"`
	// counterparty channel end
	Counterparty Counterparty `protobuf:"bytes,3,opt,name=counterparty,proto3" json:"counterparty"`
	// list of connection identifiers, in order, along which packets sent on
	// this channel will travel
	ConnectionHops []string `protobuf:"bytes,4,rep,name=connection_hops,json=connectionHops,proto3" json:"connection_hops,omitempty"`
	// opaque channel version, which is agreed upon during the handshake
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// port identifier
	PortId string `protobuf:"bytes,6,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel identifier
	ChannelId string `protobuf:"bytes,7,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *IdentifiedChannel) Reset()                    { _ = "STUB: not implemented"; return }
func (m *IdentifiedChannel) String() string            { _ = "STUB: not implemented"; return "" }
func (*IdentifiedChannel) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*IdentifiedChannel) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *IdentifiedChannel) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IdentifiedChannel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IdentifiedChannel) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *IdentifiedChannel) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *IdentifiedChannel) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_IdentifiedChannel proto.InternalMessageInfo

// Counterparty defines a channel end counterparty
type Counterparty struct {
	// port on the counterparty chain which owns the other end of the channel.
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel end on the counterparty chain
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (m *Counterparty) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Counterparty) String() string            { _ = "STUB: not implemented"; return "" }
func (*Counterparty) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Counterparty) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Counterparty) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Counterparty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Counterparty) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Counterparty) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Counterparty) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Counterparty proto.InternalMessageInfo

// Packet defines a type that carries data across different chains through IBC
type Packet struct {
	// number corresponds to the order of sends and receives, where a Packet
	// with an earlier sequence number must be sent and received before a Packet
	// with a later sequence number.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// identifies the port on the sending chain.
	SourcePort string `protobuf:"bytes,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// identifies the channel end on the sending chain.
	SourceChannel string `protobuf:"bytes,3,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	// identifies the port on the receiving chain.
	DestinationPort string `protobuf:"bytes,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	// identifies the channel end on the receiving chain.
	DestinationChannel string `protobuf:"bytes,5,opt,name=destination_channel,json=destinationChannel,proto3" json:"destination_channel,omitempty"`
	// actual opaque bytes transferred directly to the application module
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// block height after which the packet times out
	TimeoutHeight types.Height `protobuf:"bytes,7,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height"`
	// block timestamp (in nanoseconds) after which the packet times out
	TimeoutTimestamp uint64 `protobuf:"varint,8,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
}

func (m *Packet) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Packet) String() string            { _ = "STUB: not implemented"; return "" }
func (*Packet) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Packet) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Packet) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Packet) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Packet) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Packet proto.InternalMessageInfo

// PacketState defines the generic type necessary to retrieve and store
// packet commitments, acknowledgements, and receipts.
// Caller is responsible for knowing the context necessary to interpret this
// state as a commitment, acknowledgement, or a receipt.
type PacketState struct {
	// channel port identifier.
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier.
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// packet sequence.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// embedded data that represents packet state.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PacketState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketState) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketState proto.InternalMessageInfo

// PacketId is an identifier for a unique Packet
// Source chains refer to packets by source port/channel
// Destination chains refer to packets by destination port/channel
type PacketId struct {
	// channel port identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// packet sequence
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (m *PacketId) Reset()                    { _ = "STUB: not implemented"; return }
func (m *PacketId) String() string            { _ = "STUB: not implemented"; return "" }
func (*PacketId) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*PacketId) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketId) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketId) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *PacketId) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *PacketId) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_PacketId proto.InternalMessageInfo

// Acknowledgement is the recommended acknowledgement format to be used by
// app-specific protocols.
// NOTE: The field numbers 21 and 22 were explicitly chosen to avoid accidental
// conflicts with other protobuf message formats used for acknowledgements.
// The first byte of any message with this format will be the non-ASCII values
// `0xaa` (result) or `0xb2` (error). Implemented as defined by ICS:
// https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#acknowledgement-envelope
type Acknowledgement struct {
	// response contains either a result or an error and must be non-empty
	//
	// Types that are valid to be assigned to Response:
	//	*Acknowledgement_Result
	//	*Acknowledgement_Error
	Response isAcknowledgement_Response `protobuf_oneof:"response"`
}

func (m *Acknowledgement) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Acknowledgement) String() string            { _ = "STUB: not implemented"; return "" }
func (*Acknowledgement) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Acknowledgement) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Acknowledgement) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Acknowledgement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Acknowledgement) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Acknowledgement) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Acknowledgement proto.InternalMessageInfo

type isAcknowledgement_Response interface {
	isAcknowledgement_Response()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Acknowledgement_Result struct {
	Result []byte `protobuf:"bytes,21,opt,name=result,proto3,oneof" json:"result,omitempty"`
}
type Acknowledgement_Error struct {
	Error string `protobuf:"bytes,22,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (*Acknowledgement_Result) isAcknowledgement_Response() { _ = "STUB: not implemented"; return }
func (*Acknowledgement_Error) isAcknowledgement_Response()  { _ = "STUB: not implemented"; return }

func (m *Acknowledgement) GetResponse() isAcknowledgement_Response {
	_ = "STUB: not implemented"
	return *new(isAcknowledgement_Response)
}

func (m *Acknowledgement) GetResult() []byte { _ = "STUB: not implemented"; return nil }

func (m *Acknowledgement) GetError() string { _ = "STUB: not implemented"; return "" }

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Acknowledgement) XXX_OneofWrappers() []interface{} { _ = "STUB: not implemented"; return nil }

// Timeout defines an execution deadline structure for 04-channel handlers.
// This includes packet lifecycle handlers.
// A valid Timeout contains either one or both of a timestamp and block height (sequence).
type Timeout struct {
	// block height after which the packet times out
	Height types.Height `protobuf:"bytes,1,opt,name=height,proto3" json:"height"`
	// block timestamp (in nanoseconds) after which the packet times out
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *Timeout) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Timeout) String() string            { _ = "STUB: not implemented"; return "" }
func (*Timeout) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Timeout) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Timeout) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Timeout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Timeout) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Timeout) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Timeout) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Timeout proto.InternalMessageInfo

func (m *Timeout) GetHeight() types.Height { _ = "STUB: not implemented"; return *new(types.Height) }

func (m *Timeout) GetTimestamp() uint64 { _ = "STUB: not implemented"; return 0 }

func init() {
	proto.RegisterEnum("ibc.core.channel.v1.State", State_name, State_value)
	proto.RegisterEnum("ibc.core.channel.v1.Order", Order_name, Order_value)
	proto.RegisterType((*Channel)(nil), "ibc.core.channel.v1.Channel")
	proto.RegisterType((*IdentifiedChannel)(nil), "ibc.core.channel.v1.IdentifiedChannel")
	proto.RegisterType((*Counterparty)(nil), "ibc.core.channel.v1.Counterparty")
	proto.RegisterType((*Packet)(nil), "ibc.core.channel.v1.Packet")
	proto.RegisterType((*PacketState)(nil), "ibc.core.channel.v1.PacketState")
	proto.RegisterType((*PacketId)(nil), "ibc.core.channel.v1.PacketId")
	proto.RegisterType((*Acknowledgement)(nil), "ibc.core.channel.v1.Acknowledgement")
	proto.RegisterType((*Timeout)(nil), "ibc.core.channel.v1.Timeout")
}

func init() { proto.RegisterFile("ibc/core/channel/v1/channel.proto", fileDescriptor_c3a07336710636a0) }

var fileDescriptor_c3a07336710636a0 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x26, 0x65, 0xea, 0x6f, 0x64, 0xd9, 0xf2, 0xa6, 0x75, 0x09, 0x22, 0xa5, 0x18, 0xa3, 0x45,
	0xdd, 0x14, 0x11, 0xa3, 0xb4, 0x28, 0x8a, 0xdc, 0x6c, 0x89, 0xad, 0x88, 0x1a, 0x92, 0x40, 0xc9,
	0x87, 0xe6, 0x22, 0x50, 0xe4, 0x56, 0x22, 0x22, 0x71, 0x59, 0x72, 0xa5, 0x20, 0xe8, 0x0b, 0xa4,
	0x3a, 0xf5, 0x05, 0x04, 0x14, 0xe8, 0x43, 0xf4, 0x15, 0x02, 0xf4, 0x92, 0x63, 0x4e, 0x45, 0x61,
	0xbf, 0x48, 0xc1, 0xdd, 0xa5, 0x25, 0x05, 0x86, 0x51, 0x14, 0xe8, 0x29, 0x27, 0xed, 0x7c, 0xf3,
	0xcd, 0x37, 0xc3, 0x6f, 0x28, 0x2e, 0x3c, 0x08, 0xc6, 0x9e, 0xe9, 0x91, 0x18, 0x9b, 0xde, 0xd4,
	0x0d, 0x43, 0x3c, 0x33, 0x97, 0xcd, 0xec, 0xd8, 0x88, 0x62, 0x42, 0x09, 0xba, 0x17, 0x8c, 0xbd,
	0x46, 0x4a, 0x69, 0x64, 0xf8, 0xb2, 0xa9, 0x7d, 0x30, 0x21, 0x13, 0xc2, 0xf2, 0x66, 0x7a, 0xe2,
	0x54, 0xad, 0xbe, 0x51, 0x9b, 0x05, 0x38, 0xa4, 0x4c, 0x8c, 0x9d, 0x38, 0xe1, 0xe4, 0x97, 0x1c,
	0x14, 0x5b, 0x5c, 0x05, 0x3d, 0x86, 0x7c, 0x42, 0x5d, 0x8a, 0x55, 0xd9, 0x90, 0x4f, 0x0f, 0x9e,
	0x68, 0x8d, 0x5b, 0xfa, 0x34, 0x06, 0x29, 0xc3, 0xe1, 0x44, 0xf4, 0x35, 0x94, 0x48, 0xec, 0xe3,
	0x38, 0x08, 0x27, 0x6a, 0xee, 0x8e, 0xa2, 0x5e, 0x4a, 0x72, 0x6e, 0xb8, 0xe8, 0x7b, 0xd8, 0xf7,
	0xc8, 0x22, 0xa4, 0x38, 0x8e, 0xdc, 0x98, 0xbe, 0x54, 0xf7, 0x0c, 0xf9, 0xb4, 0xf2, 0xe4, 0xc1,
	0xad, 0xb5, 0xad, 0x2d, 0xe2, 0xb9, 0xf2, 0xfa, 0xaf, 0xba, 0xe4, 0xec, 0x14, 0xa3, 0xcf, 0xe0,
	0xd0, 0x23, 0x61, 0x88, 0x3d, 0x1a, 0x90, 0x70, 0x34, 0x25, 0x51, 0xa2, 0x2a, 0xc6, 0xde, 0x69,
	0xd9, 0x39, 0xd8, 0xc0, 0x1d, 0x12, 0x25, 0x48, 0x85, 0xe2, 0x12, 0xc7, 0x49, 0x40, 0x42, 0x35,
	0x6f, 0xc8, 0xa7, 0x65, 0x27, 0x0b, 0x9f, 0x2a, 0xaf, 0x7e, 0xab, 0x4b, 0x27, 0x7f, 0xe6, 0xe0,
	0xc8, 0xf6, 0x71, 0x48, 0x83, 0x1f, 0x03, 0xec, 0xbf, 0xf7, 0xae, 0xa0, 0x8f, 0xa0, 0x18, 0x91,
	0x98, 0x8e, 0x02, 0x5f, 0x2d, 0xb0, 0x4c, 0x21, 0x0d, 0x6d, 0x1f, 0x7d, 0x0c, 0x20, 0x46, 0x49,
	0x73, 0x45, 0x96, 0x2b, 0x0b, 0xc4, 0xf6, 0x85, 0x9b, 0x17, 0xb0, 0xbf, 0x3d, 0xe4, 0xb6, 0x9a,
	0x7c, 0x87, 0x5a, 0xee, 0x76, 0xb5, 0xb7, 0x39, 0x28, 0xf4, 0x5d, 0xef, 0x39, 0xa6, 0x48, 0x83,
	0x52, 0x82, 0x7f, 0x5a, 0xe0, 0xd0, 0xe3, 0x3b, 0x51, 0x9c, 0x9b, 0x18, 0xd5, 0xa1, 0x92, 0x90,
	0x45, 0xec, 0xe1, 0x51, 0x2a, 0x2e, 0xc4, 0x80, 0x43, 0x7d, 0x12, 0x53, 0xf4, 0x29, 0x1c, 0x08,
	0x82, 0xe8, 0xc0, 0x5c, 0x2e, 0x3b, 0x55, 0x8e, 0x66, 0x4b, 0xff, 0x1c, 0x6a, 0x3e, 0x4e, 0x68,
	0x10, 0xba, 0xcc, 0x3e, 0x26, 0xa6, 0x30, 0xe2, 0xe1, 0x16, 0xce, 0x14, 0x4d, 0xb8, 0xb7, 0x4d,
	0xcd, 0x64, 0xb9, 0x97, 0x68, 0x2b, 0x95, 0x69, 0x23, 0x50, 0x7c, 0x97, 0xba, 0xcc, 0xd3, 0x7d,
	0x87, 0x9d, 0xd1, 0x77, 0x70, 0x40, 0x83, 0x39, 0x26, 0x0b, 0x3a, 0x9a, 0xe2, 0x60, 0x32, 0xa5,
	0xcc, 0xd5, 0xca, 0xce, 0x8b, 0xc3, 0xff, 0xb6, 0xcb, 0x66, 0xa3, 0xc3, 0x18, 0x62, 0xeb, 0x55,
	0x51, 0xc7, 0x41, 0xf4, 0x05, 0x1c, 0x65, 0x42, 0xe9, 0x6f, 0x42, 0xdd, 0x79, 0xa4, 0x96, 0x98,
	0x4b, 0x35, 0x91, 0x18, 0x66, 0xb8, 0xb0, 0xf6, 0x67, 0xa8, 0x70, 0x67, 0xd9, 0x4b, 0xfc, 0x5f,
	0xf7, 0xb4, 0xb3, 0x96, 0xbd, 0x77, 0xd6, 0x92, 0x3d, 0xb2, 0xb2, 0x79, 0x64, 0xd1, 0xdc, 0x87,
	0x12, 0x6f, 0x6e, 0xfb, 0xff, 0x47, 0x67, 0xd1, 0xa5, 0x07, 0x87, 0x67, 0xde, 0xf3, 0x90, 0xbc,
	0x98, 0x61, 0x7f, 0x82, 0xe7, 0x38, 0xa4, 0x48, 0x85, 0x42, 0x8c, 0x93, 0xc5, 0x8c, 0xaa, 0x1f,
	0xa6, 0x43, 0x75, 0x24, 0x47, 0xc4, 0xe8, 0x18, 0xf2, 0x38, 0x8e, 0x49, 0xac, 0x1e, 0xa7, 0x8d,
	0x3a, 0x92, 0xc3, 0xc3, 0x73, 0x80, 0x52, 0x8c, 0x93, 0x88, 0x84, 0x09, 0x3e, 0x71, 0xa1, 0x38,
	0xe4, 0x6e, 0xa2, 0x6f, 0xa0, 0x20, 0x56, 0x26, 0xff, 0xcb, 0x95, 0x09, 0x3e, 0xba, 0x0f, 0xe5,
	0xcd, 0x8e, 0x72, 0x6c, 0xf0, 0x0d, 0xf0, 0xf0, 0x0f, 0x19, 0xf2, 0x03, 0xf1, 0x3d, 0xa9, 0x0f,
	0x86, 0x67, 0x43, 0x6b, 0x74, 0xd9, 0xb5, 0xbb, 0xf6, 0xd0, 0x3e, 0xbb, 0xb0, 0x9f, 0x59, 0xed,
	0xd1, 0x65, 0x77, 0xd0, 0xb7, 0x5a, 0xf6, 0xb7, 0xb6, 0xd5, 0xae, 0x49, 0xda, 0xd1, 0x6a, 0x6d,
	0x54, 0x77, 0x08, 0x48, 0x05, 0xe0, 0x75, 0x29, 0x58, 0x93, 0xb5, 0xd2, 0x6a, 0x6d, 0x28, 0xe9,
	0x19, 0xe9, 0x50, 0xe5, 0x99, 0xa1, 0xf3, 0x43, 0xaf, 0x6f, 0x75, 0x6b, 0x39, 0xad, 0xb2, 0x5a,
	0x1b, 0x45, 0x11, 0x6e, 0x2a, 0x59, 0x72, 0x8f, 0x57, 0xb2, 0xcc, 0x7d, 0xd8, 0xe7, 0x99, 0xd6,
	0x45, 0x6f, 0x60, 0xb5, 0x6b, 0x8a, 0x06, 0xab, 0xb5, 0x51, 0xe0, 0x91, 0xa6, 0xbc, 0xfa, 0x5d,
	0x97, 0x1e, 0xbe, 0x80, 0x3c, 0xfb, 0xb4, 0xa1, 0x4f, 0xe0, 0xb8, 0xe7, 0xb4, 0x2d, 0x67, 0xd4,
	0xed, 0x75, 0xad, 0x77, 0xe6, 0x65, 0x92, 0x29, 0x8e, 0x4e, 0xe0, 0x90, 0xb3, 0x2e, 0xbb, 0xec,
	0xd7, 0x6a, 0xd7, 0x64, 0xad, 0xba, 0x5a, 0x1b, 0xe5, 0x1b, 0x20, 0x1d, 0x98, 0x73, 0x32, 0x86,
	0x18, 0x58, 0x84, 0xbc, 0xf1, 0xf9, 0xf0, 0xf5, 0x95, 0x2e, 0xbf, 0xb9, 0xd2, 0xe5, 0xbf, 0xaf,
	0x74, 0xf9, 0xd7, 0x6b, 0x5d, 0x7a, 0x73, 0xad, 0x4b, 0x6f, 0xaf, 0x75, 0xe9, 0xd9, 0xd3, 0x49,
	0x40, 0xa7, 0x8b, 0x71, 0xc3, 0x23, 0x73, 0xd3, 0x23, 0xc9, 0x9c, 0x24, 0x66, 0x30, 0xf6, 0x1e,
	0x4d, 0x88, 0xb9, 0x6c, 0x36, 0xcd, 0x39, 0xf1, 0x17, 0x33, 0x9c, 0xf0, 0x8b, 0xf2, 0xf1, 0x57,
	0x8f, 0xb2, 0x9b, 0x97, 0xbe, 0x8c, 0x70, 0x32, 0x2e, 0xb0, 0x9b, 0xf2, 0xcb, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x58, 0xb9, 0xba, 0x95, 0x9a, 0x07, 0x00, 0x00,
}

func (m *Channel) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Channel) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Channel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IdentifiedChannel) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *IdentifiedChannel) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *IdentifiedChannel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Counterparty) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Counterparty) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Counterparty) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Packet) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Packet) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Packet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *PacketState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *PacketId) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *PacketId) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *PacketId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Acknowledgement) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement_Result) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement_Result) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement_Error) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Acknowledgement_Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Timeout) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Timeout) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Timeout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintChannel(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *Channel) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *IdentifiedChannel) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Counterparty) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Packet) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *PacketId) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement_Result) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Acknowledgement_Error) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Timeout) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovChannel(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozChannel(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Channel) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *IdentifiedChannel) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Counterparty) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Packet) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *PacketId) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Acknowledgement) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Timeout) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipChannel(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthChannel        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChannel          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChannel = fmt.Errorf("proto: unexpected end of group")
)
