// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/interchain_accounts/host/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams defines the payload for Msg/UpdateParams
type MsgUpdateParams struct {
	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// params defines the 27-interchain-accounts/host parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpdateParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

// MsgUpdateParamsResponse defines the response for Msg/UpdateParams
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgModuleQuerySafe defines the payload for Msg/ModuleQuerySafe
type MsgModuleQuerySafe struct {
	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// requests defines the module safe queries to execute.
	Requests []QueryRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests"`
}

func (m *MsgModuleQuerySafe) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgModuleQuerySafe) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgModuleQuerySafe) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgModuleQuerySafe) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgModuleQuerySafe) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgModuleQuerySafe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgModuleQuerySafe) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgModuleQuerySafe) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgModuleQuerySafe) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgModuleQuerySafe proto.InternalMessageInfo

// MsgModuleQuerySafeResponse defines the response for Msg/ModuleQuerySafe
type MsgModuleQuerySafeResponse struct {
	// height at which the responses were queried
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	// protobuf encoded responses for each query
	Responses [][]byte `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (m *MsgModuleQuerySafeResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgModuleQuerySafeResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgModuleQuerySafeResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgModuleQuerySafeResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgModuleQuerySafeResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgModuleQuerySafeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgModuleQuerySafeResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgModuleQuerySafeResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgModuleQuerySafeResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgModuleQuerySafeResponse proto.InternalMessageInfo

func (m *MsgModuleQuerySafeResponse) GetHeight() uint64 { _ = "STUB: not implemented"; return 0 }

func (m *MsgModuleQuerySafeResponse) GetResponses() [][]byte { _ = "STUB: not implemented"; return nil }

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "ibc.applications.interchain_accounts.host.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ibc.applications.interchain_accounts.host.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgModuleQuerySafe)(nil), "ibc.applications.interchain_accounts.host.v1.MsgModuleQuerySafe")
	proto.RegisterType((*MsgModuleQuerySafeResponse)(nil), "ibc.applications.interchain_accounts.host.v1.MsgModuleQuerySafeResponse")
}

func init() {
	proto.RegisterFile("ibc/applications/interchain_accounts/host/v1/tx.proto", fileDescriptor_fa437afde7f1e7ae)
}

var fileDescriptor_fa437afde7f1e7ae = []byte{
	// 457 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x33, 0x6d, 0x5d, 0xec, 0xb4, 0x50, 0x08, 0x62, 0x6b, 0x90, 0xb4, 0xec, 0x69, 0x29,
	0xee, 0x0c, 0xbb, 0x2a, 0x85, 0x82, 0x20, 0x05, 0x41, 0x90, 0x05, 0x1d, 0xf1, 0x22, 0x82, 0x4c,
	0xa6, 0xe3, 0x64, 0xa0, 0xc9, 0xc4, 0xbc, 0xc9, 0x62, 0x6f, 0xe2, 0xc9, 0x93, 0x78, 0xf0, 0x26,
	0x82, 0x1f, 0xa1, 0xdf, 0xc1, 0x4b, 0x8f, 0x3d, 0x7a, 0x12, 0xd9, 0x3d, 0xf4, 0x6b, 0x48, 0x66,
	0xa7, 0xad, 0x4d, 0xf5, 0x10, 0xf6, 0x96, 0x49, 0xe6, 0xff, 0x7b, 0xbf, 0x97, 0x99, 0x87, 0xef,
	0xeb, 0x44, 0x50, 0x5e, 0x14, 0x07, 0x5a, 0x70, 0xab, 0x4d, 0x0e, 0x54, 0xe7, 0x56, 0x96, 0x22,
	0xe5, 0x3a, 0x7f, 0xcd, 0x85, 0x30, 0x55, 0x6e, 0x81, 0xa6, 0x06, 0x2c, 0x1d, 0x0f, 0xa8, 0x7d,
	0x47, 0x8a, 0xd2, 0x58, 0x13, 0xde, 0xd1, 0x89, 0x20, 0x7f, 0xc7, 0xc8, 0x3f, 0x62, 0xa4, 0x8e,
	0x91, 0xf1, 0x20, 0xba, 0xa1, 0x8c, 0x32, 0x2e, 0x48, 0xeb, 0xa7, 0x19, 0x23, 0x5a, 0x17, 0x06,
	0x32, 0x03, 0x34, 0x03, 0x55, 0xb3, 0x33, 0x50, 0xfe, 0xc3, 0x4e, 0x2b, 0x27, 0x57, 0xc4, 0x05,
	0xbb, 0x9f, 0x10, 0x5e, 0x1b, 0x81, 0x7a, 0x51, 0xec, 0x73, 0x2b, 0x9f, 0xf2, 0x92, 0x67, 0x10,
	0xde, 0xc4, 0x1d, 0xd0, 0x2a, 0x97, 0xe5, 0x06, 0xda, 0x42, 0xbd, 0x65, 0xe6, 0x57, 0x21, 0xc3,
	0x9d, 0xc2, 0xed, 0xd8, 0x58, 0xd8, 0x42, 0xbd, 0x95, 0xe1, 0x3d, 0xd2, 0xa6, 0x25, 0x32, 0xa3,
	0xef, 0x2d, 0x1d, 0xff, 0xda, 0x0c, 0x98, 0x27, 0xed, 0xae, 0x7d, 0xfc, 0xbe, 0x19, 0x7c, 0x38,
	0x3d, 0xda, 0xf6, 0x45, 0xba, 0xb7, 0xf0, 0x7a, 0xc3, 0x87, 0x49, 0x28, 0x4c, 0x0e, 0xb2, 0xfb,
	0x15, 0xe1, 0x70, 0x04, 0x6a, 0x64, 0xf6, 0xab, 0x03, 0xf9, 0xac, 0x92, 0xe5, 0xe1, 0x73, 0xfe,
	0x46, 0xfe, 0x57, 0xf7, 0x15, 0xbe, 0x5e, 0xca, 0xb7, 0x95, 0x04, 0x5b, 0x0b, 0x2f, 0xf6, 0x56,
	0x86, 0xbb, 0xed, 0x84, 0x5d, 0x09, 0x36, 0x43, 0x78, 0xed, 0x73, 0xe2, 0x55, 0x71, 0x86, 0xa3,
	0xab, 0x72, 0x67, 0xee, 0xb5, 0x64, 0x2a, 0xb5, 0x4a, 0xad, 0x93, 0x5c, 0x62, 0x7e, 0x15, 0xde,
	0xc6, 0xcb, 0xa5, 0xdf, 0x33, 0xb3, 0x5c, 0x65, 0x17, 0x2f, 0x86, 0x3f, 0x16, 0xf0, 0xe2, 0x08,
	0x54, 0xf8, 0x05, 0xe1, 0xd5, 0x4b, 0x47, 0xf4, 0xa0, 0x5d, 0x27, 0x8d, 0x3f, 0x1a, 0x3d, 0x9a,
	0x2b, 0x7e, 0xde, 0xd4, 0xb7, 0xfa, 0xf2, 0x34, 0x4e, 0xe3, 0x61, 0x6b, 0x74, 0x83, 0x10, 0x3d,
	0x9e, 0x97, 0x70, 0xe6, 0x17, 0x5d, 0x7b, 0x7f, 0x7a, 0xb4, 0x8d, 0xf6, 0xe4, 0xf1, 0x24, 0x46,
	0x27, 0x93, 0x18, 0xfd, 0x9e, 0xc4, 0xe8, 0xf3, 0x34, 0x0e, 0x4e, 0xa6, 0x71, 0xf0, 0x73, 0x1a,
	0x07, 0x2f, 0x9f, 0x28, 0x6d, 0xd3, 0x2a, 0x21, 0xc2, 0x64, 0xd4, 0x8f, 0x96, 0x4e, 0x44, 0x5f,
	0x19, 0x3a, 0x1e, 0x0c, 0x68, 0xe6, 0xb0, 0x50, 0xcf, 0x15, 0xd0, 0xe1, 0x4e, 0xff, 0xc2, 0xa2,
	0x7f, 0x79, 0xa4, 0xec, 0x61, 0x21, 0x21, 0xe9, 0xb8, 0x89, 0xba, 0xfb, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0x5f, 0xbe, 0x8a, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a rpc handler for MsgUpdateParams.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// ModuleQuerySafe defines a rpc handler for MsgModuleQuerySafe.
	ModuleQuerySafe(ctx context.Context, in *MsgModuleQuerySafe, opts ...grpc.CallOption) (*MsgModuleQuerySafeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient { _ = "STUB: not implemented"; return *new(MsgClient) }

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) ModuleQuerySafe(ctx context.Context, in *MsgModuleQuerySafe, opts ...grpc.CallOption) (*MsgModuleQuerySafeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a rpc handler for MsgUpdateParams.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// ModuleQuerySafe defines a rpc handler for MsgModuleQuerySafe.
	ModuleQuerySafe(context.Context, *MsgModuleQuerySafe) (*MsgModuleQuerySafeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) ModuleQuerySafe(ctx context.Context, req *MsgModuleQuerySafe) (*MsgModuleQuerySafeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) { _ = "STUB: not implemented"; return }

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_ModuleQuerySafe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.applications.interchain_accounts.host.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "ModuleQuerySafe",
			Handler:    _Msg_ModuleQuerySafe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/applications/interchain_accounts/host/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgModuleQuerySafe) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgModuleQuerySafe) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgModuleQuerySafe) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgModuleQuerySafeResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgModuleQuerySafeResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgModuleQuerySafeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgModuleQuerySafe) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgModuleQuerySafeResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgModuleQuerySafe) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgModuleQuerySafeResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipTx(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
