// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/client/v1/deprecated.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/codec/types"
	types "github.com/cosmos/cosmos-sdk/x/upgrade/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientUpdateProposal is a legacy governance proposal. If it passes, the substitute
// client's latest consensus state is copied over to the subject client. The proposal
// handler may fail if the subject and the substitute do not match in client and
// chain parameters (with exception to latest height, frozen height, and chain-id).
//
// Deprecated: Please use MsgRecoverClient in favour of this message type.
//
// Deprecated: Do not use.
type ClientUpdateProposal struct {
	// the title of the update proposal
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// the description of the proposal
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// the client identifier for the client to be updated if the proposal passes
	SubjectClientId string `protobuf:"bytes,3,opt,name=subject_client_id,json=subjectClientId,proto3" json:"subject_client_id,omitempty" yaml:"subject_client_id"`
	// the substitute client identifier for the client standing in for the subject
	// client
	SubstituteClientId string `protobuf:"bytes,4,opt,name=substitute_client_id,json=substituteClientId,proto3" json:"substitute_client_id,omitempty" yaml:"substitute_client_id"`
}

func (m *ClientUpdateProposal) Reset()         { _ = "STUB: not implemented"; return }
func (m *ClientUpdateProposal) String() string { _ = "STUB: not implemented"; return "" }
func (*ClientUpdateProposal) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*ClientUpdateProposal) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientUpdateProposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientUpdateProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientUpdateProposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientUpdateProposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientUpdateProposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientUpdateProposal proto.InternalMessageInfo

// UpgradeProposal is a gov Content type for initiating an IBC breaking
// upgrade.
//
// Deprecated: Please use MsgIBCSoftwareUpgrade in favour of this message type.
//
// Deprecated: Do not use.
type UpgradeProposal struct {
	Title       string     `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Plan        types.Plan `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan"`
	// An UpgradedClientState must be provided to perform an IBC breaking upgrade.
	// This will make the chain commit to the correct upgraded (self) client state
	// before the upgrade occurs, so that connecting chains can verify that the
	// new upgraded client is valid by verifying a proof on the previous version
	// of the chain. This will allow IBC connections to persist smoothly across
	// planned chain upgrades
	UpgradedClientState *types1.Any `protobuf:"bytes,4,opt,name=upgraded_client_state,json=upgradedClientState,proto3" json:"upgraded_client_state,omitempty" yaml:"upgraded_client_state"`
}

func (m *UpgradeProposal) Reset()                    { _ = "STUB: not implemented"; return }
func (*UpgradeProposal) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*UpgradeProposal) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *UpgradeProposal) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *UpgradeProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpgradeProposal) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *UpgradeProposal) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *UpgradeProposal) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_UpgradeProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientUpdateProposal)(nil), "ibc.core.client.v1.ClientUpdateProposal")
	proto.RegisterType((*UpgradeProposal)(nil), "ibc.core.client.v1.UpgradeProposal")
}

func init() {
	proto.RegisterFile("ibc/core/client/v1/deprecated.proto", fileDescriptor_95e37bacc9dd01d3)
}

var fileDescriptor_95e37bacc9dd01d3 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xb1, 0x8e, 0xd3, 0x40,
	0x10, 0xb5, 0x43, 0x40, 0xc2, 0x29, 0x4e, 0x18, 0x23, 0x99, 0x10, 0xd9, 0x91, 0xb9, 0x82, 0x82,
	0xec, 0x9e, 0x83, 0x84, 0x44, 0x3a, 0x72, 0x0d, 0x74, 0x87, 0x4f, 0xd7, 0xd0, 0x44, 0xeb, 0xf5,
	0x62, 0xf6, 0xe4, 0x78, 0x2d, 0xef, 0xd8, 0x52, 0xfe, 0x80, 0x12, 0x3a, 0x24, 0x9a, 0x7c, 0x04,
	0x1f, 0x71, 0xa2, 0xba, 0x92, 0x2a, 0x42, 0x49, 0x43, 0x9d, 0x2f, 0x40, 0xde, 0xb5, 0xe1, 0xa4,
	0x20, 0x51, 0xd0, 0xf9, 0xbd, 0x79, 0x33, 0xe3, 0x79, 0xb3, 0x63, 0x3d, 0xe6, 0x31, 0xc5, 0x54,
	0x94, 0x0c, 0xd3, 0x8c, 0xb3, 0x1c, 0x70, 0x1d, 0xe2, 0x84, 0x15, 0x25, 0xa3, 0x04, 0x58, 0x82,
	0x8a, 0x52, 0x80, 0xb0, 0x6d, 0x1e, 0x53, 0xd4, 0x88, 0x90, 0x16, 0xa1, 0x3a, 0x1c, 0x1e, 0x53,
	0x21, 0x97, 0x42, 0xe2, 0xaa, 0x48, 0x4b, 0x92, 0x30, 0x5c, 0x87, 0x31, 0x03, 0x12, 0x76, 0x58,
	0x67, 0x0e, 0x1f, 0x6a, 0xd5, 0x42, 0x21, 0xac, 0x41, 0x1b, 0x72, 0x52, 0x91, 0x0a, 0xcd, 0x37,
	0x5f, 0x5d, 0x42, 0x2a, 0x44, 0x9a, 0x31, 0xac, 0x50, 0x5c, 0xbd, 0xc3, 0x24, 0x5f, 0xe9, 0x50,
	0xf0, 0xa9, 0x67, 0x39, 0xa7, 0xaa, 0xff, 0x45, 0x91, 0x10, 0x60, 0x67, 0xa5, 0x28, 0x84, 0x24,
	0x99, 0xed, 0x58, 0xb7, 0x81, 0x43, 0xc6, 0x5c, 0x73, 0x6c, 0x3e, 0xb9, 0x1b, 0x69, 0x60, 0x8f,
	0xad, 0x41, 0xc2, 0x24, 0x2d, 0x79, 0x01, 0x5c, 0xe4, 0x6e, 0x4f, 0xc5, 0x6e, 0x52, 0xf6, 0x2b,
	0xeb, 0x9e, 0xac, 0xe2, 0x4b, 0x46, 0x61, 0xa1, 0xe7, 0x5a, 0xf0, 0xc4, 0xbd, 0xd5, 0xe8, 0xe6,
	0xa3, 0xfd, 0xc6, 0x77, 0x57, 0x64, 0x99, 0xcd, 0x82, 0x03, 0x49, 0x10, 0x1d, 0xb5, 0x9c, 0xfe,
	0x9b, 0xd7, 0x89, 0xfd, 0xc6, 0x72, 0x64, 0x15, 0x4b, 0xe0, 0x50, 0x01, 0xbb, 0x51, 0xac, 0xaf,
	0x8a, 0xf9, 0xfb, 0x8d, 0xff, 0xe8, 0x77, 0xb1, 0x03, 0x55, 0x10, 0xd9, 0x7f, 0xe8, 0xae, 0xe4,
	0xec, 0xf8, 0xc3, 0xda, 0x37, 0xbe, 0x7d, 0x9d, 0x0c, 0x5b, 0xd3, 0x52, 0x51, 0xa3, 0xd6, 0x63,
	0x74, 0x2a, 0x72, 0x60, 0x39, 0xb8, 0x66, 0xf0, 0xa5, 0x67, 0x1d, 0x5d, 0x68, 0xc7, 0xff, 0xdb,
	0x8e, 0xe7, 0x56, 0xbf, 0xc8, 0x48, 0xae, 0x1c, 0x18, 0x4c, 0x47, 0xa8, 0x6d, 0xdc, 0x2d, 0xb4,
	0x6b, 0x7e, 0x96, 0x91, 0x7c, 0xde, 0xbf, 0xda, 0xf8, 0x46, 0xa4, 0xf4, 0xf6, 0xa5, 0xf5, 0xa0,
	0xd5, 0x24, 0xdd, 0x50, 0x12, 0x08, 0x30, 0x35, 0xfd, 0x60, 0xea, 0x20, 0xbd, 0x52, 0xd4, 0xad,
	0x14, 0xbd, 0xcc, 0x57, 0xf3, 0xf1, 0x7e, 0xe3, 0x8f, 0xb4, 0x27, 0x7f, 0x4d, 0x0e, 0xa2, 0xfb,
	0x1d, 0xaf, 0x2d, 0x39, 0x6f, 0xd8, 0xd9, 0xd3, 0xc6, 0x95, 0xcf, 0x6b, 0xdf, 0xf8, 0xb9, 0xf6,
	0xcd, 0x7f, 0xb9, 0x33, 0x3f, 0xbf, 0xda, 0x7a, 0xe6, 0xf5, 0xd6, 0x33, 0x7f, 0x6c, 0x3d, 0xf3,
	0xe3, 0xce, 0x33, 0xae, 0x77, 0x9e, 0xf1, 0x7d, 0xe7, 0x19, 0x6f, 0x5f, 0xa4, 0x1c, 0xde, 0x57,
	0x31, 0xa2, 0x62, 0xd9, 0xbe, 0x4a, 0xcc, 0x63, 0x3a, 0x49, 0x05, 0xae, 0xc3, 0x13, 0xbc, 0x14,
	0x49, 0x95, 0x31, 0xa9, 0xef, 0xe2, 0x64, 0x3a, 0x69, 0x4f, 0x03, 0x56, 0x05, 0x93, 0xf1, 0x1d,
	0x35, 0xc7, 0xb3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xb1, 0xbc, 0x55, 0x3a, 0x03, 0x00,
	0x00,
}

func (this *UpgradeProposal) Equal(that interface{}) bool { _ = "STUB: not implemented"; return false }

func (m *ClientUpdateProposal) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientUpdateProposal) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ClientUpdateProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpgradeProposal) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *UpgradeProposal) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *UpgradeProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintDeprecated(dAtA []byte, offset int, v uint64) int {
	_ = "STUB: not implemented"
	return 0
}

func (m *ClientUpdateProposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *UpgradeProposal) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovDeprecated(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozDeprecated(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientUpdateProposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *UpgradeProposal) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipDeprecated(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthDeprecated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeprecated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeprecated = fmt.Errorf("proto: unexpected end of group")
)
