// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/core/client/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	math "math"

	types "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	types1 "github.com/cosmos/cosmos-sdk/x/upgrade/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateClient defines a message to create an IBC client
type MsgCreateClient struct {
	// light client state
	ClientState *types.Any `protobuf:"bytes,1,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	// consensus state associated with the client that corresponds to a given
	// height.
	ConsensusState *types.Any `protobuf:"bytes,2,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgCreateClient) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgCreateClient) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgCreateClient) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgCreateClient) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgCreateClient) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgCreateClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgCreateClient) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgCreateClient) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgCreateClient) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgCreateClient proto.InternalMessageInfo

// MsgCreateClientResponse defines the Msg/CreateClient response type.
type MsgCreateClientResponse struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (m *MsgCreateClientResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgCreateClientResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgCreateClientResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgCreateClientResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgCreateClientResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgCreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgCreateClientResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgCreateClientResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgCreateClientResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgCreateClientResponse proto.InternalMessageInfo

// MsgUpdateClient defines an sdk.Msg to update a IBC client state using
// the given client message.
type MsgUpdateClient struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// client message to update the light client
	ClientMessage *types.Any `protobuf:"bytes,2,opt,name=client_message,json=clientMessage,proto3" json:"client_message,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgUpdateClient) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpdateClient) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateClient) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpdateClient) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpdateClient) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateClient) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateClient) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateClient) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateClient proto.InternalMessageInfo

// MsgUpdateClientResponse defines the Msg/UpdateClient response type.
type MsgUpdateClientResponse struct {
}

func (m *MsgUpdateClientResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpdateClientResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateClientResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpdateClientResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateClientResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateClientResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateClientResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateClientResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateClientResponse proto.InternalMessageInfo

// MsgUpgradeClient defines an sdk.Msg to upgrade an IBC client to a new client
// state
type MsgUpgradeClient struct {
	// client unique identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// upgraded client state
	ClientState *types.Any `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	// upgraded consensus state, only contains enough information to serve as a
	// basis of trust in update logic
	ConsensusState *types.Any `protobuf:"bytes,3,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	// proof that old chain committed to new client
	ProofUpgradeClient []byte `protobuf:"bytes,4,opt,name=proof_upgrade_client,json=proofUpgradeClient,proto3" json:"proof_upgrade_client,omitempty"`
	// proof that old chain committed to new consensus state
	ProofUpgradeConsensusState []byte `protobuf:"bytes,5,opt,name=proof_upgrade_consensus_state,json=proofUpgradeConsensusState,proto3" json:"proof_upgrade_consensus_state,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,6,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgUpgradeClient) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpgradeClient) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpgradeClient) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpgradeClient) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpgradeClient) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpgradeClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpgradeClient) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpgradeClient) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpgradeClient) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpgradeClient proto.InternalMessageInfo

// MsgUpgradeClientResponse defines the Msg/UpgradeClient response type.
type MsgUpgradeClientResponse struct {
}

func (m *MsgUpgradeClientResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpgradeClientResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpgradeClientResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpgradeClientResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpgradeClientResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpgradeClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpgradeClientResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpgradeClientResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpgradeClientResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpgradeClientResponse proto.InternalMessageInfo

// MsgRecoverClient defines the message used to recover a frozen or expired client.
type MsgRecoverClient struct {
	// the client identifier for the client to be updated if the proposal passes
	SubjectClientId string `protobuf:"bytes,1,opt,name=subject_client_id,json=subjectClientId,proto3" json:"subject_client_id,omitempty"`
	// the substitute client identifier for the client which will replace the subject
	// client
	SubstituteClientId string `protobuf:"bytes,2,opt,name=substitute_client_id,json=substituteClientId,proto3" json:"substitute_client_id,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgRecoverClient) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgRecoverClient) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgRecoverClient) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgRecoverClient) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgRecoverClient) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgRecoverClient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRecoverClient) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgRecoverClient) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgRecoverClient) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgRecoverClient proto.InternalMessageInfo

// MsgRecoverClientResponse defines the Msg/RecoverClient response type.
type MsgRecoverClientResponse struct {
}

func (m *MsgRecoverClientResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgRecoverClientResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgRecoverClientResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgRecoverClientResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRecoverClientResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgRecoverClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRecoverClientResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgRecoverClientResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgRecoverClientResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgRecoverClientResponse proto.InternalMessageInfo

// MsgIBCSoftwareUpgrade defines the message used to schedule an upgrade of an IBC client using a v1 governance proposal
type MsgIBCSoftwareUpgrade struct {
	Plan types1.Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan"`
	// An UpgradedClientState must be provided to perform an IBC breaking upgrade.
	// This will make the chain commit to the correct upgraded (self) client state
	// before the upgrade occurs, so that connecting chains can verify that the
	// new upgraded client is valid by verifying a proof on the previous version
	// of the chain. This will allow IBC connections to persist smoothly across
	// planned chain upgrades. Correspondingly, the UpgradedClientState field has been
	// deprecated in the Cosmos SDK to allow for this logic to exist solely in
	// the 02-client module.
	UpgradedClientState *types.Any `protobuf:"bytes,2,opt,name=upgraded_client_state,json=upgradedClientState,proto3" json:"upgraded_client_state,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgIBCSoftwareUpgrade) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgIBCSoftwareUpgrade) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgIBCSoftwareUpgrade) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgIBCSoftwareUpgrade) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgrade) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgIBCSoftwareUpgrade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgrade) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgIBCSoftwareUpgrade) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgIBCSoftwareUpgrade) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgIBCSoftwareUpgrade proto.InternalMessageInfo

func (m *MsgIBCSoftwareUpgrade) GetPlan() types1.Plan {
	_ = "STUB: not implemented"
	return *new(types1.Plan)
}

func (m *MsgIBCSoftwareUpgrade) GetUpgradedClientState() *types.Any {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgIBCSoftwareUpgrade) GetSigner() string { _ = "STUB: not implemented"; return "" }

// MsgIBCSoftwareUpgradeResponse defines the Msg/IBCSoftwareUpgrade response type.
type MsgIBCSoftwareUpgradeResponse struct {
}

func (m *MsgIBCSoftwareUpgradeResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgIBCSoftwareUpgradeResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgIBCSoftwareUpgradeResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgIBCSoftwareUpgradeResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgradeResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgIBCSoftwareUpgradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgradeResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgIBCSoftwareUpgradeResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgIBCSoftwareUpgradeResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgIBCSoftwareUpgradeResponse proto.InternalMessageInfo

// MsgUpdateParams defines the sdk.Msg type to update the client parameters.
type MsgUpdateParams struct {
	// signer address
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// params defines the client parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()                    { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParams) String() string            { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParams) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*MsgUpdateParams) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParams) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

// MsgUpdateParamsResponse defines the MsgUpdateParams response type.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgUpdateParamsResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgUpdateParamsResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgUpdateParamsResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgDeleteClientCreator defines a message to delete the client creator of a client
type MsgDeleteClientCreator struct {
	// client identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// signer address
	Signer string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (m *MsgDeleteClientCreator) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgDeleteClientCreator) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgDeleteClientCreator) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgDeleteClientCreator) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreator) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgDeleteClientCreator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreator) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *MsgDeleteClientCreator) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgDeleteClientCreator) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgDeleteClientCreator proto.InternalMessageInfo

// MsgDeleteClientCreatorResponse defines the Msg/DeleteClientCreator response type.
type MsgDeleteClientCreatorResponse struct {
}

func (m *MsgDeleteClientCreatorResponse) Reset()         { _ = "STUB: not implemented"; return }
func (m *MsgDeleteClientCreatorResponse) String() string { _ = "STUB: not implemented"; return "" }
func (*MsgDeleteClientCreatorResponse) ProtoMessage()    { _ = "STUB: not implemented"; return }
func (*MsgDeleteClientCreatorResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreatorResponse) XXX_Unmarshal(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgDeleteClientCreatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreatorResponse) XXX_Merge(src proto.Message) {
	_ = "STUB: not implemented"
	return
}

func (m *MsgDeleteClientCreatorResponse) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *MsgDeleteClientCreatorResponse) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_MsgDeleteClientCreatorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateClient)(nil), "ibc.core.client.v1.MsgCreateClient")
	proto.RegisterType((*MsgCreateClientResponse)(nil), "ibc.core.client.v1.MsgCreateClientResponse")
	proto.RegisterType((*MsgUpdateClient)(nil), "ibc.core.client.v1.MsgUpdateClient")
	proto.RegisterType((*MsgUpdateClientResponse)(nil), "ibc.core.client.v1.MsgUpdateClientResponse")
	proto.RegisterType((*MsgUpgradeClient)(nil), "ibc.core.client.v1.MsgUpgradeClient")
	proto.RegisterType((*MsgUpgradeClientResponse)(nil), "ibc.core.client.v1.MsgUpgradeClientResponse")
	proto.RegisterType((*MsgRecoverClient)(nil), "ibc.core.client.v1.MsgRecoverClient")
	proto.RegisterType((*MsgRecoverClientResponse)(nil), "ibc.core.client.v1.MsgRecoverClientResponse")
	proto.RegisterType((*MsgIBCSoftwareUpgrade)(nil), "ibc.core.client.v1.MsgIBCSoftwareUpgrade")
	proto.RegisterType((*MsgIBCSoftwareUpgradeResponse)(nil), "ibc.core.client.v1.MsgIBCSoftwareUpgradeResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "ibc.core.client.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ibc.core.client.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgDeleteClientCreator)(nil), "ibc.core.client.v1.MsgDeleteClientCreator")
	proto.RegisterType((*MsgDeleteClientCreatorResponse)(nil), "ibc.core.client.v1.MsgDeleteClientCreatorResponse")
}

func init() { proto.RegisterFile("ibc/core/client/v1/tx.proto", fileDescriptor_cb5dc4651eb49a04) }

var fileDescriptor_cb5dc4651eb49a04 = []byte{
	// 841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x3f, 0x6f, 0xdb, 0x46,
	0x14, 0x17, 0x65, 0x59, 0xa8, 0xcf, 0xb2, 0x55, 0x9f, 0x65, 0x5b, 0xa6, 0x6b, 0x49, 0x50, 0x3d,
	0xb8, 0x6a, 0x4d, 0x5a, 0x2a, 0xd0, 0x3f, 0x6e, 0x3b, 0xd8, 0xea, 0x50, 0x0f, 0x02, 0x0c, 0x19,
	0x5d, 0x3a, 0x54, 0x26, 0xa9, 0x13, 0xcb, 0x56, 0xe4, 0x11, 0x3c, 0x52, 0x8d, 0xb7, 0x20, 0x53,
	0x90, 0x29, 0x43, 0x3e, 0x40, 0x3e, 0x82, 0x91, 0x2d, 0x4b, 0xb6, 0x00, 0x1e, 0x3d, 0x66, 0x0a,
	0x02, 0x7b, 0xf0, 0x94, 0xef, 0x10, 0xe8, 0xee, 0x48, 0x93, 0x34, 0xc9, 0x28, 0xc8, 0x22, 0x88,
	0x7c, 0xbf, 0xf7, 0xde, 0xef, 0xf7, 0xfe, 0x81, 0x60, 0xcb, 0x50, 0x35, 0x59, 0xc3, 0x0e, 0x92,
	0xb5, 0xb1, 0x81, 0x2c, 0x57, 0x9e, 0xb4, 0x65, 0xf7, 0x81, 0x64, 0x3b, 0xd8, 0xc5, 0x10, 0x1a,
	0xaa, 0x26, 0x4d, 0x8d, 0x12, 0x33, 0x4a, 0x93, 0xb6, 0xb8, 0xa2, 0x98, 0x86, 0x85, 0x65, 0xfa,
	0xcb, 0x60, 0xe2, 0x86, 0x86, 0x89, 0x89, 0x89, 0x6c, 0x12, 0x7d, 0xea, 0x6e, 0x12, 0x9d, 0x1b,
	0x76, 0xb8, 0xc1, 0xb3, 0x75, 0x47, 0x19, 0x22, 0x79, 0xd2, 0x56, 0x91, 0xab, 0xb4, 0xfd, 0x67,
	0x8e, 0xaa, 0xe8, 0x58, 0xc7, 0xf4, 0xaf, 0x3c, 0xfd, 0xc7, 0xdf, 0x6e, 0xea, 0x18, 0xeb, 0x63,
	0x24, 0xd3, 0x27, 0xd5, 0x1b, 0xc9, 0x8a, 0x75, 0xce, 0x4d, 0xf5, 0x04, 0xce, 0x9c, 0x20, 0x05,
	0x34, 0x5f, 0x08, 0xa0, 0xdc, 0x23, 0x7a, 0xd7, 0x41, 0x8a, 0x8b, 0xba, 0xd4, 0x02, 0x7f, 0x04,
	0x25, 0x86, 0x19, 0x10, 0x57, 0x71, 0x51, 0x55, 0x68, 0x08, 0xbb, 0x8b, 0x9d, 0x8a, 0xc4, 0xd2,
	0x48, 0x7e, 0x1a, 0xe9, 0xd0, 0x3a, 0xef, 0x2f, 0x32, 0xe4, 0xe9, 0x14, 0x08, 0x7f, 0x03, 0x65,
	0x0d, 0x5b, 0x04, 0x59, 0xc4, 0x23, 0xdc, 0x37, 0x9f, 0xe1, 0xbb, 0x1c, 0x80, 0x99, 0xfb, 0x3a,
	0x28, 0x12, 0x43, 0xb7, 0x90, 0x53, 0x9d, 0x6b, 0x08, 0xbb, 0x0b, 0x7d, 0xfe, 0x74, 0x50, 0x7e,
	0xfc, 0xbc, 0x9e, 0x7b, 0x74, 0x7b, 0xd1, 0xe2, 0x2f, 0x9a, 0xbf, 0x82, 0x8d, 0x18, 0xe7, 0x3e,
	0x22, 0xf6, 0x34, 0x18, 0xdc, 0x02, 0x0b, 0x9c, 0xbb, 0x31, 0xa4, 0xc4, 0x17, 0xfa, 0x5f, 0xb0,
	0x17, 0xc7, 0xc3, 0x83, 0xc2, 0x34, 0x50, 0xf3, 0x19, 0x93, 0xfc, 0xa7, 0x3d, 0xbc, 0x93, 0x9c,
	0xe5, 0x06, 0x7f, 0x01, 0xcb, 0xdc, 0x68, 0x22, 0x42, 0x14, 0x3d, 0x5b, 0xd5, 0x12, 0xc3, 0xf6,
	0x18, 0x74, 0x76, 0x51, 0x9b, 0x54, 0x54, 0x98, 0x95, 0x2f, 0xaa, 0xf9, 0x3a, 0x0f, 0xbe, 0xa4,
	0x36, 0x3a, 0x0b, 0xb3, 0x50, 0x8e, 0xb7, 0x30, 0xff, 0x19, 0x2d, 0x9c, 0xfb, 0x84, 0x16, 0xee,
	0x83, 0x8a, 0xed, 0x60, 0x3c, 0x1a, 0xf0, 0xb9, 0x1d, 0xb0, 0xd8, 0xd5, 0x42, 0x43, 0xd8, 0x2d,
	0xf5, 0x21, 0xb5, 0x45, 0x65, 0x1c, 0x82, 0xed, 0x98, 0x47, 0x2c, 0xfd, 0x3c, 0x75, 0x15, 0x23,
	0xae, 0x69, 0x73, 0x53, 0xcc, 0x2e, 0xb1, 0x08, 0xaa, 0xf1, 0x32, 0x06, 0x35, 0x7e, 0x29, 0xd0,
	0x1a, 0xf7, 0x91, 0x86, 0x27, 0xc8, 0xe1, 0xe4, 0x5a, 0x60, 0x85, 0x78, 0xea, 0xbf, 0x48, 0x73,
	0x07, 0xf1, 0x5a, 0x97, 0xb9, 0xa1, 0xeb, 0x97, 0x7c, 0x1f, 0x54, 0x88, 0xa7, 0x12, 0xd7, 0x70,
	0x3d, 0x17, 0x85, 0xe0, 0x79, 0x0a, 0x87, 0x77, 0xb6, 0xc0, 0x23, 0x6d, 0x34, 0xe4, 0x18, 0xef,
	0x27, 0xb7, 0x17, 0xad, 0x2d, 0x76, 0x1f, 0xf6, 0xc8, 0xf0, 0x3f, 0x39, 0x4e, 0x93, 0xeb, 0x8a,
	0xbc, 0x0b, 0x74, 0xbd, 0x12, 0xc0, 0x5a, 0x8f, 0xe8, 0xc7, 0x47, 0xdd, 0x53, 0x3c, 0x72, 0xff,
	0x57, 0x1c, 0xc4, 0xf5, 0xc3, 0x1f, 0x40, 0xc1, 0x1e, 0x2b, 0x16, 0x5f, 0xef, 0xaf, 0x24, 0x96,
	0x41, 0xf2, 0x2f, 0x0e, 0xbf, 0x40, 0xd2, 0xc9, 0x58, 0xb1, 0x8e, 0x0a, 0x97, 0x6f, 0xeb, 0xb9,
	0x3e, 0xc5, 0xc3, 0x3f, 0xc0, 0x1a, 0xc7, 0x0c, 0x07, 0x33, 0x0f, 0xd9, 0xaa, 0xef, 0xd2, 0x0d,
	0x0d, 0x5b, 0x5a, 0x01, 0x16, 0xc3, 0x4d, 0xab, 0x83, 0xed, 0x44, 0xfe, 0x81, 0x42, 0x37, 0xb4,
	0xce, 0x27, 0x8a, 0xa3, 0x98, 0x24, 0x14, 0x58, 0x08, 0x07, 0x86, 0x3f, 0x81, 0xa2, 0x4d, 0x11,
	0x9c, 0xab, 0x28, 0xdd, 0x3f, 0xdb, 0x12, 0x8b, 0xc1, 0x25, 0x73, 0x7c, 0xf6, 0xba, 0x32, 0x8f,
	0x80, 0xd0, 0xdf, 0x60, 0xbd, 0x47, 0xf4, 0xdf, 0xd1, 0x18, 0xf9, 0xcd, 0xa6, 0xa7, 0x0a, 0x3b,
	0xd9, 0x3b, 0x7b, 0x47, 0x3a, 0x9f, 0x3d, 0xc6, 0x0d, 0x50, 0x4b, 0x8e, 0xef, 0x33, 0xe8, 0xbc,
	0x9f, 0x07, 0x73, 0x3d, 0xa2, 0xc3, 0x33, 0x50, 0x8a, 0x5c, 0xf6, 0xaf, 0x93, 0xf4, 0xc6, 0x4e,
	0xa9, 0xf8, 0xed, 0x0c, 0xa0, 0xe0, 0xde, 0x9e, 0x81, 0x52, 0xe4, 0x90, 0xa6, 0x65, 0x08, 0x83,
	0x52, 0x33, 0x24, 0x1d, 0x3f, 0xa8, 0x81, 0xa5, 0xe8, 0xc5, 0xd8, 0x49, 0xf5, 0x0e, 0xa1, 0xc4,
	0xef, 0x66, 0x41, 0x85, 0x93, 0x44, 0x37, 0x3f, 0x2d, 0x49, 0x04, 0x95, 0x9a, 0x24, 0x71, 0x15,
	0xa1, 0x03, 0x60, 0xc2, 0x1a, 0x7e, 0x93, 0x12, 0xe3, 0x3e, 0x54, 0x6c, 0xcf, 0x0c, 0x0d, 0x72,
	0x8e, 0x00, 0x0c, 0x57, 0x95, 0xef, 0x47, 0x76, 0x97, 0x18, 0xe8, 0x23, 0x5d, 0x8a, 0xce, 0x3c,
	0xf4, 0xc0, 0x6a, 0xd2, 0xc0, 0xb7, 0x52, 0x62, 0x24, 0x60, 0xc5, 0xce, 0xec, 0x58, 0x3f, 0xad,
	0x38, 0xff, 0xf0, 0xf6, 0xa2, 0x25, 0x1c, 0x9d, 0x5e, 0x5e, 0xd7, 0x84, 0xab, 0xeb, 0x9a, 0xf0,
	0xee, 0xba, 0x26, 0x3c, 0xbd, 0xa9, 0xe5, 0xae, 0x6e, 0x6a, 0xb9, 0x37, 0x37, 0xb5, 0xdc, 0x5f,
	0x3f, 0xeb, 0x86, 0xfb, 0x8f, 0xa7, 0x4a, 0x1a, 0x36, 0x65, 0xfe, 0x89, 0x65, 0xa8, 0xda, 0x9e,
	0x8e, 0xe5, 0x49, 0xbb, 0x2d, 0x9b, 0x78, 0xe8, 0x8d, 0x11, 0x61, 0x5f, 0x48, 0xfb, 0x9d, 0x3d,
	0xfe, 0x91, 0xe4, 0x9e, 0xdb, 0x88, 0xa8, 0x45, 0x7a, 0xc0, 0xbe, 0xff, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0x29, 0xc2, 0xfe, 0xf8, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateClient defines a rpc handler method for MsgCreateClient.
	CreateClient(ctx context.Context, in *MsgCreateClient, opts ...grpc.CallOption) (*MsgCreateClientResponse, error)
	// UpdateClient defines a rpc handler method for MsgUpdateClient.
	UpdateClient(ctx context.Context, in *MsgUpdateClient, opts ...grpc.CallOption) (*MsgUpdateClientResponse, error)
	// UpgradeClient defines a rpc handler method for MsgUpgradeClient.
	UpgradeClient(ctx context.Context, in *MsgUpgradeClient, opts ...grpc.CallOption) (*MsgUpgradeClientResponse, error)
	// RecoverClient defines a rpc handler method for MsgRecoverClient.
	RecoverClient(ctx context.Context, in *MsgRecoverClient, opts ...grpc.CallOption) (*MsgRecoverClientResponse, error)
	// IBCSoftwareUpgrade defines a rpc handler method for MsgIBCSoftwareUpgrade.
	IBCSoftwareUpgrade(ctx context.Context, in *MsgIBCSoftwareUpgrade, opts ...grpc.CallOption) (*MsgIBCSoftwareUpgradeResponse, error)
	// UpdateClientParams defines a rpc handler method for MsgUpdateParams.
	UpdateClientParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// DeleteClientCreator defines a rpc handler method for MsgDeleteClientCreator.
	DeleteClientCreator(ctx context.Context, in *MsgDeleteClientCreator, opts ...grpc.CallOption) (*MsgDeleteClientCreatorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient { _ = "STUB: not implemented"; return *new(MsgClient) }

func (c *msgClient) CreateClient(ctx context.Context, in *MsgCreateClient, opts ...grpc.CallOption) (*MsgCreateClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) UpdateClient(ctx context.Context, in *MsgUpdateClient, opts ...grpc.CallOption) (*MsgUpdateClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) UpgradeClient(ctx context.Context, in *MsgUpgradeClient, opts ...grpc.CallOption) (*MsgUpgradeClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) RecoverClient(ctx context.Context, in *MsgRecoverClient, opts ...grpc.CallOption) (*MsgRecoverClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) IBCSoftwareUpgrade(ctx context.Context, in *MsgIBCSoftwareUpgrade, opts ...grpc.CallOption) (*MsgIBCSoftwareUpgradeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) UpdateClientParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *msgClient) DeleteClientCreator(ctx context.Context, in *MsgDeleteClientCreator, opts ...grpc.CallOption) (*MsgDeleteClientCreatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateClient defines a rpc handler method for MsgCreateClient.
	CreateClient(context.Context, *MsgCreateClient) (*MsgCreateClientResponse, error)
	// UpdateClient defines a rpc handler method for MsgUpdateClient.
	UpdateClient(context.Context, *MsgUpdateClient) (*MsgUpdateClientResponse, error)
	// UpgradeClient defines a rpc handler method for MsgUpgradeClient.
	UpgradeClient(context.Context, *MsgUpgradeClient) (*MsgUpgradeClientResponse, error)
	// RecoverClient defines a rpc handler method for MsgRecoverClient.
	RecoverClient(context.Context, *MsgRecoverClient) (*MsgRecoverClientResponse, error)
	// IBCSoftwareUpgrade defines a rpc handler method for MsgIBCSoftwareUpgrade.
	IBCSoftwareUpgrade(context.Context, *MsgIBCSoftwareUpgrade) (*MsgIBCSoftwareUpgradeResponse, error)
	// UpdateClientParams defines a rpc handler method for MsgUpdateParams.
	UpdateClientParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// DeleteClientCreator defines a rpc handler method for MsgDeleteClientCreator.
	DeleteClientCreator(context.Context, *MsgDeleteClientCreator) (*MsgDeleteClientCreatorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateClient(ctx context.Context, req *MsgCreateClient) (*MsgCreateClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) UpdateClient(ctx context.Context, req *MsgUpdateClient) (*MsgUpdateClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) UpgradeClient(ctx context.Context, req *MsgUpgradeClient) (*MsgUpgradeClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) RecoverClient(ctx context.Context, req *MsgRecoverClient) (*MsgRecoverClientResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) IBCSoftwareUpgrade(ctx context.Context, req *MsgIBCSoftwareUpgrade) (*MsgIBCSoftwareUpgradeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) UpdateClientParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*UnimplementedMsgServer) DeleteClientCreator(ctx context.Context, req *MsgDeleteClientCreator) (*MsgDeleteClientCreatorResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) { _ = "STUB: not implemented"; return }

func _Msg_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_UpdateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_UpgradeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_RecoverClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_IBCSoftwareUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_UpdateClientParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _Msg_DeleteClientCreator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.core.client.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _Msg_CreateClient_Handler,
		},
		{
			MethodName: "UpdateClient",
			Handler:    _Msg_UpdateClient_Handler,
		},
		{
			MethodName: "UpgradeClient",
			Handler:    _Msg_UpgradeClient_Handler,
		},
		{
			MethodName: "RecoverClient",
			Handler:    _Msg_RecoverClient_Handler,
		},
		{
			MethodName: "IBCSoftwareUpgrade",
			Handler:    _Msg_IBCSoftwareUpgrade_Handler,
		},
		{
			MethodName: "UpdateClientParams",
			Handler:    _Msg_UpdateClientParams_Handler,
		},
		{
			MethodName: "DeleteClientCreator",
			Handler:    _Msg_DeleteClientCreator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/core/client/v1/tx.proto",
}

func (m *MsgCreateClient) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgCreateClient) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgCreateClient) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgCreateClientResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgCreateClientResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgCreateClientResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateClient) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateClient) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateClient) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateClientResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateClientResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateClientResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpgradeClient) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpgradeClient) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpgradeClient) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpgradeClientResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpgradeClientResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpgradeClientResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRecoverClient) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRecoverClient) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRecoverClient) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRecoverClientResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgRecoverClientResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgRecoverClientResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgIBCSoftwareUpgrade) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgrade) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgIBCSoftwareUpgrade) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgIBCSoftwareUpgradeResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgIBCSoftwareUpgradeResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgIBCSoftwareUpgradeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgDeleteClientCreator) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreator) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgDeleteClientCreator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgDeleteClientCreatorResponse) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *MsgDeleteClientCreatorResponse) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *MsgDeleteClientCreatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *MsgCreateClient) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgCreateClientResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateClient) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateClientResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpgradeClient) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpgradeClientResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgRecoverClient) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgRecoverClientResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgIBCSoftwareUpgrade) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgIBCSoftwareUpgradeResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParams) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgUpdateParamsResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgDeleteClientCreator) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgDeleteClientCreatorResponse) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozTx(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *MsgCreateClient) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgCreateClientResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateClient) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateClientResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpgradeClient) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpgradeClientResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgRecoverClient) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgRecoverClientResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgIBCSoftwareUpgrade) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgIBCSoftwareUpgradeResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgDeleteClientCreator) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *MsgDeleteClientCreatorResponse) Unmarshal(dAtA []byte) error {
	_ = "STUB: not implemented"
	return nil
}

func skipTx(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
