// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/wasm/v1/wasm.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v11/modules/core/02-client/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Wasm light client's Client state
type ClientState struct {
	// bytes encoding the client state of the underlying light client
	// implemented as a Wasm contract.
	Data         []byte       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Checksum     []byte       `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	LatestHeight types.Height `protobuf:"bytes,3,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height"`
}

func (m *ClientState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// Wasm light client's ConsensusState
type ConsensusState struct {
	// bytes encoding the consensus state of the underlying light client
	// implemented as a Wasm contract.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ConsensusState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConsensusState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConsensusState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConsensusState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConsensusState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConsensusState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// Wasm light client message (either header(s) or misbehaviour)
type ClientMessage struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ClientMessage) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ClientMessage) String() string            { _ = "STUB: not implemented"; return "" }
func (*ClientMessage) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ClientMessage) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ClientMessage) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientMessage) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ClientMessage) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ClientMessage) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ClientMessage proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.wasm.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.wasm.v1.ConsensusState")
	proto.RegisterType((*ClientMessage)(nil), "ibc.lightclients.wasm.v1.ClientMessage")
}

func init() {
	proto.RegisterFile("ibc/lightclients/wasm/v1/wasm.proto", fileDescriptor_678928ebbdee1807)
}

var fileDescriptor_678928ebbdee1807 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4e, 0xc3, 0x30,
	0x18, 0x85, 0x63, 0xa8, 0x10, 0x72, 0x5b, 0x86, 0x88, 0x21, 0xca, 0x90, 0x56, 0x65, 0x29, 0x48,
	0xb5, 0x09, 0x2c, 0x88, 0x09, 0xb5, 0x42, 0x62, 0x61, 0x29, 0x5b, 0x17, 0xe4, 0xb8, 0x96, 0x63,
	0x91, 0xd4, 0x55, 0x7f, 0xa7, 0x88, 0x1b, 0x20, 0x26, 0x8e, 0xc0, 0x71, 0x3a, 0x76, 0x64, 0x42,
	0xa8, 0xbd, 0x08, 0xb2, 0x1d, 0x10, 0x0b, 0x4c, 0x79, 0x79, 0xfe, 0xfc, 0xff, 0x4f, 0x7e, 0xf8,
	0x48, 0x65, 0x9c, 0x16, 0x4a, 0xe6, 0x86, 0x17, 0x4a, 0xcc, 0x0c, 0xd0, 0x47, 0x06, 0x25, 0x5d,
	0xa6, 0xee, 0x4b, 0xe6, 0x0b, 0x6d, 0x74, 0x18, 0xa9, 0x8c, 0x93, 0xdf, 0x10, 0x71, 0x87, 0xcb,
	0x34, 0x3e, 0x94, 0x5a, 0x6a, 0x07, 0x51, 0xab, 0x3c, 0x1f, 0x77, 0xec, 0x50, 0xae, 0x17, 0x82,
	0x7a, 0xde, 0x8e, 0xf3, 0xca, 0x03, 0xbd, 0x17, 0x84, 0x9b, 0x23, 0x67, 0xdc, 0x19, 0x66, 0x44,
	0x18, 0xe2, 0xc6, 0x94, 0x19, 0x16, 0xa1, 0x2e, 0xea, 0xb7, 0xc6, 0x4e, 0x87, 0x31, 0xde, 0xe7,
	0xb9, 0xe0, 0x0f, 0x50, 0x95, 0xd1, 0x8e, 0xf3, 0x7f, 0xfe, 0xc3, 0x6b, 0xdc, 0x2e, 0x98, 0x11,
	0x60, 0xee, 0x73, 0x61, 0x63, 0x45, 0xbb, 0x5d, 0xd4, 0x6f, 0x9e, 0xc5, 0xc4, 0x06, 0xb5, 0x8b,
	0x49, 0xbd, 0x6e, 0x99, 0x92, 0x1b, 0x47, 0x0c, 0x1b, 0xab, 0x8f, 0x4e, 0x30, 0x6e, 0xf9, 0x6b,
	0xde, 0xbb, 0x6c, 0x3c, 0xbf, 0x75, 0x82, 0xde, 0x09, 0x3e, 0x18, 0xe9, 0x19, 0x88, 0x19, 0x54,
	0xf0, 0x67, 0x9c, 0x9a, 0x3d, 0xc6, 0x6d, 0x9f, 0xfb, 0x56, 0x00, 0x30, 0xf9, 0x0f, 0x3a, 0x9c,
	0xac, 0x36, 0x09, 0x5a, 0x6f, 0x12, 0xf4, 0xb9, 0x49, 0xd0, 0xeb, 0x36, 0x09, 0xd6, 0xdb, 0x24,
	0x78, 0xdf, 0x26, 0xc1, 0xe4, 0x4a, 0x2a, 0x93, 0x57, 0x19, 0xe1, 0xba, 0xa4, 0x5c, 0x43, 0xa9,
	0x81, 0xaa, 0x8c, 0x0f, 0xa4, 0xa6, 0xa5, 0x9e, 0x56, 0x85, 0x00, 0x5f, 0xc8, 0xe0, 0xbb, 0x91,
	0xd3, 0x8b, 0x41, 0x5d, 0x4a, 0x4a, 0xcd, 0xd3, 0x5c, 0x40, 0xb6, 0xe7, 0x9e, 0xf1, 0xfc, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0xd9, 0x3e, 0xca, 0x8d, 0xbe, 0x01, 0x00, 0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ClientMessage) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ClientMessage) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ClientMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintWasm(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConsensusState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientMessage) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovWasm(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozWasm(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ClientState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConsensusState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ClientMessage) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipWasm(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthWasm        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWasm          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWasm = fmt.Errorf("proto: unexpected end of group")
)
